### ISSUE TITLE
Backport PCRE2 10.37 shows unexpected result

### ISSUE THREAD

**Issue by tuyennn** [oerdnj/deb.sury.org#1654] opened 2021-10-05 11:15 UTC
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Latest PPA
Could provide the fix on this or backport
https://bugs.php.net/bug.php?id=81101 
Affected version 7.3.31, 7.4.24

Need to set pcre.jit = 0 for workaround

**To Reproduce**
1. Using Magento 2 all versions
2. Deploy with `php bin/magento setup:upgrade;php bin/magento setup:static-content:deploy -f;php bin/magento cache:flush`
3. Check the frontend and adminside
4. See error as no styling be loaded

**Expected behavior**
styling be loaded

**Distribution (please complete the following information):**
 - OS:Ubuntu 21.04
 - Architecture: amd64
 - Repository: ppa:ondrej/php

**Package(s) (please complete the following information):**
```
php7.3:
  Installed: (none)
  Candidate: 7.3.31-1+ubuntu21.04.1+deb.sury.org+1
  Version table:
     7.3.31-1+ubuntu21.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute/main amd64 Packages
        500 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute/main i386 Packages
```
```
php7.4:
  Installed: 7.4.24-1+ubuntu21.04.1+deb.sury.org+1
  Candidate: 7.4.24-1+ubuntu21.04.1+deb.sury.org+1
  Version table:
 *** 7.4.24-1+ubuntu21.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute/main amd64 Packages
        500 http://ppa.launchpad.net/ondrej/php/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status

```

**Additional context**

**Comment by oerdnj** [comment] 2021-10-05 11:21
Duplicate of #1653

**Closed by oerdnj** 2021-10-05 11:21 UTC
