### ISSUE TITLE
libgd3 & libgd3:i386 packages are held back

### ISSUE THREAD

**Issue by emodric** [oerdnj/deb.sury.org#1918] opened 2023-01-25 09:55 UTC
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**

When running `sudo apt upgrade`, I get the message that some packages have been kept back:

```
eddie@abyss ~ $ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  libgd3 libgd3:i386
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
```

**Your understanding of what is happening**

It seems to me like there's some kind of cyclic dependency problem here, but I don't know anything about `apt` besides using it to install and update packages.

**What steps did you take to resolve issue yourself before reporting it here**

If I try to reinstall the packages:

```
eddie@abyss ~ $ sudo apt install --reinstall libgd3 libgd3:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd3 : Breaks: libgd3:i386 (!= 2.3.3-7+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-6+ubuntu22.04.1+deb.sury.org+1 is to be installed
 libgd3:i386 : Breaks: libgd3 (!= 2.3.3-6+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-7+ubuntu22.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

If I try to remove them first, a plethora of system packages would be removed as well, so that's not an option.

**Expected behavior**

I expect for both packges to be installed normally.

**Distribution:**

 - OS: Ubuntu 22.04 LTS
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s):**

```
eddie@abyss ~ $ sudo apt-cache policy libgd3
libgd3:
  Installed: 2.3.3-5+ubuntu22.04.1+deb.sury.org+1
  Candidate: 2.3.3-7+ubuntu22.04.1+deb.sury.org+1
  Version table:
     2.3.3-7+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main amd64 Packages
 *** 2.3.3-5+ubuntu22.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     2.3.0-2ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages

eddie@abyss ~ $ sudo apt-cache policy libgd3:i386
libgd3:i386:
  Installed: 2.3.3-5+ubuntu22.04.1+deb.sury.org+1
  Candidate: 2.3.3-6+ubuntu22.04.1+deb.sury.org+1
  Version table:
     2.3.3-6+ubuntu22.04.1+deb.sury.org+1 500
        500 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy/main i386 Packages
 *** 2.3.3-5+ubuntu22.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     2.3.0-2ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu jammy/main i386 Packages
```

**Comment by droplinxuser** [comment] 2023-01-25 09:58
I'm not an expert on this, but you can try:
`sudo apt install --only-upgrade libgd3 libgd3:i386`

**Comment by emodric** [comment] 2023-01-25 10:20
@droplinxuser Nope, same error:

```
eddie@abyss ~ $ sudo apt install --only-upgrade libgd3 libgd3:i386
[sudo] password for eddie: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgd3 : Breaks: libgd3:i386 (!= 2.3.3-7+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-6+ubuntu22.04.1+deb.sury.org+1 is to be installed
 libgd3:i386 : Breaks: libgd3 (!= 2.3.3-6+ubuntu22.04.1+deb.sury.org+1) but 2.3.3-7+ubuntu22.04.1+deb.sury.org+1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by todeveni** [comment] 2023-01-25 10:23
Duplicate of #1873. See https://github.com/oerdnj/deb.sury.org/issues/1873#issuecomment-1343164132.

**Closed** 2023-01-25 10:36 UTC
