### ISSUE TITLE
unlike amd64, for arm64 php 8.3.13 only available for php8.3 while 8.3.12 is latest for php8.3-*

### ISSUE THREAD

**Issue by satphil** [oerdnj/deb.sury.org#2224] opened 2024-11-20 10:52 UTC
**Frequently asked questions**

- [ X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ X] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ X] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**
I upgraded my php8.3 this afternoon on amd64 and arm64 systems. 
On amd64 all upgraded to:
8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc

However on arm64, only php8.3 upgraded to:
8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
while the rest of the php8.3-* packages (e.g. php8.3-cli, php8.3-common) stayed at 
8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c

**To Reproduce**
On amd64 and arm64 systems run
apt update && apt-cache policy php8.3 php8.3-cli php8.3-common

On amd64, all 3 have:
Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc

On arm64, php8.3 has
Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
but php8.3-cli and php8.3-common are stuck back at
Candidate: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c

**Your understanding of what is happening**
Suspicions arise as to possible sub-optimal arm64 packaging.

**What steps did you take to resolve issue yourself before reporting it here**
Re-ran "apt update" but with no better result

**Expected behavior**
Expect all the packages to upgrade to the same level and for arm64 and amd64 to keep in step so our test and dev systems can mirror our production system config.

**Distribution (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm)
 - Architecture: 6.1.0-27-amd64 vs 6.1.0-27-cloud-arm64
 - Repository: https://packages.sury.org/php bookworm/main amd64 Packages vs
 - https://packages.sury.org/php bookworm/main arm64 Packages

**Package(s) (please complete the following information):**
# apt-cache policy php8.3 php8.3-cli php8.3-common
php8.3:
  Installed: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Version table:
 *** 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
php8.3-cli:
  Installed: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Version table:
 *** 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
php8.3-common:
  Installed: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Version table:
 *** 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

vs

# apt-cache policy php8.3 php8.3-cli php8.3-common
php8.3:
  Installed: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Candidate: 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc
  Version table:
 *** 8.3.13-1+0~20241104.46+debian12~1.gbpaaf4dc 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
php8.3-cli:
  Installed: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c
  Candidate: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c
  Version table:
 *** 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status
php8.3-common:
  Installed: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c
  Candidate: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c
  Version table:
 *** 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c 500
        500 https://packages.sury.org/php bookworm/main arm64 Packages
        100 /var/lib/dpkg/status

**Additional context**
Packages affected include:

php-common is already the newest version (2:95+0~20240927.54+debian12~1.gbpe0084c).
php8.3-cli is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-common is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-curl is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-fpm is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-gd is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-mbstring is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-mysql is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-opcache is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-readline is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).
php8.3-xml is already the newest version (8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c).

**Comment by rfay** [comment] 2024-11-20 14:46
I confirm this. On arm64 only 8.3.12, on amd64 8.3.13.

**Comment by oerdnj** [comment] 2024-11-20 15:02
Duplicate of #2220

**Closed by oerdnj** 2024-11-20 15:02 UTC
