### ISSUE TITLE
linux php5.6 kurulumu başarısız

### ISSUE THREAD

**Issue by msamgar** [oerdnj/deb.sury.org#1292] opened 2019-12-10 10:56 UTC
Hi,
I am trying to install php5.6 on Ubuntu 18.04 but it fails. The code I tried to run and the error I received was as follows. I think there is no problem with my network settings because I had previously installed postgresql 9.4. I can access all websites through Mozilla. I don't use any firewalls either. Please guide me.
Code: sudo add-apt-repository ppa: ondrej / php -y
Error: retrieving gpg key timed out.

**Comment by oerdnj** [comment] 2019-12-10 10:57
Duplicate of #1291, don't fill duplicate issues.

It's your local problem, not a problem with the connectivity.

**Closed by oerdnj** 2019-12-10 10:57 UTC
