### ISSUE TITLE
Missing arm64 Debian packages

### ISSUE THREAD

**Issue by Zenexer** [oerdnj/deb.sury.org#2220] opened 2024-11-04 20:57 UTC
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and concise manner

**Describe the bug**

php8.3-common version 8.3.13 is missing for debian bookworm arm64; the latest version is 8.3.12:

```
# apt show php8.3-common:arm64
Package: php8.3-common
Version: 8.3.12-1+0~20240927.43+debian12~1.gbpad3b8c
Priority: optional
Section: php
Source: php8.3
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 10.1 MB
Provides: php-calendar, php-ctype, php-exif, php-ffi, php-fileinfo, php-ftp, php-iconv, php-pdo, php-phar, php-posix, php-shmop, php-sockets, php-sysvmsg, php-sysvsem, php-sysvshm, php-tokenizer, php8.3-calendar, php8.3-ctype, php8.3-exif, php8.3-ffi, php8.3-fileinfo, php8.3-ftp, php8.3-gettext, php8.3-iconv, php8.3-pdo, php8.3-phar, php8.3-posix, php8.3-shmop, php8.3-sockets, php8.3-sysvmsg, php8.3-sysvsem, php8.3-sysvshm, php8.3-tokenizer
Depends: php-common (>= 1:81~), ucf, libc6 (>= 2.34), libffi8 (>= 3.4), libssl3 (>= 3.0.0)
Breaks: gforge-common (<< 6), php7.0-curl (<< 7.0.33-1~), php7.2-sodium (<< 7.2.12~)
Homepage: http://www.php.net/
Download-Size: 686 kB
APT-Manual-Installed: yes
APT-Sources: https://packages.sury.org/php bookworm/main arm64 Packages
Description: documentation, examples and common module for PHP
 This package provides the documentation, examples and common module(s) for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
```

It's present for amd64:

```
# apt info php8.3-common:amd64
Package: php8.3-common:amd64
Version: 8.3.13-1+0~20241030.44+debian12~1.gbpaaf4dc
Priority: optional
Section: php
Source: php8.3
Maintainer: Debian PHP Maintainers <team+pkg-php@tracker.debian.org>
Installed-Size: 9585 kB
Provides: php-calendar, php-ctype, php-exif, php-ffi, php-fileinfo, php-ftp, php-iconv, php-pdo, php-phar, php-posix, php-shmop, php-sockets, php-sysvmsg, php-sysvsem, php-sysvshm, php-tokenizer, php8.3-calendar, php8.3-ctype, php8.3-exif, php8.3-ffi, php8.3-fileinfo, php8.3-ftp, php8.3-gettext, php8.3-iconv, php8.3-pdo, php8.3-phar, php8.3-posix, php8.3-shmop, php8.3-sockets, php8.3-sysvmsg, php8.3-sysvsem, php8.3-sysvshm, php8.3-tokenizer
Depends: php-common (>= 1:81~), ucf, libc6 (>= 2.34), libffi8 (>= 3.4), libssl3 (>= 3.0.0)
Breaks: gforge-common (<< 6), php7.0-curl (<< 7.0.33-1~), php7.2-sodium (<< 7.2.12~)
Homepage: http://www.php.net/
Download-Size: 714 kB
APT-Sources: https://packages.sury.org/php bookworm/main amd64 Packages
Description: documentation, examples and common module for PHP
 This package provides the documentation, examples and common module(s) for PHP.
 .
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used
 open source general-purpose scripting language that is especially suited
 for web development and can be embedded into HTML.
```

**Additional context**

APT list file for arm64:

```
deb [arch=arm64 signed-by=/usr/share/keyrings/sury-archive-keyring.gpg] https://packages.sury.org/php/ bookworm main
```

APT list file for amd64:

```
deb [arch=amd64 signed-by=/usr/share/keyrings/sury-archive-keyring.gpg] https://packages.sury.org/php/ bookworm main
```

Using Docker, latest bookworm as a base, with the default `debian.sources` file renamed to `debian.sources.disabled` for testing purposes.  `apt update` run between each test.

**Comment by rfay** [comment] 2024-11-04 21:46
All recent ARM64 builds are missing.

**Comment by Zenexer** [comment] 2024-11-04 22:10
@rfay I'm seeing php8.3-common at 8.3.13 on Ubuntu 24.04 (noble) arm64, so I don't think that's true.

**Comment by rfay** [comment] 2024-11-04 22:22
This issue is about Debian Bookworm

**Comment by rfay** [comment] 2024-11-04 22:23
You can see the dates and versions at https://packages.sury.org/php/pool/main/p/php8.3/ and friends.

**Comment by Zenexer** [comment] 2024-11-04 22:47
That's only for Debian. This GitHub issue tracker also handles the Ubuntu PPA, which has a different endpoint.

**Comment by rfay** [comment] 2024-11-04 22:54
This issue is about PHP 8.3 on Debian. The title of this issue is:
> Missing php8.3-common arm64 package for debian bookworm, php 8.3.13

**Comment by Zenexer** [comment] 2024-11-04 22:57
Yes, and I want to be clear that it is *not* all arm64 packages covered by this issue tracker and maintained by Ondrej that are missing--it's _just_ the Debian packages.

**Comment by oerdnj** [comment] 2024-11-04 23:14
Well, I understood what @rfay was saying…. You can now stop with the back and forth on the issue.

**Comment by oerdnj** [comment] 2024-11-11 11:31
So, the issue is that the arm64 chroots started to segfault qemu-user-static (`ldconfig` segfaults).

I tried to upgrade the `qemu-user-static` to a version from bookworm-backports, that didn't help.

So far, looks like deleting and recreating the chroot have had helped - with one problem, but the compiler still segfaults.

Can't wait for the [debusine](https://debusine.debian.net) to be finally ready to replace the [jenkins-debian-glue](https://jenkins-debian-glue.org) and finally have a native builder for arm64.

**Comment by rfay** [comment] 2024-11-11 13:22
Thanks so much for working on it. Eagerly awaiting the solution.

**Comment by rfay** [comment] 2024-11-17 16:18
@oerdnj we're really hoping to do a DDEV release soon after PHP 8.4.0 comes out in just a few days, but half of the userbase is arm64 (newer macs).  Is there anything we can do to help with this, help resolve the segfault or anything? We've also seen crashes in qemu-user-static as well over the years (in docker image builds), but are not having that at this point.

**Comment by oerdnj** [comment] 2024-11-17 16:39
@rfay The current status is that Debian bullseye is segfaulting while bookworm looks currently fine to me.

```
[ 8645.184842] gcc[1498330]: segfault at 309a3c0 ip 00000000006278d0 sp 00007ffe97a184b8 error 4 in qemu-aarch64-static[401000+46a000] likely on CPU 0 (core 0, socket 0)
[ 8645.184847] Code: 86 6d 1b 00 66 0f 1f 44 00 00 64 83 2c 25 40 ff ff ff 01 74 05 c3 0f 1f 40 00 bf c0 56 e1 00 e9 76 7b 1b 00 66 0f 1f 44 00 00 <64> 8b 04 25 40 ff ff ff 85 c0 0f 9f c0 c3 66 90 64 8b 14 25 40 ff
[ 8735.794401] gcc[1510252]: segfault at 32723c0 ip 00000000006278d0 sp 00007ffd4ed99b58 error 4 in qemu-aarch64-static[401000+46a000] likely on CPU 28 (core 44, socket 0)
[ 8735.794410] Code: 86 6d 1b 00 66 0f 1f 44 00 00 64 83 2c 25 40 ff ff ff 01 74 05 c3 0f 1f 40 00 bf c0 56 e1 00 e9 76 7b 1b 00 66 0f 1f 44 00 00 <64> 8b 04 25 40 ff ff ff 85 c0 0f 9f c0 c3 66 90 64 8b 14 25 40 ff
[ 9568.308564] cc1[1663481]: segfault at 45873c0 ip 00000000006278d0 sp 00007ffc63104598 error 4 in qemu-aarch64-static[401000+46a000] likely on CPU 15 (core 28, socket 0)
[ 9568.308573] Code: 86 6d 1b 00 66 0f 1f 44 00 00 64 83 2c 25 40 ff ff ff 01 74 05 c3 0f 1f 40 00 bf c0 56 e1 00 e9 76 7b 1b 00 66 0f 1f 44 00 00 <64> 8b 04 25 40 ff ff ff 85 c0 0f 9f c0 c3 66 90 64 8b 14 25 40 ff
```

**Comment by rfay** [comment] 2024-11-17 17:04
Well fantastic, thanks. I had been checking it almost daily, but didn't check before writing this. Now I see 8.4.0RC4 on Bookworm, thanks!

Commented in 
* #2176 

about the extensions we're hoping for.

**Comment by oerdnj** [comment] 2024-11-17 17:53
I've updated the qemu to 9.2.0~rc, we will see if that helps. I have no idea why and when this become broken.

**Comment by oerdnj** [comment] 2024-11-20 15:02
So, nope, the new qemu version didn't really help.

**Comment by oerdnj** [comment] 2024-11-20 15:11
I think I found the cause: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1087822

**Comment by Npi4** [comment] 2024-11-21 14:50
I could just download 8.3.14.
Thank you for the work and the laborious troubleshooting.
Ik kan gewoon 8.3.14 downloaden.
Bedankt voor het werk en het moeizame oplossen van problemen.

**Comment by oerdnj** [comment] 2024-11-22 11:50
I think that all PHP Engine packages should be built now for all architectures again, but let me check whether some extensions are missing while the builders were broken, etc… before closing the issues.

**Comment by oerdnj** [comment] 2024-11-26 04:54
From the state of things, I believe this has been now fixed. Oh boy, the joys of multi-arch computers...

**Closed by oerdnj** 2024-11-26 04:54 UTC

**Comment by rfay** [comment] 2024-11-26 04:58
Congrats and thanks!

**Comment by satphil** [comment] 2024-11-29 01:39
Thanks from me as well!
