### ISSUE TITLE
Calling phpinfo() within php-fpm 7.0 crashes process

### ISSUE THREAD

**Issue by cheindl** [oerdnj/deb.sury.org#628] opened 2017-06-27 08:04 UTC
Hi,

we're using your great PHP-PPA under Ubuntu 16.04 LTS. Everytime we are executing a PHP file with simply calling phpinfo() the php-fpm process crashes and we get only an error 500 on the browser.

PHP-File to be executed (info.php):
```
<?php phpinfo();
```

Apache2 error.log:
```
[Tue Jun 27 09:57:22.115661 2017] [proxy_fcgi:error] [pid 17597] [client ::1:43400] AH01067: Failed to read FastCGI header
[Tue Jun 27 09:57:22.115723 2017] [proxy_fcgi:error] [pid 17597] (104)Connection reset by peer: [client ::1:43400] AH01075: Error dispatching request to :
```

php7.0-fpm.log:
```
[27-Jun-2017 09:57:22.115751] DEBUG: pid 17750, fpm_got_signal(), line 76: received SIGCHLD
[27-Jun-2017 09:57:22.115868] WARNING: pid 17750, fpm_children_bury(), line 252: [pool www] child 17757 exited on signal 6 (SIGABRT - core dumped) after 9.611305 seconds from start
[27-Jun-2017 09:57:22.118779] NOTICE: pid 17750, fpm_children_make(), line 421: [pool www] child 17776 started
[27-Jun-2017 09:57:22.119051] DEBUG: pid 17750, fpm_event_loop(), line 424: event module triggered 1 events
```

```
dpkg -l | grep "php7.0"
ii  libapache2-mod-php7.0                                       7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php7.0-bcmath                                               7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Bcmath module for PHP
ii  php7.0-cli                                                  7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                                               7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        documentation, examples and common module for PHP
ii  php7.0-curl                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        CURL module for PHP
ii  php7.0-fpm                                                  7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.0-gd                                                   7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        GD module for PHP
ii  php7.0-imap                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        IMAP module for PHP
ii  php7.0-intl                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Internationalisation module for PHP
ii  php7.0-json                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        JSON module for PHP
ii  php7.0-ldap                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        LDAP module for PHP
ii  php7.0-mbstring                                             7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                                               7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        libmcrypt module for PHP
ii  php7.0-mysql                                                7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        MySQL module for PHP
ii  php7.0-opcache                                              7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Zend OpCache module for PHP
ii  php7.0-readline                                             7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        readline module for PHP
ii  php7.0-soap                                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        SOAP module for PHP
ii  php7.0-sqlite3                                              7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        SQLite3 module for PHP
ii  php7.0-xml                                                  7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-xmlrpc                                               7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        XMLRPC-EPI module for PHP
ii  php7.0-zip                                                  7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Zip module for PHP
```

**Comment by cheindl** [comment] 2017-06-27 08:09
I just saw, that even the command line php information does not work, too:

```
# php7.0 -i
phpinfo()
PHP Version => 7.0.20-2~ubuntu16.04.1+deb.sury.org+1

System => Linux HOST 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64
Build Date => Jun 14 2017 05:33:01
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php/7.0/cli
Loaded Configuration File => /etc/php/7.0/cli/php.ini
Scan this dir for additional .ini files => /etc/php/7.0/cli/conf.d
Additional .ini files parsed => /etc/php/7.0/cli/conf.d/10-mysqlnd.ini,
/etc/php/7.0/cli/conf.d/10-opcache.ini,
/etc/php/7.0/cli/conf.d/10-pdo.ini,
/etc/php/7.0/cli/conf.d/15-xml.ini,
/etc/php/7.0/cli/conf.d/20-apcu.ini,
/etc/php/7.0/cli/conf.d/20-apcu_bc.ini,
/etc/php/7.0/cli/conf.d/20-bcmath.ini,
/etc/php/7.0/cli/conf.d/20-calendar.ini,
/etc/php/7.0/cli/conf.d/20-ctype.ini,
/etc/php/7.0/cli/conf.d/20-curl.ini,
/etc/php/7.0/cli/conf.d/20-dom.ini,
/etc/php/7.0/cli/conf.d/20-exif.ini,
/etc/php/7.0/cli/conf.d/20-fileinfo.ini,
/etc/php/7.0/cli/conf.d/20-ftp.ini,
/etc/php/7.0/cli/conf.d/20-gd.ini,
/etc/php/7.0/cli/conf.d/20-gettext.ini,
/etc/php/7.0/cli/conf.d/20-gmagick.ini,
/etc/php/7.0/cli/conf.d/20-iconv.ini,
/etc/php/7.0/cli/conf.d/20-igbinary.ini,
/etc/php/7.0/cli/conf.d/20-imagick.ini,
/etc/php/7.0/cli/conf.d/20-imap.ini,
/etc/php/7.0/cli/conf.d/20-intl.ini,
/etc/php/7.0/cli/conf.d/20-json.ini,
/etc/php/7.0/cli/conf.d/20-ldap.ini,
/etc/php/7.0/cli/conf.d/20-mbstring.ini,
/etc/php/7.0/cli/conf.d/20-mcrypt.ini,
/etc/php/7.0/cli/conf.d/20-memcache.ini,
/etc/php/7.0/cli/conf.d/20-mysqli.ini,
/etc/php/7.0/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini,
/etc/php/7.0/cli/conf.d/20-phar.ini,
/etc/php/7.0/cli/conf.d/20-posix.ini,
/etc/php/7.0/cli/conf.d/20-readline.ini,
/etc/php/7.0/cli/conf.d/20-redis.ini,
/etc/php/7.0/cli/conf.d/20-shmop.ini,
/etc/php/7.0/cli/conf.d/20-simplexml.ini,
/etc/php/7.0/cli/conf.d/20-soap.ini,
/etc/php/7.0/cli/conf.d/20-sockets.ini,
/etc/php/7.0/cli/conf.d/20-sqlite3.ini,
/etc/php/7.0/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.0/cli/conf.d/20-sysvsem.ini,
/etc/php/7.0/cli/conf.d/20-sysvshm.ini,
/etc/php/7.0/cli/conf.d/20-tokenizer.ini,
/etc/php/7.0/cli/conf.d/20-wddx.ini,
/etc/php/7.0/cli/conf.d/20-xdebug.ini,
/etc/php/7.0/cli/conf.d/20-xmlreader.ini,
/etc/php/7.0/cli/conf.d/20-xmlrpc.ini,
/etc/php/7.0/cli/conf.d/20-xmlwriter.ini,
/etc/php/7.0/cli/conf.d/20-xsl.ini,
/etc/php/7.0/cli/conf.d/20-zip.ini

PHP API => 20151012
PHP Extension => 20151012
Zend Extension => 320151012
Zend Extension Build => API320151012,NTS
PHP Extension Build => API20151012,NTS
Debug Build => no
Thread Safety => disabled
Zend Signal Handling => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => provided by mbstring
IPv6 Support => enabled
DTrace Support => available, disabled

Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
Registered Stream Filters => zlib.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consumed, dechunk, convert.iconv.*, mcrypt.*, mdecrypt.*

This program makes use of the Zend Scripting Language Engine:
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.20-2~ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans


 _______________________________________________________________________


Configuration

apc

APC Compatibility => 1.0.3
APCu Version => 5.1.7
Build Date => Dec 11 2016 12:09:03

apcu

APCu Support => Disabled
Version => 5.1.8
APCu Debugging => Disabled
MMAP Support => Enabled
MMAP File Mask =>  
Serialization Support => Disabled
Build Date => Jan 23 2017 10:24:53

Directive => Local Value => Master Value
apc.coredump_unmap => Off => Off
apc.enable_cli => Off => Off
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
apc.writable => /tmp => /tmp

bcmath

BCMath support => enabled

Directive => Local Value => Master Value
bcmath.scale => 0 => 0

calendar

Calendar support => enabled

Core

PHP Version => 7.0.20-2~ubuntu16.04.1+deb.sury.org+1

Directive => Local Value => Master Value
allow_url_fopen => On => On
allow_url_include => Off => Off
arg_separator.input => & => &
arg_separator.output => & => &
auto_append_file => no value => no value
auto_globals_jit => On => On
auto_prepend_file => no value => no value
browscap => no value => no value
default_charset => UTF-8 => UTF-8
default_mimetype => text/html => text/html
disable_classes => no value => no value
disable_functions => no value => no value
display_errors => Off => Off
display_startup_errors => Off => Off
doc_root => no value => no value
docref_ext => no value => no value
docref_root => no value => no value
enable_dl => Off => Off
enable_post_data_reading => On => On
error_append_string => no value => no value
error_log => no value => no value
error_prepend_string => no value => no value
error_reporting => 22527 => 22527
exit_on_timeout => Off => Off
expose_php => On => On
extension_dir => /usr/lib/php/20151012 => /usr/lib/php/20151012
file_uploads => On => On
highlight.comment => <font style="color: #FF8000">#FF8000</font> => <font style="color: #FF8000">#FF8000</font>
highlight.default => <font style="color: #0000BB">#0000BB</font> => <font style="color: #0000BB">#0000BB</font>
highlight.html => <font style="color: #000000">#000000</font> => <font style="color: #000000">#000000</font>
highlight.keyword => <font style="color: #007700">#007700</font> => <font style="color: #007700">#007700</font>
highlight.string => <font style="color: #DD0000">#DD0000</font> => <font style="color: #DD0000">#DD0000</font>
html_errors => Off => Off
ignore_repeated_errors => Off => Off
ignore_repeated_source => Off => Off
ignore_user_abort => Off => Off
implicit_flush => On => On
include_path => .:/usr/share/php => .:/usr/share/php
input_encoding => no value => no value
internal_encoding => no value => no value
log_errors => On => On
log_errors_max_len => 1024 => 1024
mail.add_x_header => On => On
mail.force_extra_parameters => no value => no value
mail.log => no value => no value
max_execution_time => 0 => 0
max_file_uploads => 20 => 20
max_input_nesting_level => 64 => 64
max_input_time => -1 => -1
max_input_vars => 1000 => 1000
memory_limit => -1 => -1
open_basedir => no value => no value
output_buffering => 0 => 0
output_encoding => no value => no value
output_handler => no value => no value
post_max_size => 8M => 8M
precision => 14 => 14
realpath_cache_size => 4096K => 4096K
realpath_cache_ttl => 120 => 120
register_argc_argv => On => On
report_memleaks => On => On
report_zend_debug => Off => Off
request_order => GP => GP
sendmail_from => no value => no value
sendmail_path => /usr/sbin/sendmail -t -i  => /usr/sbin/sendmail -t -i 
serialize_precision => 17 => 17
short_open_tag => Off => Off
SMTP => localhost => localhost
smtp_port => 25 => 25
sql.safe_mode => Off => Off
sys_temp_dir => no value => no value
track_errors => Off => Off
unserialize_callback_func => no value => no value
upload_max_filesize => 2M => 2M
upload_tmp_dir => no value => no value
user_dir => no value => no value
user_ini.cache_ttl => 300 => 300
user_ini.filename => .user.ini => .user.ini
variables_order => GPCS => GPCS
xmlrpc_error_number => 0 => 0
xmlrpc_errors => Off => Off
zend.assertions => -1 => -1
zend.detect_unicode => On => On
zend.enable_gc => On => On
zend.multibyte => Off => Off
zend.script_encoding => no value => no value

ctype

ctype functions => enabled

curl

cURL support => enabled
cURL Information => 7.47.0
Age => 3
Features
AsynchDNS => Yes
CharConv => No
Debug => No
GSS-Negotiate => No
IDN => Yes
IPv6 => Yes
krb4 => No
Largefile => Yes
libz => Yes
NTLM => Yes
NTLMWB => Yes
SPNEGO => Yes
SSL => Yes
SSPI => No
TLS-SRP => Yes
HTTP2 => No
GSSAPI => Yes
KERBEROS5 => Yes
UNIX_SOCKETS => Yes
PSL => No
Protocols => dict, file, ftp, ftps, gopher, http, https, imap, imaps, ldap, ldaps, pop3, pop3s, rtmp, rtsp, smb, smbs, smtp, smtps, telnet, tftp
Host => x86_64-pc-linux-gnu
SSL Version => OpenSSL/1.0.2k
ZLib Version => 1.2.8

date

date/time support => enabled
"Olson" Timezone Database Version => 0.system
Timezone Database => internal
Default timezone => Europe/Berlin

Directive => Local Value => Master Value
date.default_latitude => 31.7667 => 31.7667
date.default_longitude => 35.2333 => 35.2333
date.sunrise_zenith => 90.583333 => 90.583333
date.sunset_zenith => 90.583333 => 90.583333
date.timezone => no value => no value

dom

DOM/XML => enabled
DOM/XML API Version => 20031129
libxml Version => 2.9.4
HTML Support => enabled
XPath Support => enabled
XPointer Support => enabled
Schema Support => enabled
RelaxNG Support => enabled

exif

EXIF Support => enabled
EXIF Version => 1.4 $Id: 8bdc0c8f27c2c9dd1f7551f1f9fe3ab57a06a4b1 $
Supported EXIF Version => 0220
Supported filetypes => JPEG,TIFF

Directive => Local Value => Master Value
exif.decode_jis_intel => JIS => JIS
exif.decode_jis_motorola => JIS => JIS
exif.decode_unicode_intel => UCS-2LE => UCS-2LE
exif.decode_unicode_motorola => UCS-2BE => UCS-2BE
exif.encode_jis => no value => no value
exif.encode_unicode => ISO-8859-15 => ISO-8859-15

fileinfo

fileinfo support => enabled
version => 1.0.5
libmagic => 522

filter

Input Validation and Filtering => enabled
Revision => $Id: 28fcca4bfda9c9907588a64d245b49cb398249d8 $

Directive => Local Value => Master Value
filter.default => unsafe_raw => unsafe_raw
filter.default_flags => no value => no value

ftp

FTP support => enabled
FTPS support => enabled

gd

GD Support => enabled
GD headers Version => 2.2.3
GD library Version => 2.2.3
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.6.1
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
libJPEG Version => 8
PNG Support => enabled
libPNG Version => 1.2.54
WBMP Support => enabled
XPM Support => enabled
libXpm Version => 30411
XBM Support => enabled
WebP Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 0 => 0

gettext

GetText Support => enabled

gmagick

gmagick module => enabled
gmagick version => 2.0.4RC1
GraphicsMagick version => GraphicsMagick 1.3.25 2016-09-05 Q16 http://www.GraphicsMagick.org/

hash

hash support => enabled
Hashing Engines => md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b fnv132 fnv1a32 fnv164 fnv1a64 joaat haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5 

MHASH support => Enabled
MHASH API Version => Emulated Support

iconv

iconv support => enabled
iconv implementation => glibc
iconv library version => 2.23

Directive => Local Value => Master Value
iconv.input_encoding => no value => no value
iconv.internal_encoding => no value => no value
iconv.output_encoding => no value => no value

igbinary

igbinary support => enabled
igbinary version => 2.0.1
igbinary APCU serializer ABI => 0
igbinary session support => yes

Directive => Local Value => Master Value
igbinary.compact_strings => On => On

imagick
*** Error in `php7.0': free(): invalid next size (fast): 0x00005617bde8ff10 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fad645fb7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fad6460437a]
/lib/x86_64-linux-gnu/libc.so.6(+0x82d52)[0x7fad64606d52]
/lib/x86_64-linux-gnu/libc.so.6(posix_memalign+0x11d)[0x7fad6460b71d]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(AllocateSemaphoreInfo+0x28)[0x7fad55fe5238]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(NewLinkedList+0x60)[0x7fad55f65670]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(+0xe94f2)[0x7fad55f434f2]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(AcquireExceptionInfo+0x20)[0x7fad55f43800]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(IsEventLogging+0x2d)[0x7fad55f7e9ad]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(LogMagickEventList+0x24)[0x7fad55f7eba4]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(LogMagickEvent+0x85)[0x7fad55f7ec75]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(+0x12bc2a)[0x7fad55f85c2a]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(+0x12c1a6)[0x7fad55f861a6]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(OpenModules+0x69)[0x7fad55f86fe9]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(GetMagickInfo+0x1a8)[0x7fad55f81938]
/usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2(GetMagickList+0x68)[0x7fad55f820c8]
/usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2(MagickQueryFormats+0x20)[0x7fad563b9f30]
/usr/lib/php/20151012/imagick.so(zm_info_imagick+0x3d)[0x7fad56677dbd]
php7.0(+0x1bdf43)[0x5617bb839f43]
php7.0(zend_hash_apply+0x7c)[0x5617bb8f105c]
php7.0(php_print_info+0x8cf)[0x5617bb83a9cf]
php7.0(+0x2f8fef)[0x5617bb974fef]
php7.0(main+0x474)[0x5617bb760764]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fad645a4830]
php7.0(_start+0x29)[0x5617bb7608a9]
======= Memory map: ========
5617bb67c000-5617bba2d000 r-xp 00000000 08:18 786680                     /usr/bin/php7.0
5617bbc2d000-5617bbca6000 r--p 003b1000 08:18 786680                     /usr/bin/php7.0
5617bbca6000-5617bbcb6000 rw-p 0042a000 08:18 786680                     /usr/bin/php7.0
5617bbcb6000-5617bbcd2000 rw-p 00000000 00:00 0 
5617bdadb000-5617bde97000 rw-p 00000000 00:00 0                          [heap]
7fad44000000-7fad44021000 rw-p 00000000 00:00 0 
7fad44021000-7fad48000000 ---p 00000000 00:00 0 
7fad4a9bd000-7fad4a9c3000 r-xp 00000000 08:18 1726018                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/gif.so
7fad4a9c3000-7fad4abc3000 ---p 00006000 08:18 1726018                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/gif.so
7fad4abc3000-7fad4abc4000 r--p 00006000 08:18 1726018                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/gif.so
7fad4abc4000-7fad4abc5000 rw-p 00007000 08:18 1726018                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/gif.so
7fad4abc5000-7fad4abc9000 r-xp 00000000 08:18 1725975                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fits.so
7fad4abc9000-7fad4adc9000 ---p 00004000 08:18 1725975                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fits.so
7fad4adc9000-7fad4adca000 r--p 00004000 08:18 1725975                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fits.so
7fad4adca000-7fad4adcb000 rw-p 00005000 08:18 1725975                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fits.so
7fad4adcb000-7fad4adcd000 r-xp 00000000 08:18 1726052                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fd.so
7fad4adcd000-7fad4afcc000 ---p 00002000 08:18 1726052                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fd.so
7fad4afcc000-7fad4afcd000 r--p 00001000 08:18 1726052                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fd.so
7fad4afcd000-7fad4afce000 rw-p 00002000 08:18 1726052                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fd.so
7fad4afce000-7fad4afd0000 r-xp 00000000 08:18 1726136                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fax.so
7fad4afd0000-7fad4b1cf000 ---p 00002000 08:18 1726136                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fax.so
7fad4b1cf000-7fad4b1d0000 r--p 00001000 08:18 1726136                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fax.so
7fad4b1d0000-7fad4b1d1000 rw-p 00002000 08:18 1726136                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/fax.so
7fad4b1d1000-7fad4b1d6000 r-xp 00000000 08:18 813721                     /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12.0.0
7fad4b1d6000-7fad4b3d6000 ---p 00005000 08:18 813721                     /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12.0.0
7fad4b3d6000-7fad4b3d7000 r--p 00005000 08:18 813721                     /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12.0.0
7fad4b3d7000-7fad4b3d8000 rw-p 00006000 08:18 813721                     /usr/lib/x86_64-linux-gnu/libIlmThread-2_2.so.12.0.0
7fad4b3d8000-7fad4b3f3000 r-xp 00000000 08:18 813720                     /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12.0.0
7fad4b3f3000-7fad4b5f2000 ---p 0001b000 08:18 813720                     /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12.0.0
7fad4b5f2000-7fad4b5f5000 r--p 0001a000 08:18 813720                     /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12.0.0
7fad4b5f5000-7fad4b5f6000 rw-p 0001d000 08:18 813720                     /usr/lib/x86_64-linux-gnu/libIex-2_2.so.12.0.0
7fad4b5f6000-7fad4b638000 r-xp 00000000 08:18 813717                     /usr/lib/x86_64-linux-gnu/libHalf.so.12.0.0
7fad4b638000-7fad4b837000 ---p 00042000 08:18 813717                     /usr/lib/x86_64-linux-gnu/libHalf.so.12.0.0
7fad4b837000-7fad4b838000 r--p 00041000 08:18 813717                     /usr/lib/x86_64-linux-gnu/libHalf.so.12.0.0
7fad4b838000-7fad4b839000 rw-p 00042000 08:18 813717                     /usr/lib/x86_64-linux-gnu/libHalf.so.12.0.0
7fad4b839000-7fad4ba03000 r-xp 00000000 08:18 816792                     /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
7fad4ba03000-7fad4bc02000 ---p 001ca000 08:18 816792                     /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
7fad4bc02000-7fad4bc05000 r--p 001c9000 08:18 816792                     /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
7fad4bc05000-7fad4bd06000 rw-p 001cc000 08:18 816792                     /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0
7fad4bd06000-7fad4bd07000 rw-p 00000000 00:00 0 
7fad4bd07000-7fad4bd0a000 r-xp 00000000 08:18 1716858                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/exr.so
7fad4bd0a000-7fad4bf09000 ---p 00003000 08:18 1716858                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/exr.so
7fad4bf09000-7fad4bf0a000 r--p 00002000 08:18 1716858                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/exr.so
7fad4bf0a000-7fad4bf0b000 rw-p 00003000 08:18 1716858                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/exr.so
7fad4bf0b000-7fad4bf0e000 r-xp 00000000 08:18 1726119                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/ept.so
7fad4bf0e000-7fad4c10d000 ---p 00003000 08:18 1726119                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/ept.so
7fad4c10d000-7fad4c10e000 r--p 00002000 08:18 1726119                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/ept.so
7fad4c10e000-7fad4c10f000 rw-p 00003000 08:18 1726119                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/ept.so
7fad4c10f000-7fad4c116000 r-xp 00000000 08:18 1726098                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dpx.so
7fad4c116000-7fad4c315000 ---p 00007000 08:18 1726098                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dpx.so
7fad4c315000-7fad4c316000 r--p 00006000 08:18 1726098                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dpx.so
7fad4c316000-7fad4c317000 rw-p 00007000 08:18 1726098                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dpx.so
7fad4c317000-7fad4c318000 r-xp 00000000 08:18 1716864                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dot.so
7fad4c318000-7fad4c517000 ---p 00001000 08:18 1716864                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dot.so
7fad4c517000-7fad4c518000 r--p 00000000 08:18 1716864                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dot.so
7fad4c518000-7fad4c519000 rw-p 00001000 08:18 1716864                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dot.so
7fad4c519000-7fad4c51c000 r-xp 00000000 08:18 1726096                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dng.so
7fad4c51c000-7fad4c71b000 ---p 00003000 08:18 1726096                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dng.so
7fad4c71b000-7fad4c71c000 r--p 00002000 08:18 1726096                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dng.so
7fad4c71c000-7fad4c71d000 rw-p 00003000 08:18 1726096                    /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/dng.soMagick: abort due to signal 6 (SIGABRT) "Abort"...
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by cheindl** [comment] 2017-06-27 08:10
Maybe a duplicate of #622.

**Comment by oerdnj** [comment] 2017-06-29 11:16
It is duplicate of #622.

**Closed by oerdnj** 2017-06-29 11:16 UTC
