### ISSUE TITLE
add-repository instructions fail on ubunutu 15.10 in Dec 2015

### ISSUE THREAD

**Issue by iwelch** [oerdnj/deb.sury.org#147] opened 2015-12-04 18:05 UTC
same issue with php or php-7.0.  pretty vanilla ubuntu 15.10 system.

# sudo add-apt-repository ppa:ondrej/php-7.0
 PPA with PHP 7.0.  If you want a co-installable version of PHP, please use:

ppa:ondrej/php

where PHP 7.0 and PHP 5.6 co-exists.

You can get more information about the packages at https://deb.sury.org

For PHP 5.6 use: ppa:ondrej/php5-5.6
For PHP 5.5 use: ppa:ondrej/php5
For PHP 5.4 use: ppa:ondrej/php5-oldstable

BUGS&FEATURES: This PPA now has a issue tracker: https://deb.sury.org/pages/bugreporting.html

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating: https://deb.sury.org/pages/donate.html
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmp1tp4ikaz/secring.gpg' created
gpg: keyring `/tmp/tmp1tp4ikaz/pubring.gpg' created
gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp1tp4ikaz/trustdb.gpg: trustdb created
gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 385, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 262, in add_ppa_signing_key
    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 211, in _verify_fingerprint
    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 203, in _get_fingerprints
    output = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
    output, unused_err = process.communicate(inputdata, timeout=timeout)
  File "/usr/lib/python3.4/subprocess.py", line 949, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 92: ordinal not in range(128)

**Comment by Enviii** [comment] 2015-12-04 19:27
I had the same issue on 14.04. Problem is it doesn't recognize "gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�" imported" because of the character. 

I followed the instructions here to add UTF-8 and it worked: http://serverfault.com/a/728001

**Comment by oerdnj** [comment] 2015-12-04 20:01
Set the locale to anything with utf8

On 4 Dec 2015, ivo welch <notifications@github.com> wrote:
>
>same issue with php or php-7.0.  pretty vanilla ubuntu 15.10 system.
>
># sudo add-apt-repository ppa:ondrej/php-7.0
>PPA with PHP 7.0.  If you want a co-installable version of PHP, please
>use:
>
>ppa:ondrej/php
>
>where PHP 7.0 and PHP 5.6 co-exists.
>
>You can get more information about the packages at https://deb.sury.org
>
>For PHP 5.6 use: ppa:ondrej/php5-5.6
>For PHP 5.5 use: ppa:ondrej/php5
>For PHP 5.4 use: ppa:ondrej/php5-oldstable
>
>BUGS&FEATURES: This PPA now has a issue tracker:
>https://deb.sury.org/pages/bugreporting.html
>
>PLEASE READ: If you like my work and want to give me a little
>motivation, please consider donating:
>https://deb.sury.org/pages/donate.html
> More info: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0
>Press [ENTER] to continue or ctrl-c to cancel adding it
>
>gpg: keyring `/tmp/tmp1tp4ikaz/secring.gpg' created
>gpg: keyring `/tmp/tmp1tp4ikaz/pubring.gpg' created
>gpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com
>gpg: /tmp/tmp1tp4ikaz/trustdb.gpg: trustdb created
>gpg: key E5267A6C: public key "Launchpad PPA for Ond\xc5\x99ej Sur�"
>imported
>gpg: Total number processed: 1
>gpg:               imported: 1  (RSA: 1)
>Exception in thread Thread-1:
>Traceback (most recent call last):
>  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
>    self.run()
>  File "/usr/lib/python3.4/threading.py", line 868, in run
>    self._target(*self._args, **self._kwargs)
>File
>"/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py",
>line 688, in addkey_func
>    func(**kwargs)
>File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
>385, in add_key
>    return apsk.add_ppa_signing_key()
>File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
>262, in add_ppa_signing_key
>    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):
>File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
>211, in _verify_fingerprint
>    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)
>File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line
>203, in _get_fingerprints
>    output = subprocess.check_output(cmd, universal_newlines=True)
>  File "/usr/lib/python3.4/subprocess.py", line 609, in check_output
>   output, unused_err = process.communicate(inputdata, timeout=timeout)
>  File "/usr/lib/python3.4/subprocess.py", line 949, in communicate
>    stdout = _eintr_retry_call(self.stdout.read)
>File "/usr/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
>    return func(*args)
>  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
>    return codecs.ascii_decode(input, self.errors)[0]
>UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position
>92: ordinal not in range(128)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/147

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by iwelch** [comment] 2015-12-04 21:13
suggestion: add this info to https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0, "Read about installing".  thanks ondrej.  /iaw

**Comment by oerdnj** [comment] 2015-12-07 12:40
This is duplicate of #56

**Closed by oerdnj** 2015-12-07 12:40 UTC
