### ISSUE TITLE
Can't update repos on debian sid (php)

### ISSUE THREAD

**Issue by sergo44** [oerdnj/deb.sury.org#778] opened 2018-01-09 03:52 UTC
Hello!

I am using deb.sury.org in debian sid for php 5.6 both 7.1 version.

root@debian:~# cat /etc/apt/sources.list.d/deb.sury.org.list
deb https://packages.sury.org/php/ stretch main

Now i can;t update repo with error:

E: Repository 'https://packages.sury.org/php stretch InRelease' changed its 'Origin' value from '' to 'deb.sury.org'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.

**Comment by todeveni** [comment] 2018-01-09 05:05
Duplicate of #765

**Comment by oerdnj** [comment] 2018-01-09 18:50
It gives explicit instructions in the error message:
> N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Is there a reason you haven't followed them?

**Closed by oerdnj** 2018-01-09 18:50 UTC

**Comment by sergo44** [comment] 2018-02-02 03:29
oerdnj, I don't want allow insecure repos. Error message follow me to man https://manpages.debian.org/stretch/apt/apt-secure.8.en.html (allow insecure repos).

In all mans (apt-get, apt, apt-cache) NO information about option --allow-releaseinfo-change (man issue or hidden feature: ) )

https://manpages.debian.org/stretch/apt/apt-get.8.en.html
https://manpages.debian.org/stretch/apt/apt-secure.8.en.html
https://manpages.debian.org/stretch/apt/apt.8.en.html
