### ISSUE TITLE
php7.3-fpm no longer supports sysvinit and removes if non systemd

### ISSUE THREAD

**Issue by retry** [oerdnj/deb.sury.org#1347] opened 2020-02-21 13:08 UTC
```
This is a problem.  No other package in a debian headless system is forcing systemd like this.

# apt-get -s dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  dbus libcryptsetup12 systemd
The following packages will be upgraded:
  php7.3-cli php7.3-common php7.3-curl php7.3-fpm php7.3-gmp php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache
  php7.3-readline php7.3-xml php7.3-zip
12 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Inst libcryptsetup12 (2:2.1.0-5+deb10u2 Debian:10.3/stable [amd64])
Inst systemd (241-7~deb10u3 Debian:10.3/stable [amd64])
Inst dbus (1.12.16-1 Debian:10.3/stable [amd64])
Inst php7.3-zip [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-xml [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-readline [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-opcache [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-mysql [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-mbstring [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-json [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-gmp [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-fpm [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-curl [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-cli [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-common [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf libcryptsetup12 (2:2.1.0-5+deb10u2 Debian:10.3/stable [amd64])
Conf systemd (241-7~deb10u3 Debian:10.3/stable [amd64])
Conf dbus (1.12.16-1 Debian:10.3/stable [amd64])
Conf php7.3-zip (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-xml (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-readline (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-opcache (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-mysql (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-mbstring (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-json (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-gmp (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-fpm (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-curl (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-cli (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-common (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])

With systemd pinned to not install...

# apt-get -s dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be REMOVED:
  php7.3-fpm
The following packages will be upgraded:
  php7.3-cli php7.3-common php7.3-curl php7.3-gmp php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache
  php7.3-readline php7.3-xml php7.3-zip
11 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
Remv php7.3-fpm [7.3.14-5+0~20200202.52+debian10~1.gbpa71879]
Inst php7.3-zip [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-xml [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-readline [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-opcache [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-mysql [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-mbstring [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-json [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-gmp [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-curl [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-cli [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64]) []
Inst php7.3-common [7.3.14-5+0~20200202.52+debian10~1.gbpa71879] (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-zip (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-xml (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-readline (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-opcache (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-mysql (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-mbstring (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-json (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-gmp (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-curl (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-cli (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])
Conf php7.3-common (7.3.15-1+0~20200220.53+debian10~1.gbp931d08 packages.sury.org [amd64])

```

**Comment by miniBill** [comment] 2020-02-21 13:14
Duplicate of #1343

**Comment by retry** [comment] 2020-02-21 13:20
It's not a duplicate.  I use debian buster, not devuan.  I don't see why all of a sudden systemd is a forced requirement instead of maintaining a simple 200 line init script for php7.3-fpm .  Again I am using debian buster and NO OTHER PACKAGE FORCES SYSTEMD.

**Comment by oerdnj** [comment] 2020-02-21 13:22
Yes, yelling will get you what you want.

**Closed by oerdnj** 2020-02-21 13:22 UTC

**Comment by retry** [comment] 2020-02-21 13:24
Emphasis to the point that you stand alone in this forced change, and out of the blue I might add.

**Comment by xwni** [comment] 2020-02-21 13:43
This change was not necessary, please revert it.    @oerdnj Your attitude is disgraceful.  This is your change, your mistake, a bad/breaking change in your package, and you should revert it. 

I do appreciate your attention to php versions for older distros, but  Systemd is much too invasive. 

It's much more than an init system, it's a cancer with fingers all over the linux system.   It had no business being adopted, particularly in debian variants.   

Currently trying to rebuild a version of your package without this nonsense change.

**Comment by miniBill** [comment] 2020-02-21 13:49
@xwni and @retry : you are obviously free to fork this repository and do as you please with the code.
Surý is maintaining and publishing this repository out of his **kindness**, and you are entitled to absolutely nothing.
I'm a Devuan user, think systemd is a very bad implementation of some good ideas and it is vastly overreaching its purpose, and I am personally affected by this issue.
Still, I don't start yelling at voluteers, judging attitudes as _"disgraceful"_ or other such nonsense.

Devuan forked off because the people who maintain it feel that their time is best spent on maintaining a fork rather than arguing against inclusion of systemd in Debian, and are personally investing their resources to make it happen.
What are you investing in this, apart from insulting someone who is offering for free something valuable?

**Comment by oerdnj** [comment] 2020-02-21 14:04
I am not going to maintain a `systemd-tmpfiles` shim on my own. If there’s an alternative package that does provide `systemd-tmpfiles` compatible interface, I can add it as alternative to `systemd` package. The init.d script is still available, I am just not going to add more code to support every useful systemd feature just to appease people hating systemd. Just installing `systemd` package on the system has no effect as it does not replace `/sbin/init` and it makes the tools from `systemd` suite available to packages. This does not switch your `/sbin/init` to systemd not it does start any extra services. And I don’t believe extra 14MB makes a difference for systems with web server, PHP and usually a database.

If I started pulling any other package (day `openssl`), nobody would even notice. This makes it a non-technical issue.

If you want to go extra length because of your beliefs, it whole be you who does the extra work. Using `equivs` to create a dummy `systemd` package + backported `opentmpfiles` with extra symlink to `systemd-tmpfiles` should do the trick.

**Comment by oerdnj** [comment] 2020-02-21 14:08
As of “out of the blue” - Devuan was never supported and given the recent Debian GR on init systems result, this is perfectly reasonable thing to do.

**Comment by retry** [comment] 2020-02-21 14:14
I have already said twice that I am not using Devuan.  I am using Debian Buster without systemd by selecting sysvinit-core.

"Just installing systemd package on the system has no effect as it does not replace /sbin/init and it makes the tools from systemd suite available to packages."

This is incorrect.  Look again at my apt-get -s dist-upgrade.  php-fpm is forcing sysvinit-core to be removed.

`
Inst libcryptsetup12 (2:2.1.0-5+deb10u2 Debian:10.3/stable [amd64])
Inst systemd (241-7~deb10u3 Debian:10.3/stable [amd64])
Remv sysvinit-core [2.93-8] [init:amd64 ]
Conf libcryptsetup12 (2:2.1.0-5+deb10u2 Debian:10.3/stable [amd64]) [init:amd64 ]
Conf systemd (241-7~deb10u3 Debian:10.3/stable [amd64]) [init:amd64 ]
Inst systemd-sysv (241-7~deb10u3 Debian:10.3/stable [amd64])
Inst dbus (1.12.16-1 Debian:10.3/stable [amd64])
Inst libnss-systemd (241-7~deb10u3 Debian:10.3/stable [amd64])
Inst libpam-systemd (241-7~deb10u3 Debian:10.3/stable [amd64])
`

**Comment by oerdnj** [comment] 2020-02-21 14:22
Then you are doing it wrong, `systemd-sysv` is not required and `systemd` and `sysvinit-core` can coexist just fine:
```
root@himiko:~# apt install sysvinit-core systemd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
systemd is already the newest version (241-7~deb10u3).
The following additional packages will be installed:
  initscripts insserv startpar sysv-rc
Suggested packages:
  bootchart2 bootlogd
The following packages will be REMOVED:
  libpam-systemd systemd-sysv
The following NEW packages will be installed:
  initscripts insserv startpar sysv-rc sysvinit-core
0 upgraded, 5 newly installed, 2 to remove and 0 not upgraded.
Need to get 398 kB of archives.
After this operation, 292 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

Confirmed both on Debian stretch (9) and buster (10).

**Comment by retry** [comment] 2020-02-21 14:32
because you're switching a systemd install to a sysvinit-core.  I am using a sysvinit-core system that was then being overridden by systemd and having sysvinit-core removed .  Not the same thing.  Anybody running a sysvinit based system just doing a routine upgrade will find it trying to force systemd init onto their system.

**Comment by retry** [comment] 2020-02-21 14:34
Will the official builds for buster do this too?

**Comment by oerdnj** [comment] 2020-02-21 14:37
It is the same thing. If you properly (apt) pin `systemd-sysv` to not install, it should not happen.

**Comment by oerdnj** [comment] 2020-02-21 17:16
In Debian buster chroot with `sysvinit-core` installed:

```
# apt policy sysvinit-core
sysvinit-core:
  Installed: 2.93-8
  Candidate: 2.93-8
  Version table:
 *** 2.93-8 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

with `--no-install-recommends` via:
```
# cat /etc/apt/apt.conf.d/99mk-sbuild-no-recommends
// disable install recommends
APT::Install-Recommends "0";
```

it does not uninstall `sysvinit-core`
```
# apt install systemd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdevmapper1.02.1 libidn11 libip4tc0 libjson-c3 libkmod2 libssl1.1
Suggested packages:
  systemd-container policykit-1
Recommended packages:
  libpam-systemd dbus
The following NEW packages will be installed:
  dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdevmapper1.02.1 libidn11 libip4tc0 libjson-c3 libkmod2 libssl1.1 systemd
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 5852 kB of archives.
After this operation, 20.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

vs installing recommended packages does install `systemd-sysv`:
```
# apt install --install-recommends systemd
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  initscripts insserv startpar sysv-rc
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  dbus dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdbus-1-3 libdevmapper1.02.1 libexpat1 libidn11 libip4tc0 libjson-c3 libkmod2 libnss-systemd libpam-systemd
  libssl1.1 systemd-sysv
Suggested packages:
  default-dbus-session-bus | dbus-session-bus systemd-container policykit-1
The following packages will be REMOVED:
  sysvinit-core
The following NEW packages will be installed:
  dbus dmsetup libapparmor1 libargon2-1 libcap2 libcryptsetup12 libdbus-1-3 libdevmapper1.02.1 libexpat1 libidn11 libip4tc0 libjson-c3 libkmod2 libnss-systemd libpam-systemd
  libssl1.1 systemd systemd-sysv
0 upgraded, 18 newly installed, 1 to remove and 0 not upgraded.
Need to get 6917 kB of archives.
After this operation, 22.4 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

So simply disabling installing recommended packages solves the issue on Debian.

**Comment by tdrnetworks** [comment] 2020-02-26 02:00
A kind soul has reverted the changes for PHP v5.6 right through to 7.4.3:

http://dev1galaxy.org/viewtopic.php?id=3331

**Comment by oktayaa** [comment] 2020-02-28 15:31
```
#Package: systemd
#Pin: release *
#Pin-Priority: -1


#Package: *systemd*
#Pin: release *
#Pin-Priority: -1

Package: systemd-sysv
Pin: release *
Pin-Priority: -1
```

This worked for me on a stretch box where systemd was gutted after initial install.  (Commented out lines are the original to pin all systemd related things. Might be overkill. I followed a guide years ago)

```
root@virt01:/etc/apt/preferences.d# aptitude install systemd
The following NEW packages will be installed:
  cgmanager{a} libpam-systemd{a} libseccomp2{a} systemd systemd-shim{a}
The following packages will be upgraded:
  libsystemd0
1 packages upgraded, 5 newly installed, 0 to remove and 35 not upgraded.
Need to get 3,085 kB of archives. After unpacking 11.1 MB will be used.
Do you want to continue? [Y/n/?]
```

It does not introduce a ton of packages as you can see above. All in all this is more than sufficient for me. I am thinking of pinning systemd back now. (Uncommenting the lines in policy)

Thanks for the pointers @oerdnj .

Also I recommend other affected parties to try to be a bit positive. This guy isn't trying to cause us pain.

**Comment by oerdnj** [comment] 2020-02-28 17:05
Thanks @oktayaa ! Perhaps you can turn this into the wiki here? You should be able to edit the FAQ page freely.

**Comment by szepeviktor** [comment] 2020-03-01 13:25
> If you want to go extra length because of your beliefs, it whole be you who does the extra work. Using `equivs` to create a dummy `systemd` package + backported `opentmpfiles` with extra symlink to `systemd-tmpfiles` should do the trick.

Here is my first try on this. You need equivs 2.1+ for `Links:`

```debian
Source: systemd-tmpfiles
Section: admin
Priority: important
Homepage: https://packages.debian.org/bullseye/opentmpfiles
Standards-Version: 3.9.2

Package: systemd-tmpfiles
Version: 244.3-1
Maintainer: Viktor Szépe <viktor@szepe.net>
Depends: opentmpfiles
Provides: systemd
Conflicts: systemd
Architecture: amd64
Links: /bin/opentmpfiles-tmpfiles /bin/systemd-tmpfiles
Description: Provides systemd-tmpfiles command symlinked to opentmpfiles-tmpfiles
```

opentmpfiles is a Bash script so it does not need to be rebuilt.

**Comment by oerdnj** [comment] 2020-03-01 15:59
I can change `systemd` to `systemd | systemd-tmpfiles` if that helps.

**Comment by oktayaa** [comment] 2020-03-02 18:12
Note: After installing systemd, a systemd-logind process becomes active.
It can be disabled by:
  systemctl mask systemd-logind.service
  pam-auth-update

(Remember to kill the active process too)
