### ISSUE TITLE
Version-agnostic way to access socket

### ISSUE THREAD

**Issue by OlafvdSpek** [oerdnj/deb.sury.org#1080] opened 2019-02-07 12:05 UTC
> Referencing the php version in a conffile feels like whack-a-mole. Is there really no better way?

> My remark about encoding the php version is not a show stopper, but maybe it still is worth filing a bug against php-fpm asking for a better way to integrate (after buster)?

It'd be nice not to have to include the version number in such conf files, though having the option to do so can be nice.

https://salsa.debian.org/debian/lighttpd/merge_requests/11#note_63976

**Comment by oerdnj** [comment] 2019-02-08 12:42
I am open to suggestions, ideas or MRs :-).

**Comment by gstrauss** [comment] 2019-02-11 17:10
What do you think of a script that could ship with php-fpm which can be run to find a primary php-fpm service that is enabled in systemd, wait for it to be active in systemd, and then return the path to the socket?  Could it have a flag to only provide an active unix socket or TCP socket?

The shortcoming of adding a service dependency on a specific php7.x-fpm.service version is, again, hard-coding the version.  Upgrading major releases (which bump PHP version) or installing a new PHP version from backports can result in broken configurations for services that were configured to use the version-specific PHP socket.

Another option, of course, would be for the default installation config to use a well-named socket path rather than a versioned socket path.  Modifying the config would be required for those that want to run multiple simultaneous side-by-side installations of different php-fpm versions.

**Comment by oerdnj** [comment] 2019-02-12 17:13
The problem is that we need only one FPM version to handle the “set” of configuration files. The alternatives system would be ideal because it’s already used, but I haven’t been able to figure out how to use it here.

**Comment by oerdnj** [comment] 2019-02-12 17:16
JFTR the version-named sockets allow gradual upgrades from one PHP version to another, so perhaps we will need a script similar to the one in postgresql packages that would “upgrade” the FPM configurations to new “default” version.

**Comment by gstrauss** [comment] 2019-02-12 20:30
You could use something as simple as a symlink.
When listening to a socket, say `/run/php/php7.3-fpm.sock`,
a symlink could be created/repointed from `/run/php/php-fpm.sock -> php7.3-fpm.sock`

The point is that it is not polite or user-friendly for a simple, default configuration to require an end-user to go manually update configuration files of **other** daemons in order to point to a different versioned filename.

**Comment by oerdnj** [comment] 2019-02-12 20:36
Well, if you need simple configuration you should install libapache2-mod-php.
But the symlink could work, but still you would have to migrate all the *.conf files for non-default pools.

**Comment by WindfallProphet** [comment] 2020-01-29 21:48
If you run php-fpm with the `--fpm-config ` parameter and direct it to a version-agnostic location (i.e. /etc/php/php-fpm.conf), I think that should work. The only issue is getting the right version of php-fpm, but that can be symlinked from the package, correct? 

Just put this in a systemd service file and you should be set.

**Comment by oerdnj** [comment] 2020-02-01 16:11
I have good news and bad news :-). The good news is that I finally started to implement this, the bad news is that I broke FPM packages in the process: https://github.com/oerdnj/deb.sury.org/issues/1327

**Comment by oerdnj** [comment] 2020-02-01 18:26
OK, so could you try installing following packages from [php-qa](https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages) repository (once the packages are built):

* php5.6 - 5.6.40-20
* php7.0 - 7.0.33-19
* php7.1 - 7.1.33-8
* php7.2 - 7.2.27-5
* php7.3 - 7.3.14-5
* php7.4 - 7.4.2-5

Those should register and unregister the socket from the systemd unit (`ExecStartPost` and `ExecStopPost`). It might not be ideal as the highest running version will always override the symlink, but it should at least provide a stable socket.

Be aware that unless you also copy the pools from one version to another things will break.

I don't have a running Ubuntu server anywhere, so I would appreciate if somebody could test this. (I only did a manual test on my Debian server using the two extra lines to copy it to systemd unit.)

**Comment by oerdnj** [comment] 2020-02-02 08:02
And I am now building the packages for Debian, so closing this bug.  If you have suggestions how to improve the mechanism, please open a separate issue.

**Closed by oerdnj** 2020-02-02 08:02 UTC

**Comment by oerdnj** [comment] 2020-02-02 17:52
```
lrwxrwxrwx 1 root     root     30 Feb  2 18:01 php-fpm.sock -> /etc/alternatives/php-fpm.sock
```

```
# update-alternatives --list php-fpm.sock
/run/php/php5.6-fpm.sock
/run/php/php7.4-fpm.sock
```

The only downside is that the configured setting doesn't survive the restarts, because the alternative is added and removed on restart. And if you stop one FPM, it gets picked by a different version. But hey, we can't have unicorns AND rainbows, right? :)

**Comment by gstrauss** [comment] 2020-02-09 22:11
@oerdnj : thank you for the effort you put in to make this option available.
