### ISSUE TITLE
php7.0-dev on Ubuntu 14.04 potentially broken

### ISSUE THREAD

**Issue by jawngee** [oerdnj/deb.sury.org#392] opened 2016-06-24 13:34 UTC
Attempting to install php7.0-dev on a fresh droplet on Digital Ocean:

```
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install python-software-properties python-pycurl build-essential python-mysqldb curl git-core dbus
apt-get install php7.0-cli php7.0-common php7.0-curl php7.0-dev php7.0-fpm php7.0-gd php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-xml php7.0-xmlrpc php7.0-zip
```

Results in:

```
The following packages have unmet dependencies:
 php7.0-dev : Depends: libpcre3-dev (>= 2:8:20) but it is not going to be installed
              Recommends: dh-php but it is not going to be installed
              Recommends: pkg-php-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

If I install the libpcre3-dev that is in your repo, the error becomes:

```
The following packages have unmet dependencies:
 php7.0-dev : Depends: libpcre3-dev (>= 2:8:20) but 2:8.38-3.1+deb.sury.org~trusty+6 is to be installed
              Recommends: dh-php but it is not going to be installed
              Recommends: pkg-php-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by xarem** [comment] 2016-06-24 14:15
see #391 

thanks, @oerdnj!

**Comment by oerdnj** [comment] 2016-06-24 15:23
Duplicate of #391

**Closed by oerdnj** 2016-06-24 15:23 UTC
