### ISSUE TITLE
SSL Certification error in Debian 9 stretch

### ISSUE THREAD

**Issue by nikoloskid** [oerdnj/deb.sury.org#1733] opened 2022-03-09 11:13 UTC
**To Reproduce**
1. apt-get -y install apt-transport-https lsb-release ca-certificates curl
2. curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg
`curl: (60) SSL certificate problem: certificate has expired`
3. apt update 
```
Ign:1 https://packages.sury.org/php stretch InRelease
7 https://packages.sury.org/php stretch Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists... Done
E: The repository 'http://packages.sury.org/php stretch Release' does not have a Release file.
```

**Distribution (please complete the following information):**
 - OS: Debian 9 Stretch
 - Architecture: amd64 
 - Repository: packages.sury.org and tried packages.sury.xyz

**Comment by oerdnj** [comment] 2022-03-09 11:22
Duplicate of #1729

**Closed by oerdnj** 2022-03-09 11:22 UTC

**Comment by nikoloskid** [comment] 2022-03-09 11:26
Yes, it looks like it was due to our interal DNS, I changed to Cloudflare's and the updates went through.
