### ISSUE TITLE
php-redis update

### ISSUE THREAD

**Issue by JamesDeGreese** [oerdnj/deb.sury.org#654] opened 2017-07-25 12:42 UTC
Greetings!
The new stable version of php-redis 3.1.3 is now available in the PECL
repositories (from 2017-07-15). Do you plan to update the package of
php-redis in your repository, and if so, when will it be released?
Thanks

**Comment by szepeviktor** [comment] 2017-07-25 20:38
Have you seen the bugreports?

**Comment by oerdnj** [comment] 2017-07-30 18:22
It might be wise to wait for https://github.com/phpredis/phpredis/issues/1211 to be solved first.

**Comment by aTanCS** [comment] 2017-08-29 07:50
It does not look like a bug in the end.
https://github.com/phpredis/phpredis/issues/1211#issuecomment-324126508

**Comment by oerdnj** [comment] 2017-08-29 08:02
It still looks like a regression to me. And it's fixed in the develop branch, so I'll wait for the next release. Or somebody could dig up a commit/patch.

**Comment by oerdnj** [comment] 2017-09-07 18:16
Just released 3.1.4RC1 to the ppa.

**Comment by szepeviktor** [comment] 2017-09-07 18:44
Thank you.

This was long awaited.

**Comment by jonathanvanherpe** [comment] 2017-09-11 00:46
@oerdnj , 3.1.4RC introduces breaking changes ( see https://github.com/snc/SncRedisBundle/issues/357 ), is there a way you can set your ppa to also offer 3.1.2 or 3.1.3 so we can lock that version until SncRedisbundle gets fixed?

**Comment by szepeviktor** [comment] 2017-09-11 16:37
I've used this in `/etc/apt/preferences.d/php-redis-bug`

```
Package: php7.0-redis
Pin: version 3.1.3*
Pin-Priority: -1
```

(Debian jessie)

**Comment by oerdnj** [comment] 2017-09-12 06:14
I am downgrading the package to `3.1.2`. Making intrusive bc-incompatible changes to minor releases is madness.

**Comment by jonathanvanherpe** [comment] 2017-09-12 06:32
@oerdnj  thanks mate!

**Comment by KacerCZ** [comment] 2017-09-25 21:06
Is it possible to add redis extension also for PHP 7.2?

**Comment by oerdnj** [comment] 2017-09-28 18:24
`3.1.4` uploaded, it should have all breaking changes reverted and I believe that it has been also ready built for PHP 7.2

**Closed by oerdnj** 2017-09-28 18:24 UTC
