### ISSUE TITLE
Cannot find save handler 'redis' after update

### ISSUE THREAD

**Issue by dimitris-k** [oerdnj/deb.sury.org#1218] opened 2019-08-11 07:05 UTC
**Problem: Lost session management, php-fpm warning that: _Cannot find save handler 'redis'_**

No problems for a year or two with packages from sury.org. But after I updated some minutes ago, php 7.2 (fpm) cannot connect to redis server with the above message. And session management stopped working...

```
php-redis (4.3.0-1+0~20190606080331.12+stretch~1.gbp0171a6 => 5.0.2+4.3.0-2+0~20190809.14+debian9~1.gbp070358)
php7.2 (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-cli (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-common (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-curl (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-fpm (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-gd (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-json (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-ldap (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-mbstring (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-mysql (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-opcache (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-readline (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-soap (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-xml (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)
php7.2-zip (7.2.20-2+0~20190725.24+debian9~1.gbp69697c => 7.2.21-1+0~20190807.25+debian9~1.gbp935ebf)

```

**Distribution:**
 - OS: Debian Stretch 9.9
 - Architecture: amd64
 - Repository: `deb https://packages.sury.org/php/ stretch main`

**Package:**
```
$ apt-cache policy php-redis
php-redis:
  Installed: 5.0.2+4.3.0-2+0~20190809.14+debian9~1.gbp070358
  Candidate: 5.0.2+4.3.0-2+0~20190809.14+debian9~1.gbp070358
  Version table:
 *** 5.0.2+4.3.0-2+0~20190809.14+debian9~1.gbp070358 500
        500 https://packages.sury.org/php stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     3.1.1-1 500
        500 http://debian.otenet.gr/debian stretch/main amd64 Packages

```
I cannot even downgrade to the previous version that was working...

**Additional context**
Contents of the `/etc/php/7.2/fpm/php.ini` file:
```
session.save_handler = redis
session.save_path = "tcp://localhost:6379?weight=1&persistent=1&database=0"
```
I can also connect and issue queries to the local redis server

**Comment by dimitris-k** [comment] 2019-08-11 07:34
SOLVED

The Debian Stretch redis-server is old.
```
$ apt-cache policy redis-tools
redis-tools:
  Installed: 3:3.2.6-3+deb9u3
  Candidate: 3:3.2.6-3+deb9u3
  Version table:                                                                                                                                 5:5.0.3-3~bpo9+2 100
        100 http://debian.otenet.gr/debian stretch-backports/main amd64 Packages
 *** 3:3.2.6-3+deb9u3 500
        500 http://security.debian.org stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3:3.2.6-3+deb9u2 500
        500 http://debian.otenet.gr/debian stretch/main amd64 Packages
```
Everything works again after installing newer version from backports:
`sudo apt -t stretch-backports install redis-server redis-tools`

**Comment by oerdnj** [comment] 2019-08-11 17:38
Thanks for the info. Is there official upstream repository?

**Comment by dimitris-k** [comment] 2019-08-16 05:03
"Is there official upstream repository?"

Sorry, I am not sure what you ask... For Stretch the "official" upstream is the "backports" repo. For Buster, I see that redis-server available is 5:5.0.3-4 ...

**Comment by oerdnj** [comment] 2019-08-19 06:28
But Jessie users are left with no options. Anyway let’s core that bridge when we get there. I get this is solved, so I am closing the issue.

**Closed by oerdnj** 2019-08-19 06:28 UTC

**Comment by todeveni** [comment] 2019-08-19 06:40
Unable to reproduce with clean Jessie install+this repo and installing `php7.3-cli php-redis redis-server`.

```
php7.3-cli 7.3.8-1+0~20190807.43+debian8~1.gbp7731bf
php-redis 5.0.2+4.3.0-2+0~20190814.15+debian8~1.gbp070358
redis-server 2:2.8.17-1+deb8u7
```

```
<?php
ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://localhost:6379');

session_start();
```

```
vagrant@jessie:~# php test.php && redis-cli
127.0.0.1:6379> keys *
1) "PHPREDIS_SESSION:v56n0keucf4rmqhhfts5hr8m5k"
```
