### ISSUE TITLE
Php 7.0.5 crashes a lot - compiling nightly build solves issue

### ISSUE THREAD

**Issue by cyppe** [oerdnj/deb.sury.org#325] opened 2016-04-19 19:57 UTC
I have a lot of issues when running complex scripts that also uses a lot of MSSQL calls. Not sure if that is the issue.

But when compiling from current PHP-7.0 repository with latest code it works. Cannot say for sure if issues are fixed in code or if it's because how I compile it. Maybe leave out some package that causes the issue.

I see similar issues as mine here in other packages, so do not think it's related to your build:
https://github.com/gplessis/dotdeb-php/issues/128

I have also filed bug report here, but it's possible not complete enought.
https://bugs.php.net/bug.php?id=72044

So I would really appreciate if you can help out to make PPA package with the latest nightly build:
https://bugs.php.net/bug.php?id=72044

As it's a bit complex to maintain self compiled version in Ubuntu in my opinion. And then I hope when next version comes out the issue will be resolved in official version.

**Comment by oerdnj** [comment] 2016-04-19 20:12
I've just uploaded 7.0.6~rc1 to `ppa:ondrej/php-qa`. Wait ~hour for packages to be built and try...

**Comment by cyppe** [comment] 2016-04-19 20:15
Interesting, hope it will work. I have not tried to compile 7.0.6, only 7.0.7-dev that lives in the PHP-7.0 branch and there it worked.   Thanks for the help. Some donation will come to compensate for your time  👍

**Comment by oerdnj** [comment] 2016-04-19 20:55
Lemme know if it doesn't help, I'll pull up even more recent build from nightly.

**Comment by oerdnj** [comment] 2016-04-21 12:56
@cyppe So, did it help?

**Comment by trendzetter** [comment] 2016-04-21 13:59
I will test, just a second

**Comment by trendzetter** [comment] 2016-04-21 14:09
You think this package will work with debian Jessie? I read some strong warnings against using PPA's with debian but need breaks law  :)

**Comment by trendzetter** [comment] 2016-04-21 14:27
Hey Ondřej, I can confirm that the issue is indeed solved by the new build. I am having some inconsistencies because the modules are not from the same source as the php core.

**Comment by trendzetter** [comment] 2016-04-21 14:43
I tried some more, at first it seems to work but on closer inspection I am still seeing those errors. Sorry for false hope ;(

**Comment by oerdnj** [comment] 2016-04-29 19:23
@cyppe PHP 7.0.6 has been published, so did it help? Or should I go looking into upstream git for possible fix?

**Comment by oerdnj** [comment] 2016-04-29 19:35
@cyppe @trendzetter I just pulled https://github.com/php/php-src/commit/92233dd736a883c34d5769081a9c0ff6d9f264f7 to php-qa build. Could you try when it finished building: https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages?batch=300

**Comment by cyppe** [comment] 2016-04-29 21:24
Yes will try, as previous also stated the other build did unfortunately not work. I am currently running production on compiled PHP-7.0 branch (7.0.7) from about 2 weeks ago and it's working great. So I do not dare to touch that production environment for some time in case current PHP-7.0 state is not working as the one I fetched.

But will try to setup new machine to test asap. Thanks.

**Comment by trendzetter** [comment] 2016-05-03 13:41
this patch seems promising, I am in the same situation as cyppe, the server went in production self-compiled so returning to packages is a bit painful.
I will try to install a virtual server on my laptop soon

**Comment by trendzetter** [comment] 2016-05-04 09:41
I tried the new php build but I am still getting same amount of errors of similar type. About 1 in 2 requests aborts on TYPO3 8.1.
`[ 2133.177420] php-fpm7.0[7299]: segfault at 5555554e ip 00007f33468244ae sp 00007ffd3f253298 error 4`

**Comment by cyppe** [comment] 2016-05-04 11:10
Same here, no luck.

Would be interesting if you try to build from PHP-7.0 branch like I did when I got it to work by compiling myself:
https://github.com/php/php-src/tree/PHP-7.0

Now it's 2-3 weeks newer than the version I pulled, but hopefully nothing that breaks the fix has been introduced.

**Comment by trendzetter** [comment] 2016-05-04 11:16
I have 7.0.5 from source compiled, works just fine. I think the difference is in the "self compiling". I don't know why but it appears those packages are build with different options and one of those options is used by all packages but never by those people why compile it for themselves.
I am not convinced that you need a specific patch of branch.

**Comment by cyppe** [comment] 2016-05-04 11:24
Yes maybe, I did something like this, except the paths.

I disabled opcache in my build because I had some issues with it. Maybe
it's the problem?

./configure \
    --prefix=/home/forge/cyppe/php \
    --with-config-file-path=/home/forge/cyppe/php/etc \
    --enable-opcache=no \
    --enable-soap \
    --enable-mbstring \
    --enable-zip \
    --enable-bcmath \
    --enable-pcntl \
    --enable-ftp \
    --enable-exif \
    --enable-calendar \
    --enable-sysvmsg \
    --enable-sysvsem \
    --enable-sysvshm \
    --enable-wddx \
    --enable-mysqlnd \
    --with-curl \
    --with-mcrypt \
    --with-iconv \
    --with-gmp \
    --with-pspell \
    --with-gd \
    --with-jpeg-dir=/usr \
    --with-png-dir=/usr \
    --with-zlib-dir=/usr \
    --with-xpm-dir=/usr \
    --with-freetype-dir=/usr \
    --enable-gd-native-ttf \
    --enable-gd-jis-conv \
    --with-openssl \
    --with-pdo-mysql=/usr \
    --with-pdo-dblib \
    --with-iodbc=/usr/local \
    --with-gettext=/usr \
    --with-zlib=/usr \
    --with-bz2=/usr \
    --with-recode=/usr

ons 4 maj 2016 kl 13:16 skrev trendzetter <notifications@github.com>:

**Comment by oerdnj** [comment] 2016-05-04 11:26
Perhaps it's the same bug as #229? Could you try using PHP packages from the PPA, but disable opcache (`phpdismod opcache`)?

**Comment by trendzetter** [comment] 2016-05-04 12:27
I tested without opcache. Doesn't make a difference for running TYPO3 on php7. Still getting constant crashes:
[04-May-2016 01:23:32] WARNING: [pool www] child 13518 exited on signal 6 (SIGABRT) after 37.201734 seconds from start
[04-May-2016 01:23:32] NOTICE: [pool www] child 13541 started
[04-May-2016 01:23:40] WARNING: [pool www] child 13541 exited on signal 6 (SIGABRT) after 7.227146 seconds from start
[04-May-2016 01:23:40] NOTICE: [pool www] child 13542 started
[04-May-2016 01:24:04] WARNING: [pool www] child 13542 exited on signal 6 (SIGABRT) after 24.387074 seconds from start
[04-May-2016 01:24:04] NOTICE: [pool www] child 13546 started

I don't understand why but everybody who did his own compilation has no issues at all:
https://github.com/gplessis/dotdeb-php/issues/124

**Comment by oerdnj** [comment] 2016-05-04 12:46
I am preparing today's PHP 7.0.7 snapshot for `ppa:ondrej/php-qa`. Let's see if that helps.

**Comment by oerdnj** [comment] 2016-05-05 07:57
@trendzetter @cyppe The snapshot have been built and ready in `ppa:ondrej/php-qa`, could you retest your setup if that helps or not?

**Comment by oerdnj** [comment] 2016-05-13 09:19
@trendzetter @cyppe I uploaded `7.0.7~rc1-1+donate.sury.org~*+3` to `ppa:ondrej/php-qa` with one more fix for a crasher bug pulled from 7.0.8-git. Would you be so kind a retest?

**Comment by trendzetter** [comment] 2016-05-13 13:24
Good news @oerdnj ! The packages work, typo3 is now able to install using these latest packages! Congrats, as far as I know these are the first packaged php7 installers for the debian family that work without those aborts at runtime.

**Comment by oerdnj** [comment] 2016-05-13 13:33
Ok, I'll pull that patch after the weekend into 7.0.6 and we'll see whether it's the patch or 7.0.7~rc1 :)

**Comment by oerdnj** [comment] 2016-05-25 10:18
JFTR it has been in `php7.0` since `7.0.6-11`. So you might try using those. Anyway since the patch fixes the issue, and 7.0.7 is just around the corner (hopefully), I am closing this bug.

**Closed by oerdnj** 2016-05-25 10:18 UTC
Labels: help wanted, moreinfo

**Comment by oerdnj** [comment] 2016-05-30 21:36
And interesting point was made elsewhere, it looks like this might have been error in PCRE 8.35 (recently upgraded to 8.38 in the PPAs).

@trendzetter Are you able to retest it? (Downgrade PCRE to system version and see if the crash happens again.)
