### ISSUE TITLE
removing  systemd remove phpx.x-fpm now :(

### ISSUE THREAD

**Issue by aqueos** [oerdnj/deb.sury.org#1349] opened 2020-02-22 11:12 UTC
hi,

 thanks a lot for your work :)

I had a recent problem in the fact that the phpx.x-fpm package seems now to have a hard depency on systemd. I use sysvinit and when i remove systemd it remove the phpx.x-fpm package of the system now breaking all the websites. 
  
   It does not seems it was the case before because i use the package since a long time and never had the fpm package uninstall because i removed systemd.

  Is there a way to have the dependency to systemd as a soft one and not a hard one ? :)

best regards,
Ghislain.

**Comment by oerdnj** [comment] 2020-02-22 12:25
Then don't remove `systemd` package, it does not conflict with `sysvinit-core`.  Also duplicate of #1347, #1343, and #1348

**Closed by oerdnj** 2020-02-22 12:25 UTC

**Comment by tdrnetworks** [comment] 2020-02-26 02:01
A kind soul has reverted the changes for PHP v5.6 right through to 7.4.3:

http://dev1galaxy.org/viewtopic.php?id=3331
