### ISSUE TITLE
5.6.31-1~ubuntu16.04.1+deb.sury.org+1 uninstallable

### ISSUE THREAD

**Issue by Batailic** [oerdnj/deb.sury.org#639] opened 2017-07-06 11:03 UTC
On Ubuntu 16.04 the package can not be installed because it depends on:
libssl1.1 (>= 1.1.0) (UNAVAILABLE)

**Comment by dmitry-nksupport** [comment] 2017-07-06 11:08
Same thing on Ubuntu 14.04 when installing php7.0 or php7.1:


# apt-get install php7.1-fpm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-fpm : Depends: php7.1-cli but it is not going to be installed
              Depends: php7.1-common (= 7.1.7-1~ubuntu14.04.1+deb.sury.org+1) but it is not going to be installed
              Depends: php7.1-json but it is not going to be installed
              Depends: php7.1-opcache but it is not going to be installed
              Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.


Package libssl1.1 is not available in any Ubuntu distributions.

**Comment by h1kkan** [comment] 2017-07-06 11:44
Same issue on ubuntu 16.04.2 LTS when i try to install php5.6, but if update it (not fresh installation) - all ok.

```

The following packages have unmet dependencies:
 php5.6-cli : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php5.6-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php5.6-fpm : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by oerdnj** [comment] 2017-07-06 11:57
Ah, that's side-effect of enabling OpenSSL 1.1.0 in `ppa:ondrej/apache2`. I have just uploaded openssl 1.1.0f to `ppa:ondrej/php`, so it should be fixed shortly after the packages finish building.

**Comment by ChrisWiegman** [comment] 2017-07-06 11:57
Also reporting same issue on 16.04.02. Tried to force install libssl1.1 and got the following:

```
sudo apt-get install libssl1.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libssl1.1' has no installation candidate
```

**Comment by ricardoper** [comment] 2017-07-06 12:21
Same problem on a **LinuxMint 18.x**.

Temporary fix with a Debian package:
https://packages.debian.org/stretch/libssl1.1

**Comment by oerdnj** [comment] 2017-07-06 12:25
Should be fixed as of this moment.

Mixing Ubuntu PPAs with packages from Debian Stretch on *Linux Mint* doesn't really sound like something you should be doing.

**Closed by oerdnj** 2017-07-06 12:25 UTC

**Comment by teward** [comment] 2017-07-06 12:48
@oerdnj Nor does upgrading to LibSSL 1.1.0 on 16.04 or 14.04.

I question your approach to this solely because the number of packages that can explode from two SSL library versions being available on the same system is insane.  It's one reason why OpenSSL 1.1.0 isn't in Ubuntu yet.

**Comment by iamacup** [comment] 2017-07-06 12:58
I am also having this issue - full description and details here: https://stackoverflow.com/questions/44947497/php-7-install-on-ubuntu-14-04-now-fails-due-to-libssl-dependency-that-cant-be-re

**Comment by oerdnj** [comment] 2017-07-06 13:13
@teward Perhaps you should lookup what a `SONAME` is and what 'versioned symbols' are before making any judgement.

**Comment by PushEngineering** [comment] 2017-07-06 13:41
confirmed issue resolved for me - many thanks.

**Comment by lobsterdore** [comment] 2018-03-28 14:33
@oerdnj looks like this issue is happening again, I've opened a new issue #840

**Comment by matthbull** [comment] 2018-03-28 14:43
Im still getting this problem when trying to install php-7.2 onto ubuntu 16.04

**Comment by yassine-khachlek** [comment] 2018-03-28 14:55
Yes, it just happen for me too:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.1-cli : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.1-common : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 php7.1-fpm : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ricardoper** [comment] 2018-03-28 15:00
Hello, same problem here... Ubuntu 16.04 and in Docker images too.

**Comment by aleqx** [comment] 2020-02-08 14:57
I'm having issues with this as well. Your repo has overwritten libssl-dev with 1.1 headers and wiped the 1.0 headers ... compilation of most things expecting 1.0 headers now fails.
