### ISSUE TITLE
PHP 5.6.7 won't start on Ubuntu 15.04

### ISSUE THREAD

**Issue by TheDigitalOrchard** [oerdnj/deb.sury.org#65] opened 2015-05-01 05:02 UTC
Brand new server, first time using 15.04. Built from a snapshot running 14.10 with an existing server setup (Ngnix+PHP5.6). Despite several attempts, php5-fpm just refuses to start. I believe my unfamiliarity with `systemd` is part of the problem, but maybe we're just not ready for 15.04 yet? 

Here's some info running `systemctl status`:

```
sudo systemctl status php5-fpm.service
● php5-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php5-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Thu 2015-04-30 21:54:23 PDT; 2min 30s ago
 Main PID: 15926 (code=exited, status=0/SUCCESS)

Apr 30 21:52:52  systemd[1]: Starting The PHP FastCGI Process Manager...
Apr 30 21:54:23  systemd[1]: php5-fpm.service start operation timed out. Terminating.
Apr 30 21:54:23  systemd[1]: Failed to start The PHP FastCGI Process Manager.
Apr 30 21:54:23  systemd[1]: Unit php5-fpm.service entered failed state.
Apr 30 21:54:23  systemd[1]: php5-fpm.service failed.
```

At this point, I'm at a loss for what to do next aside from completely starting from scratch, which I really don't want to do.

**Comment by TheDigitalOrchard** [comment] 2015-05-01 05:06
The `/var/log/php5-fpm.log` shows this activity.... the process starts, and then two minutes later, it terminates for an unknown reason.

```
[30-Apr-2015 21:52:52] NOTICE: configuration file /etc/php5/fpm/php-fpm.conf test is successful

[30-Apr-2015 21:52:52] NOTICE: fpm is running, pid 15926
[30-Apr-2015 21:52:52] NOTICE: ready to handle connections
[30-Apr-2015 21:54:23] NOTICE: Terminating ...
[30-Apr-2015 21:54:23] NOTICE: exiting, bye-bye!
```

**Comment by oerdnj** [comment] 2015-05-02 11:14
Very wild guess: Your service file contains Type=notify, but php5-fpm hasn't been compiled with systemd support. Replace Type=notify with Type=simple as a workaround or compile php5-fpm with systemd - you can patch -R (reverse the patch) this: https://github.com/oerdnj/pkg-php/commit/b76fc828bdd113b1d1072744932e137c11ca57dc.patch

**Comment by neclimdul** [comment] 2015-05-05 16:43
We come to your ppa's for the compiling! :)

Thanks for the workaround! I was googling this yesterday and only found old emails from you on the systemd mailing list but couldn't sort out what the workaround was.

Is there any chance of disabling the linked patch for the vivid builds and beyond?

**Comment by oerdnj** [comment] 2015-05-05 16:50
Yeah, I will think of something...

**Comment by neclimdul** [comment] 2015-05-05 18:20
Just incase someone comes along later and so I remember what I did later, `/lib/systemd/system/php5-fpm.service` has the default file. This line copies a version to `/etc/systemd/system` opens an editor to let you modify it.

```
sudo systemctl edit --full php5-fpm
```

**Comment by ChrisWiegman** [comment] 2015-05-13 23:04
While the workaround works this isn't a solution. Any ETA on when you'll have this fixed?

**Comment by oerdnj** [comment] 2015-05-14 10:03
@ChrisWiegman Could you try 5.6.8+dfsg-1+deb.sury.org~vivid+4? I don't have a vivid installed anywhere, but I made some adjustmenst to d/control and d/rules to build _with_ systemd on vivid (or rather disable systemd on precise, trusty and oneiric)

**Comment by oerdnj** [comment] 2015-05-14 14:17
@TheDigitalOrchard @neclimdul Could you please try it as well? I am closing this bug, but feel free to reopen if it's not fixed.

**Closed by oerdnj** 2015-05-14 14:17 UTC

**Comment by neclimdul** [comment] 2015-05-14 14:34
updated this morning, reverted my systemd config, restart, stop, start, stop, start. all smooth and fast. Thanks!

**Comment by oerdnj** [comment] 2015-05-14 14:49
Cool, at least I have tested how to modify d/control and d/rules for different releases.

**Comment by golevel** [comment] 2015-11-30 16:50
@oerdnj I just ran into this same problem, but not having done this before I'm not sure what my step by step process should be to resolve it. For myself and others finding this link from Google, what exactly do we do to fix this?

**Comment by oerdnj** [comment] 2015-11-30 17:17
@golevel Depends on what you are trying to achieve? If you are not using my PHP PPA then I can't fix errors in Ubuntu packages -> try the trick with editing systemd unit fily replacing `Type=notify` with `Type=simple` within the file.

**Comment by golevel** [comment] 2015-11-30 17:23
Sorry, I may have just created a repost of this as a new issue, I'm not sure which is the right protocol. I found you through this link:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1451346

Which seems to match up perfectly with my issue, down to the manual start working for me as a temporary solution.

Thank you though, I will try that solution.

**Comment by golevel** [comment] 2015-11-30 17:31
I can't seem to find a systemd unit file. Where/how do I do that? I'm looking in /lib/systemd.

**Comment by oerdnj** [comment] 2015-11-30 17:34
https://github.com/oerdnj/deb.sury.org/issues/65#issuecomment-99165351

But why you are using outdated version of PHP (5.6.7)? Just upgrade to latest and be done with it.

**Comment by oerdnj** [comment] 2015-11-30 17:37
Ah I see, so it's probably bug in Ubuntu version, you should bug them about fixing the bug there if it's plain Ubuntu php5 version.

**Comment by golevel** [comment] 2015-11-30 17:39
I'm using PHP 5.6.11-1+deb.sury.org~utopic+1 (cli) but the issue is the exact same as far as I can tell.

**Comment by oerdnj** [comment] 2015-11-30 19:14
Ubuntu Utopic was discontinued on July 23, 2015, so update your Ubuntu and your PHP version to latest available.

**Comment by golevel** [comment] 2015-11-30 19:26
I did, that's when the problems started. Am I using the wrong version of PHP?

**Comment by oerdnj** [comment] 2015-11-30 20:09
5.6.15 is latest packaged version with 5.6.16 in the queue (it was released last Thursday).

**Comment by golevel** [comment] 2015-12-08 18:20
If my php version is this:

5.6.11-1+deb.sury.org~utopic+1 (cli)

And my ubuntu version is this:

Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

How do I update php so that I don't have the utopic tag (if that's the problem) and update to the latest version? I'm guessing that the +deb.sury.org means I am using your PPA.

Sorry for the newbie questions, this is my first major Ubuntu update using DigitalOcean.

**Comment by oerdnj** [comment] 2015-12-08 18:38
Add the PPA again, it got disabled during update. 

On 8 Dec 2015, golevel <notifications@github.com> wrote:
>If my php version is this:
>
>5.6.11-1+deb.sury.org~utopic+1 (cli)
>
>And my ubuntu version is this:
>
>Distributor ID:	Ubuntu
>Description:	Ubuntu 15.10
>Release:	15.10
>Codename:	wily
>
>How do I update php so that I don't have the utopic tag (if that's the
>problem) and update to the latest version? I'm guessing that the
>+deb.sury.org means I am using your PPA.
>
>Sorry for the newbie questions, this is my first major Ubuntu update
>using DigitalOcean.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/oerdnj/deb.sury.org/issues/65#issuecomment-162967964

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by golevel** [comment] 2015-12-08 18:40
How do I do that? My upgrade process was just doing sudo do-release-upgrade. I'm not sure where to go from here.

**Comment by oerdnj** [comment] 2015-12-09 09:49
@golang I am sorry, but I can't do regular end-user support. Please visit http://ubuntuforums.org/ or search on AskUbuntu to get answer related to basic system administration.
