### ISSUE TITLE
Openssl issue

### ISSUE THREAD

**Issue by vixxtor** [oerdnj/deb.sury.org#650] opened 2017-07-20 12:22 UTC
Hello,

Most probably after the last update of php5.6 and openssl from your ppa, I have an issue with openssl functions. To keep it simple, the following script, which used to work before (and works on another system with a different php version) stopped working (the openssl_seal function doesn't work).

apt-cache madison openssl
   openssl | 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1 | http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages

**Comment by vixxtor** [comment] 2017-07-20 12:25
[test.txt](https://github.com/oerdnj/deb.sury.org/files/1162232/test.txt)

[certificate.pem.txt](https://github.com/oerdnj/deb.sury.org/files/1162233/certificate.pem.txt)

Attached are an easy sample script and a certificate (to be renabed back into certificate.pem) in order to test it. 

Output on affected system is:
loading public key
key=Array
(
    [bits] => 2048
    [key] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8UR9G5trj9vRebEUqmW
5gGmA1lSIv6Lcy7XvOasKDqjXPJAJ+HkpDQz7dfVY/qBUQPyWMnZBCFRzh1lMmhX
nl5bqjAHKBNoqYzN6ZPG4osgxj07LdrNLkVnTYXnPJ+r7fifSe/m/h5B0uLrhhOW
4b3fDaj37crhDFwgMHTj51CiOfy+i6aSG5Xr0Dj3pB6FGXrMF3LCQyzkgwlkopUx
hpnwj5jMlWUGVzRid5eI9dcqLtxF/xb5uApsn8lPaPq5mpYj9SgC4DflpH8HeJqA
Rh64jiLEh4LOBga3QbW9hMJ1DF5RYAXH34GrHaXnjrnu4k4xfY33cqXTms9QqDO0
XwIDAQAB
-----END PUBLIC KEY-----

    [rsa] => Array
        (
�����       [n] => ���nm�?oE��R����YR"��s.׼��(:�\�@'���43���c��Q�X��!Q�e2hW�^[�0(h�������� �=;-��.EgM��<�����I���A��������
     \ 0t��P�9��������8���z�r�C,��	d��1�����̕eW4bw����*.�E���
l��Oh����#�(�7��x��F��"ć���A����u
                                     ^Q`�߁��玹��N1}��r�Ӛ�P�3�_
            [e] => 
        )

    [type] => 0
)

error=
-----------
encrypting
srcData=this is my secret message
error=
result=
pkeys=Array
(
    [0] => Resource id #4
)

envkeys=
encdata=
-----------
Error while encrypting data! Reason:

While output on working system is:
loading public key
key=Array
(
    [bits] => 2048
    [key] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8UR9G5trj9vRebEUqmW
5gGmA1lSIv6Lcy7XvOasKDqjXPJAJ+HkpDQz7dfVY/qBUQPyWMnZBCFRzh1lMmhX
nl5bqjAHKBNoqYzN6ZPG4osgxj07LdrNLkVnTYXnPJ+r7fifSe/m/h5B0uLrhhOW
4b3fDaj37crhDFwgMHTj51CiOfy+i6aSG5Xr0Dj3pB6FGXrMF3LCQyzkgwlkopUx
hpnwj5jMlWUGVzRid5eI9dcqLtxF/xb5uApsn8lPaPq5mpYj9SgC4DflpH8HeJqA
Rh64jiLEh4LOBga3QbW9hMJ1DF5RYAXH34GrHaXnjrnu4k4xfY33cqXTms9QqDO0
XwIDAQAB
-----END PUBLIC KEY-----

    [rsa] => Array
        (
�����       [n] => ���nm�?oE��R����YR"��s.׼��(:�\�@'���43���c��Q�X��!Q�e2hW�^[�0(h�������� �=;-��.EgM��<�����I���A��������
     \ 0t��P�9��������8���z�r�C,��	d��1�����̕eW4bw����*.�E���
l��Oh����#�(�7��x��F��"ć���A����u
                                     ^Q`�߁��玹��N1}��r�Ӛ�P�3�_
            [e] => 
        )

    [type] => 0
)

error=
-----------
encrypting
srcData=this is my secret message
error=
result=25
pkeys=Array
(
    [0] => Resource id #4
)

envkeys=Array
(
��N���> J�r�����0:B��4Ո=i5������ױ�b3Hx?���w�ݕ�*�
U
\9,�߇����B�|���� �s�"�z������7��|O}l4���!�"YA|��806R�[ռW_�O6ʬꅺ�
L�
  ���t����ס�Tv��2�b�j�y���6|c6��
                                    d�B�X\���ޓ��\��
                                                     I2f�ZH���
+
 A�i�xk��
         iG��6)d
)

encdata=U��D�hZŖ6�3W�:�|7*ڀ�Q��

**Comment by oerdnj** [comment] 2017-07-20 15:15
Unfortunately I can't reproduce this on Debian stretch with OpenSSL 1.1.0f compiled php5.6:
```
$ php5.6 -i | grep -i ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.0f  25 May 2017
OpenSSL Header Version => OpenSSL 1.1.0f  25 May 2017
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
```

And the test script runs just fine with your certificate:
```
$ php5.6 openssl_seal.php 
loading public key
key=Array
(
    [bits] => 2048
    [key] => -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn8UR9G5trj9vRebEUqmW
5gGmA1lSIv6Lcy7XvOasKDqjXPJAJ+HkpDQz7dfVY/qBUQPyWMnZBCFRzh1lMmhX
nl5bqjAHKBNoqYzN6ZPG4osgxj07LdrNLkVnTYXnPJ+r7fifSe/m/h5B0uLrhhOW
4b3fDaj37crhDFwgMHTj51CiOfy+i6aSG5Xr0Dj3pB6FGXrMF3LCQyzkgwlkopUx
hpnwj5jMlWUGVzRid5eI9dcqLtxF/xb5uApsn8lPaPq5mpYj9SgC4DflpH8HeJqA
Rh64jiLEh4LOBga3QbW9hMJ1DF5RYAXH34GrHaXnjrnu4k4xfY33cqXTms9QqDO0
XwIDAQAB
-----END PUBLIC KEY-----

    [rsa] => Array
        (
            [n] => [binary_data]
            [e] => [binary_data]
        )

    [type] => 0
)

error=
-----------
encrypting
srcData=this is my secret message
error=
result=25
pkeys=Array
(
    [0] => Resource id #4
)

envkeys=Array
(
    [0] => [binary_data]
)

encdata=[binary_data]
-----------
```

**Comment by oerdnj** [comment] 2017-07-20 15:20
BTW Not sure what is your usage scenario, but using RC4 to ensure security doesn't seem like a good idea anyway.

**Comment by vixxtor** [comment] 2017-07-20 17:07
Hi,

RC4 is not an issue in reality, the code is just simplified to the maximum just to prove the issue.

I have just installed a plain ubuntu 16.04, updated it then installed your latest php5.6. I am getting the same wrong behavior.

Using php7.0-cli works fine on the same machine, so the issue is strictly in php5.6.

If you want, I can give you ssh access to the machine (it is empty and you can do whatever you want to it in order to troubleshoot). Just write me a direct e-mail (vixtor at gmail dot com) with your source IP address.

**Comment by vixxtor** [comment] 2017-07-24 09:33
Hello,

Do you have any news regarding this issue? Is there anything I can help you more with this?

**Comment by aphilippi** [comment] 2017-07-26 13:54
I have exactly the same issue on a Ubuntu 16.04.2 LTS

the script works with php7.0, php7.1, but fails on php5.6

My openssl version:
dpkg -s openssl
Version: 1.1.0f-2~ubuntu16.04.1+deb.sury.org+1

php5.6 -i | grep -i ssl:

Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv2, tls, tlsv1.0, tlsv1.1, tlsv1.2
SSL => Yes
SSL Version => OpenSSL/1.0.2g
core SSL => supported
extended SSL => supported
openssl
OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 1.1.0f  25 May 2017
OpenSSL Header Version => OpenSSL 1.1.0f  25 May 2017
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
Native OpenSSL support => enabled
OLDPWD => /usr/lib/ssl
_SERVER["OLDPWD"] => /usr/lib/ssl

Any hint is appreciated

**Comment by oerdnj** [comment] 2017-07-26 13:58
@zsalab any ideas?

**Comment by bic-marius-cristea** [comment] 2017-07-26 14:41
same issue here - a brand new 16.04.2 LTS produces the same missing output for php5.6

**Comment by zsalab** [comment] 2017-07-26 15:08
Can somebody create a docker image where I can reproduce the problem? Unfortunately my time is limited on this, but I try the best to find the problem.... please give me a Docker image and I will try to figure out whats wrong

**Comment by zsalab** [comment] 2017-07-26 15:10
By the way the version for compiling the PHP and the version installed by the time using it is the same?
@oerdnj do you know which OpenSSL version did you used to compile this packages?

**Comment by zsalab** [comment] 2017-07-26 15:20
By the way how far I understand that is an "old" ubuntu but with 1.1 openssl.... I do not think it is a good idea, my advice to use the PHP (<7.0) with the OpenSSL 1.0 on the OS which comes with OpenSSL 1.0
https://packages.ubuntu.com/xenial-updates/openssl

**Comment by oerdnj** [comment] 2017-07-26 15:25
@zsalab That's hard to achieve when people want modern TLS crypto in the http server at the same time. 

BTW there's no Ubuntu release with OpenSSL 1.1 at all.

**Comment by oerdnj** [comment] 2017-07-26 15:28
The compile time and run time libraries match - SONAME makes sure of that.

**Comment by oerdnj** [comment] 2017-07-26 15:28
And versioned symbols...

**Comment by aphilippi** [comment] 2017-07-26 15:29
Thanks for the replys. 

Yes, it's a "old ubuntu but with 1.1 openssl".... 
But we run multiple php versions (5.6, 7.0, 7.1)  on it.

**Comment by zsalab** [comment] 2017-07-26 15:44
@oerdnj I think if you compile with 1.0.2e you can run with 1.0.2.f
@aphilippi My advice to build the packages from source and try, if does not works please share the output of the build with me (the all)

**Comment by oerdnj** [comment] 2017-07-26 15:49
@zsalab That's true, but this doesn't have any impact otherwise everything would be broken all the time. Those are just patch releases and are safe to upgrade unless there's a major screw-up. 

I suspect it might be something about changed API of this particular function between 5.6 and 7.0

**Comment by zsalab** [comment] 2017-07-26 15:50
@oerdnj I hope you do not mind if I try to consider all the possibilities? But of course you can do the debugging by yourself if you want

**Comment by oerdnj** [comment] 2017-07-26 20:14
@zsalab No judgment was attached to my statement. Sorry if I offended you, it was unintentional. 

I'll review the OpenSSL patch around the affected function to see if I can catch the culprit tomorrow.

**Comment by zsalab** [comment] 2017-07-27 07:15
So, the patch is not a backport of the PHP 7 OpenSSL module, that was an original plan but you remember it just did not work.
My opinion we really have to see the build log (your PHP packages executing the tests but did not care about the result), so probably we should see there some error which can help to determine the problem.
How far I understand you tried on Debian Stretch and you could not reproduce there the problem (unfortunately I do not have Ubuntu, so I can not try just if somebody willing to give me a Docker file which prepared for reproduce the problem).

**Comment by oerdnj** [comment] 2017-07-27 08:54
I think I found the culprint:
```
-	if (EVP_SealInit(&ctx, cipher, eks, eksl, NULL, pkeys, nkeys) <= 0 ||
-			!EVP_SealUpdate(&ctx, buf, &len1, (unsigned char *)data, data_len) ||
-			!EVP_SealFinal(&ctx, buf + len1, &len2)) {
+	if (!EVP_SealInit(ctx, cipher, eks, eksl, NULL, pkeys, nkeys) <= 0 ||
+			!EVP_SealUpdate(ctx, buf, &len1, (unsigned char *a)data, data_len) ||
+			!EVP_SealFinal(ctx, buf + len1, &len2)) {
```


`EVP_SealInit` returns 0 on error and npubkey on success.

**Comment by oerdnj** [comment] 2017-07-27 08:57
@vixxtor @aphilippi @bic-marius-cristea Could either of you try installing 5.6.31-2+ubuntu16.04.1+deb.sury.org+0.0 from `ppa:ondrej/php` once it finished building[1], please?

1. https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+build/13158344

**Comment by zsalab** [comment] 2017-07-27 09:02
@oerdnj  I see there is build log, but looks just a part of it. Can you publish/send to me the build log?

**Comment by oerdnj** [comment] 2017-07-27 09:02
@zsalab "Currently building" - the full build log will be available after the build finishes.

**Comment by vixxtor** [comment] 2017-07-27 09:07
I will test it. For now there's no update available.

**Comment by vixxtor** [comment] 2017-07-27 09:52
Hi,

The build seems to have finished. I see the new package in the php-qa web page, but I don't find it with apt at all:

root@frontend-1:~# apt-get update
Hit:1 http://ro.archive.ubuntu.com/ubuntu xenial InRelease
**Hit:2 http://ppa.launchpad.net/ondrej/php-qa/ubuntu xenial InRelease**
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                         
Hit:4 http://ro.archive.ubuntu.com/ubuntu xenial-updates InRelease                                                        
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease                                   
Hit:6 http://ro.archive.ubuntu.com/ubuntu xenial-backports InRelease                                
Reading package lists... Done                     
root@frontend-1:~# apt-show-versions php5.6
**php5.6:all/xenial 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 uptodate**
root@frontend-1:~# uname -a
Linux frontend-1 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vixxtor** [comment] 2017-07-27 09:55
Found the reason - the build was successful but not yet published.

**Comment by oerdnj** [comment] 2017-07-27 10:08
I found one little hidden Ubuntu machine and the issue has been resolved with the updated package. I am uploading a proper version into the main repository right now.

**Closed by oerdnj** 2017-07-27 10:08 UTC

**Comment by vixxtor** [comment] 2017-07-27 10:47
Yes, it seems to be working fine.

**Comment by zsalab** [comment] 2017-07-27 11:03
@oerdnj may I ask the cause of the problem?

**Comment by oerdnj** [comment] 2017-07-27 11:08
@zsalab There was an extra `!` in front of `EVP_SealInit`. If you have a local copy of the patch, use this on top of it:

https://gitlab.sury.org/pkg-php/php/commit/7ef7cb61bb23fe3fcbcba9ca6d1326cf4e3d1347

**Comment by zsalab** [comment] 2017-07-27 11:18
@oerdnj ah, I see this was a bug in PHP and they fix it but the patch update missed this...
https://bugs.php.net/bug.php?id=74651
thank you to let me know

**Comment by aphilippi** [comment] 2017-07-27 21:22
Hi, thanks a lot and sorry for being unresponsive - travelling with 3 kids :)

I installed the  5.6.31-2+ubuntu16.04.1+deb.sury.org+0.0 from ppa:ondrej/php and now it works. 

Thanks a lot for you quick and effective reaction.
