### ISSUE TITLE
php8.1/php8.2 propro.so warning - undefined symbol: convert_to_explicit_type_ex

### ISSUE THREAD

**Issue by hknet** [oerdnj/deb.sury.org#1989] opened 2023-06-29 07:19 UTC
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

on ubuntu 22.04 LTS deploying the following using ppa-sources:
apt install php8.1 php8.1-bcmath php8.1-bz2 php8.1-cli php8.1-common php8.1-curl php8.1-dba php8.1-fpm php8.1-gd php8.1-imap php8.1-intl php8.1-mbstring php8.1-mysql php8.1-opcache php8.1-readline php8.1-soap php8.1-xml php8.1-xsl php8.1-zip php8.1-raphf php8.1-http php8.1-mcrypt php8.1-apcu php8.1-apcu php8.1-gmp php8.1-propro

then a cli "php8.1 -v" call reports:

php8.1 -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'propro.so' (tried: /usr/lib/php/20210902/propro.so (/usr/lib/php/20210902/propro.so: undefined symbol: convert_to_explicit_type_ex), /usr/lib/php/20210902/propro.so.so (/usr/lib/php/20210902/propro.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.20 (cli) (built: Jun  8 2023 15:26:07) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.20, Copyright (c), by Zend Technologies

same is true for 8.2, while 8.0 and below do not report this warning.

**Comment by oerdnj** [comment] 2023-06-29 08:58
What’s ldd output on the propro.so?

**Comment by BaderSZ** [comment] 2023-07-01 18:56
> What’s ldd output on the propro.so?

Here's my ldd output, since I'm having this issue as well:

```bash
$ ldd /usr/lib/php/20220829/propro.so
	linux-vdso.so.1 (0x00007ffcaaa8b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbb11064000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbb1129d000)
```

**Comment by todeveni** [comment] 2023-07-01 19:17
propro isn't PHP 8.1+ compatible due to PHP dropping `convert_to_explicit_type_ex`?
> Also drop the unused convert_to_explicit_type macros.
https://github.com/php/php-src/commit/422d1665a2a744421b5911cbe8541370509bc4f5

Reproducible steps with Docker.
`docker run -it ubuntu:22.04 /bin/bash`

```
apt update
apt install software-properties-common
add-apt-repository ppa:ondrej/php
apt install php8.1-cli php8.1-propro
```

```
# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'propro.so' (tried: /usr/lib/php/20210902/propro.so (/usr/lib/php/20210902/propro.so: undefined symbol: convert_to_explicit_type_ex), /usr/lib/php/20210902/propro.so.so (/usr/lib/php/20210902/propro.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.20 (cli) (built: Jun  8 2023 15:26:07) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.20, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.20, Copyright (c), by Zend Technologies
```

```
# ldd -v /usr/lib/php/20210902/propro.so
	linux-vdso.so.1 (0x0000ffff9d6b1000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff9d4b0000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffff9d678000)

	Version information:
	/usr/lib/php/20210902/propro.so:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		libc.so.6 (GLIBC_2.17) => /lib/aarch64-linux-gnu/libc.so.6
	/lib/aarch64-linux-gnu/libc.so.6:
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
```

**Comment by vafhornung** [comment] 2023-07-07 13:55
The propro devs themselves said in the last commit (https://github.com/m6w6/ext-propro/commit/921871c048332818704008ce7b67f8f2e32d3cf4) "Propro support has been discontinued since PHP 8.0".

I think there should be no (php-8.0/)php8.1/php8.2-propro packages in the repo.

**Comment by oerdnj** [comment] 2023-07-07 15:17
> The propro devs themselves said in the last commit ([m6w6/ext-propro@921871c](https://github.com/m6w6/ext-propro/commit/921871c048332818704008ce7b67f8f2e32d3cf4)) "Propro support has been discontinued since PHP 8.0".
> 
> I think there should be no (php-8.0/)php8.1/php8.2-propro packages in the repo.

Yeah, that’s my plan.

**Comment by oerdnj** [comment] 2023-08-29 10:34
Hmm, looks like something went wrong and now only php7.4-propro has been built. That's also not correct. Let's try one more time.

**Comment by oerdnj** [comment] 2023-10-06 10:17
This should be fixed now

**Closed by oerdnj** 2023-10-06 10:17 UTC

**Comment by oerdnj** [comment] 2024-06-27 10:13
You need to uninstall `php8.1-propro`; there’s no propro extension for PHP 8.x
