### ISSUE TITLE
PECL HTTP module (php5.6-http package) not working

### ISSUE THREAD

**Issue by C-Duv** [oerdnj/deb.sury.org#439] opened 2016-08-23 09:46 UTC
On Ubuntu 16.04.1 I have a PHP v5.6 working thanks to `php5.6` from ppa:ondrej/php5-5.6 (all other PHP versions -id. PHP 7- removed).

But after installing `php5.6-http` (which installed `php-http`, `php-propro{a}` and `php-raphf{a}`) I cannot use the [http_build_url()](http://php.net/manual/pl/function.http-build-url.php) PHP function:

```Shell
$ php5.6 -r 'http_build_url();'
PHP Fatal error:  Call to undefined function http_build_url() in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
```

PHP version
```Shell
PHP 5.6.25-1+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

PHP modules:
```Shell
$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
http
iconv
imagick
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
propro
raphf
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Xdebug
Zend OPcache
```

PHP-related Ubuntu packages:

| Package               | Version                                              |
|-----------------------|------------------------------------------------------|
| dh-php                | 0.21+deb.sury.org~xenial+1                           |
| libapache2-mod-php5.6 | 5.6.25-1+deb.sury.org~xenial+1                       |
| php-common            | 1:44+deb.sury.org~xenial+1                           |
| php-http              | 3.0.1+2.5.6-6+deb.sury.org~xenial+1                  |
| php-imagick           | 3.4.2-2+donate.sury.org~xenial+1                     |
| php-pear              | 1:1.10.1+submodules+notgz-8+donate.sury.org~xenial+2 |
| php-propro            | 2.0.0+1.0.2-2+donate.sury.org~xenial+1               |
| php-raphf             | 2.0.0+1.1.2-2+deb.sury.org~xenial+1                  |
| php-xdebug            | 2.4.0-5+donate.sury.org~xenial+1                     |
| php5.6                | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-cli            | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-common         | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-curl           | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-dev            | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-gd             | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-json           | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-ldap           | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-mbstring       | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-mcrypt         | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-mysql          | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-opcache        | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-readline       | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-xml            | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-xmlrpc         | 5.6.25-1+deb.sury.org~xenial+1                       |
| php5.6-zip            | 5.6.25-1+deb.sury.org~xenial+1                       |
| pkg-php-tools         | 1.33+deb.sury.org~xenial+1                           |

**Comment by oerdnj** [comment] 2016-08-25 12:10
Can you confirm that php-http got enabled? (Try running `phpenmod http`)

**Comment by C-Duv** [comment] 2016-08-26 11:20
It seems OK:
```Shell
$ ls -l /etc/php/5.6/*/conf.d/*-http.ini
rwxrwxrwx 1 root root 36 août  23 11:26 /etc/php/5.6/apache2/conf.d/25-http.ini -> /etc/php/5.6/mods-available/http.ini
lrwxrwxrwx 1 root root 36 août  23 11:26 /etc/php/5.6/cli/conf.d/25-http.ini -> /etc/php/5.6/mods-available/http.ini
```

**Comment by ihipop** [comment] 2016-09-08 03:52
same issue

**Comment by muhh** [comment] 2016-10-19 06:08
I have the same problem (on precise though).

`http_build_url()` is not from php-http, but from pecl_http. 

There is a php-pecl-http package, but it somehow doesn't get installed. I don't understand why.
Installing `php-http` installs the ubuntu package.

**Comment by muhh** [comment] 2016-10-26 08:30
I reproduced the issue on trusty. Same problem.

Is there anything I can do to help debug this issue?

**Comment by oerdnj** [comment] 2016-10-26 09:08
What does `apt-cache policy php-http` say?

**Comment by muhh** [comment] 2016-10-26 11:08
```
# apt-cache policy php-http
php-http:
  Installed: 3.0.1+2.5.6-6+deb.sury.org~trusty+1
  Candidate: 3.0.1+2.5.6-6+deb.sury.org~trusty+1
  Version table:
 *** 3.0.1+2.5.6-6+deb.sury.org~trusty+1 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4.1-2 0
        500 http://mirror.hetzner.de/ubuntu/packages/ trusty/universe amd64 Packages
```

**Comment by oerdnj** [comment] 2016-10-26 11:20
That seems fine, you have the pecl_http version of php-http installed.

**Comment by oerdnj** [comment] 2016-10-26 11:30
Looks like the module is loaded, but it doesn't export the function. Don't know why yet.

**Comment by muhh** [comment] 2016-10-26 12:48
I found the reason: It's as simple as that the function does only exist in pecl_http in older versions.

The PHP documentation sadly does not reflect this. 

I'm very ok with closing this issue.

**Comment by oerdnj** [comment] 2016-10-26 12:53
ok :), if you have a time please report it to bugs.php.net and report the url here for reference.

**Closed by oerdnj** 2016-10-26 12:53 UTC

**Comment by C-Duv** [comment] 2016-10-26 13:11
So [`http_build_url()`](http://php.net/manual/pl/function.http-build-url.php) function does not exists anymore in upstream PECL?

I guess my alternative is to use [`jakeasmith/http_build_url`](https://packagist.org/packages/jakeasmith/http_build_url)Composer package.

Thanks for the details @muhh :)
