### ISSUE TITLE
PPA add composer

### ISSUE THREAD

**Issue by rudiservo** [oerdnj/deb.sury.org#1529] opened 2021-02-08 18:19 UTC
Hi, is it possible to add Composer to the ubuntu PPA and keep it relatively up to date.

**Comment by oerdnj** [comment] 2021-02-08 18:42
Duplicate of #1411

**Closed** 2021-02-08 18:43 UTC

**Comment by rudiservo** [comment] 2021-02-08 21:09
@oerdnj sorry for the duplicate
