### ISSUE TITLE
Couldn't install any PHP variant from your repository under Jessie (arch i386) due to broken dependency (libssl)

### ISSUE THREAD

**Issue by nuxwin** [oerdnj/deb.sury.org#645] opened 2017-07-10 19:40 UTC
@oerdnj 

As said in the title, it is currently impossible to install any PHP variant from your repository under Debian Jessie (Arch i386). You have a dependency on the libssl1.0.0 (>= 1.0.2~beta3) package but:

```
# apt-cache policy libssl1.0.0
libssl1.0.0:
  Installed: 1.0.1t-1+deb8u6
  Candidate: 1.0.1t-1+deb8u6
  Version table:
 *** 1.0.1t-1+deb8u6 0
        500 http://mirrors.digitalocean.com/debian/ jessie/main i386 Packages
        500 http://security.debian.org/ jessie/updates/main i386 Packages
        100 /var/lib/dpkg/status

# apt-cache policy libssl1.0.2
libssl1.0.2:
  Installed: 1.0.2k-1+0~20170215143954.9+jessie~1.gbpecefd8
  Candidate: 1.0.2k-1+0~20170215143954.9+jessie~1.gbpecefd8
  Version table:
 *** 1.0.2k-1+0~20170215143954.9+jessie~1.gbpecefd8 0
       1001 https://packages.sury.org/php/ jessie/main i386 Packages
        100 /var/lib/dpkg/status
```
I think that you should update the control file of source package. You should depend on libssl1.0.2 instead of libssl1.0.0.

A fast fix/rebuild of the packages would be welcome as this issue affect all people installing our i-MSCP control panel under Debian Jessie (arch i386).

Thank you.

**Comment by oerdnj** [comment] 2017-07-10 19:48
Do you have jessie-backports enabled? Also what's output of `apt-cache policy php7.1-cli`?

**Comment by nuxwin** [comment] 2017-07-10 19:50
@oerdnj 

No. No backport enabled. Your package depends on libssl1.0.0 (1.0.2 beta) while it should depend on libssl1.0.2.
That issue only affect i386 arch.

**Comment by nuxwin** [comment] 2017-07-10 20:01
@oerdnj 

Hope this will be more clear for you:

```
# apt-cache policy php7.1-cli
php7.1-cli:i386:
  Installé : (aucun)
  Candidat : 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36
 Table de version :
     7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36 0
       1001 https://packages.sury.org/php/ jessie/main i386 Packages
```
```
Paquet : php7.1-cli                                     
Nouveau: oui
État: non installé
Version : 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36
Priorité : optionnel
Section : php
Responsable : Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture : i386
Taille décompressée : 3 997 k
Dépend: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36), php7.1-json, php7.1-opcache, php7.1-readline, tzdata, ucf,
         libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2~beta3), libxml2 (>= 2.8.0), zlib1g (>= 1:1.2.3.4)
Suggère: php-pear
Fournit: php-cli, phpapi-20160303
Description : command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Site : http://www.php.net/
```

**Comment by nuxwin** [comment] 2017-07-10 20:14
@oerdnj 

For the record, here is our xml file for package installation: https://github.com/i-MSCP/imscp/blob/1.4.x/autoinstaller/Packages/debian-jessie.xml#L118

**Comment by nuxwin** [comment] 2017-07-10 21:13
@oerdnj 

For the i386 architecture, the package depends on the `libssl1.0.0 (>= 1.0.2~beta3)` package which don't exist for that version.
```
root@jessie:/usr/local/src/imscp# LANG=C aptitude show php7.1-cli:i386
Package: php7.1-cli                      
New: yes
State: not installed
Version: 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36
Priority: optional
Section: php
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: i386
Uncompressed Size: 3997 k
Depends: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36), php7.1-json, php7.1-opcache, php7.1-readline, tzdata, ucf,
         libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2~beta3), libxml2 (>= 2.8.0), zlib1g (>= 1:1.2.3.4)
Suggests: php-pear
Conflicts: php7.1-cli
Provides: php-cli, phpapi-20160303
Description: command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Homepage: http://www.php.net/
```

For the `amd64` architecture, the package depends on the ```libssl1.0.2 (>= 1.0.2d)``` package which is provided by your repository.
```
root@jessie:/usr/local/src/imscp# LANG=C aptitude show php7.1-cli:amd64
Package: php7.1-cli                      
State: not installed
Version: 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36
Priority: optional
Section: php
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 3998 k
Depends: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36), php7.1-json, php7.1-opcache, php7.1-readline, tzdata, ucf,
         libc6 (>= 2.15), libssl1.0.2 (>= 1.0.2d), libxml2 (>= 2.8.0), zlib1g (>= 1:1.1.4)
Suggests: php-pear
Conflicts: php7.1-cli
Provides: php-cli, phpapi-20160303
Description: command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Homepage: http://www.php.net/
```

I think that whatever the architecture, your PHP package should depends on the `libssl1.0.2 (>= 1.0.2d)` package. This is also valable for the libapache2-mod-php7.1 package and so on...

This bug affects all PHP variants: `php5.6`, `php7.0` and `php7.1`.

**Comment by nuxwin** [comment] 2017-07-11 10:56
@oerdnj 

Note that for previous versions, the dependency was correct:

```
root@hosting:/var/www/imscp/gui/public/client# uname -a
Linux hosting 4.4.59-1-pve #1 SMP PVE 4.4.59-87 (Tue, 25 Apr 2017 09:01:58 +0200) i686 GNU/Linux

Linux hosting 4.4.59-1-pve #1 SMP PVE 4.4.59-87 (Tue, 25 Apr 2017 09:01:58 +0200) i686 GNU/Linux
root@hosting:/var/www/imscp/gui/public/client# aptitude show php7.1-cli
Paquet : php7.1-cli                                     
Nouveau: oui
État: non installé
Version : 7.1.6-1+0~20170609083833.26+jessie~1.gbpa2f43a
Priorité : optionnel
Section : php
Responsable : Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture : i386
Taille décompressée : 4 001 k
Dépend: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.6-1+0~20170609083833.26+jessie~1.gbpa2f43a), php7.1-json, php7.1-opcache, php7.1-readline, tzdata, ucf,
         libc6 (>= 2.15), libssl1.0.2 (>= 1.0.2d), libxml2 (>= 2.8.0), zlib1g (>= 1:1.2.3.4)
Suggère: php-pear
Fournit: php-cli, phpapi-20160303
Description : command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Site : http://www.php.net/
```
I assume that you made a change in your builder which cause the issue. Because, after updating APT index the dependency on libssl has changed and cannot be honored:
```
root@hosting:/var/www/imscp/gui/public/client# aptitude show php7.1-cli
Paquet : php7.1-cli                                     
Nouveau: oui
État: non installé
Version : 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36
Priorité : optionnel
Section : php
Responsable : Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture : i386
Taille décompressée : 3 997 k
Dépend: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36), php7.1-json, php7.1-opcache, php7.1-readline, tzdata, ucf,
         libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2~beta3), libxml2 (>= 2.8.0), zlib1g (>= 1:1.2.3.4)
Suggère: php-pear
Fournit: php-cli, phpapi-20160303
Description : command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Site : http://www.php.net/
```
That really a big issue for us... This bug break several servers.

Please stay us informed.

Thanks.

**Comment by oerdnj** [comment] 2017-07-11 12:09
This was caused by OpenSSL update in jessie-backports. Should be fixed in next recompile cycle.

**Comment by nuxwin** [comment] 2017-07-11 12:32
@oerdnj 

I hope so. Dependency is determinated via shlibs, right? If so, that is an issue from builder? I'm wondering why libssl-dev from the backports repository has been used. That weird, isn't it?

I'm really curious and I like to learn ;)

**Comment by oerdnj** [comment] 2017-07-11 15:16
@nuxwin Could you try now?

**Comment by nuxwin** [comment] 2017-07-11 19:06
@oerdnj 

Seem solved.

```
Package: php7.1-cli                      
New: yes
State: not installed
Version: 7.1.7.retag-1+0~20170711133844.5+jessie~1.gbp5284f4
Priority: optional
Section: php
Maintainer: Debian PHP Maintainers <pkg-php-maint@lists.alioth.debian.org>
Architecture: i386
Uncompressed Size: 4001 k
Depends: libedit2 (>= 2.11-20080614-4), libmagic1, libpcre3 (>= 1:8.20), mime-support, php7.1-common (= 7.1.7.retag-1+0~20170711133844.5+jessie~1.gbp5284f4), php7.1-json, php7.1-opcache, php7.1-readline, tzdata,
         ucf, libc6 (>= 2.15), libssl1.0.2 (>= 1.0.2d), libxml2 (>= 2.8.0), zlib1g (>= 1:1.2.3.4)
Suggests: php-pear
Provides: php-cli, phpapi-20160303
Description: command-line interpreter for the PHP scripting language
 This package provides the /usr/bin/php7.1 command interpreter, useful for testing PHP scripts from a shell or performing general shell scripting tasks. 
 
 The following extensions are built in: Core date filter hash libxml openssl pcntl pcre Reflection session SPL standard zlib. 
 
 PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.
Homepage: http://www.php.net/
```

**Closed** 2017-07-11 19:24 UTC
