### ISSUE TITLE
php7.3-fpm update breaks php7.3-fpm

### ISSUE THREAD

**Issue by arkantos80** [oerdnj/deb.sury.org#1339] opened 2020-02-11 23:15 UTC
php7.3-fpm amd64 7.3.14-6+ubuntu18.04.1+deb.sury.org

expects the pid file to now be in /var/run/php/ if it is not there but in the older /var/run/ folder
the update will crap out and bork fpm
while I like the the new file structure it would be nice to not have the update not break existing installs.  

Details
Get:20 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 php7.3-fpm amd64 7.3.14-6+ubuntu18.04.1+deb.sury.org+1 [1,391 kB]

Setting up php7.3-fpm (7.3.14-6+ubuntu18.04.1+deb.sury.org+1) ...
Errors were encountered while processing:
 php7.3-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1) 

service php7.3-fpm status
● php7.3-fpm.service - The PHP 7.3 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.3-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Tue 2020-02-11 15:51:16 MST; 25s ago
     Docs: man:php-fpm7.3(8)
 Main PID: 30969 (code=exited, status=0/SUCCESS)
   Status: "Processes active: 0, idle: 0, Requests: 0, slow: 0, Traffic: 0req/sec"

Feb 11 15:49:46  systemd[1]: Starting The PHP 7.3 FastCGI Process Manager...
Feb 11 15:49:46  update-alternatives[30983]: update-alternatives: error: alternative path /run/php/php7.3-fpm.sock doesn't exist
Feb 11 15:49:46  systemd[1]: php7.3-fpm.service: Can't open PID file /run/php/php7.3-fpm.pid (yet?) after start-post: No such file or directory
Feb 11 15:51:16  systemd[1]: php7.3-fpm.service: Start-post operation timed out. Stopping.
Feb 11 15:51:16 [1]: php7.3-fpm.service: Failed with result 'timeout'.
Feb 11 15:51:16  systemd[1]: Failed to start The PHP 7.3 FastCGI Process Manager.

update-alternatives --list php
/usr/bin/php7.3

cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

uname -a
Linux 4.15.0-1058-aws #60-Ubuntu SMP Wed Jan 15 22:35:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by arkantos80** [comment] 2020-02-11 23:19
perhaps I'm the only one with the issue.  I reconfigured my php-fpm.conf and pool.d/www.conf and nginx configs on all my servers to use the new socket and pid locations.  I have not had any issues with updates till this one.  I just thought this would be helpful if others had similar issues.

**Comment by oerdnj** [comment] 2020-02-12 05:10
This is duplicate of #1334

**Closed by oerdnj** 2020-02-12 05:10 UTC
