### ISSUE TITLE
touch: cannot touch '/run/php/php7.2-fpm.sock': No such file or directory

### ISSUE THREAD

**Issue by dweinerATL** [oerdnj/deb.sury.org#1328] opened 2020-02-01 18:01 UTC
**Unsupported distributions**
 - [X ] I'm *not* using [Ubuntu Trusty (14.04)](https://www.patreon.com/posts/private-ubuntu-30596045)

**Repository mirroring**
- [X ] I'm *not* trying to mirror the repositories using wget, curl, mozilla. If I am mirroring the packages.sury.org repository, I am properly using [rsync](https://www.patreon.com/posts/use-rsync-luke-32563640) to minimize the traffic.

While installing PHP7.2-fpm from the PPA, we get this error:

```
Setting up php7.2-fpm (7.2.27-3+ubuntu16.04.1+deb.sury.org+1) ...
touch: cannot touch '/run/php/php7.2-fpm.sock': No such file or directory
dpkg: error processing package php7.2-fpm (--configure):
 subprocess installed post-installation script returned error exit status 1
```

**Comment by oerdnj** [comment] 2020-02-01 18:04
duplicate of #1327 (just a different error message)

**Closed by oerdnj** 2020-02-01 18:04 UTC

**Comment by dweinerATL** [comment] 2020-02-01 18:06
@oerdnj It was a different version and I wasn't sure if you were aware.  Thanks!

**Comment by oerdnj** [comment] 2020-02-01 18:08
I know, I'll update the original bug to have more context.
