### ISSUE TITLE
Installing php-memcached installs all PHP versions

### ISSUE THREAD

**Issue by c-datculescu** [oerdnj/deb.sury.org#1466] opened 2020-10-11 08:44 UTC
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
When attempting to install php-memcached along with php 7.4, all php versions get installed. I have followed the documentation and i cannot get it to not install all php versions (5.6, 7.0, 7.1, 7.2, 7.3, 7.4 and 8.0rc).

**To Reproduce**
1. Run `apt-get install --no-install-recommends php7.4-json php-memcached`. The output looks like this on ubuntu bionic:
```
apt-get install --no-install-recommends php7.4-json php-memcached
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.4-json is already the newest version (7.4.11-2+ubuntu18.04.1+deb.sury.org+1).
php7.4-json set to manually installed.
The following packages were automatically installed and are no longer required:
  libpq5 librabbitmq4
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libmemcached11 php-igbinary php-msgpack php5.6-cli php5.6-common php5.6-json php5.6-msgpack php5.6-opcache php5.6-phpdbg php5.6-readline php7.0-cli php7.0-common php7.0-json php7.0-msgpack php7.0-opcache php7.0-phpdbg php7.0-readline php7.1-cli php7.1-common php7.1-json php7.1-msgpack php7.1-opcache php7.1-phpdbg
  php7.1-readline php7.2-cli php7.2-common php7.2-json php7.2-msgpack php7.2-opcache php7.2-phpdbg php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-msgpack php7.3-opcache php7.3-phpdbg php7.3-readline php7.4-msgpack php8.0-cli php8.0-common php8.0-msgpack php8.0-opcache php8.0-phpdbg php8.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  libmemcached11 php-igbinary php-memcached php-msgpack php5.6-cli php5.6-common php5.6-json php5.6-msgpack php5.6-opcache php5.6-phpdbg php5.6-readline php7.0-cli php7.0-common php7.0-json php7.0-msgpack php7.0-opcache php7.0-phpdbg php7.0-readline php7.1-cli php7.1-common php7.1-json php7.1-msgpack php7.1-opcache
  php7.1-phpdbg php7.1-readline php7.2-cli php7.2-common php7.2-json php7.2-msgpack php7.2-opcache php7.2-phpdbg php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-msgpack php7.3-opcache php7.3-phpdbg php7.3-readline php7.4-msgpack php8.0-cli php8.0-common php8.0-msgpack php8.0-opcache php8.0-phpdbg
  php8.0-readline
0 upgraded, 46 newly installed, 0 to remove and 12 not upgraded.
Need to get 25.3 MB/25.5 MB of archives.
After this operation, 101 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
2. Nothing changes even if using `apt-get install --no-install-recommends php7.4-json php7.4-memcached`
```
apt-get install --no-install-recommends php7.4-json php7.4-memcached
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php-memcached' instead of 'php7.4-memcached'
php7.4-json is already the newest version (7.4.11-2+ubuntu18.04.1+deb.sury.org+1).
php7.4-json set to manually installed.
The following packages were automatically installed and are no longer required:
  libpq5 librabbitmq4
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  libmemcached11 php-igbinary php-msgpack php5.6-cli php5.6-common php5.6-json php5.6-msgpack php5.6-opcache php5.6-phpdbg php5.6-readline php7.0-cli php7.0-common php7.0-json php7.0-msgpack php7.0-opcache php7.0-phpdbg php7.0-readline php7.1-cli php7.1-common php7.1-json php7.1-msgpack php7.1-opcache php7.1-phpdbg
  php7.1-readline php7.2-cli php7.2-common php7.2-json php7.2-msgpack php7.2-opcache php7.2-phpdbg php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-msgpack php7.3-opcache php7.3-phpdbg php7.3-readline php7.4-msgpack php8.0-cli php8.0-common php8.0-msgpack php8.0-opcache php8.0-phpdbg php8.0-readline
Suggested packages:
  php-pear
The following NEW packages will be installed:
  libmemcached11 php-igbinary php-memcached php-msgpack php5.6-cli php5.6-common php5.6-json php5.6-msgpack php5.6-opcache php5.6-phpdbg php5.6-readline php7.0-cli php7.0-common php7.0-json php7.0-msgpack php7.0-opcache php7.0-phpdbg php7.0-readline php7.1-cli php7.1-common php7.1-json php7.1-msgpack php7.1-opcache
  php7.1-phpdbg php7.1-readline php7.2-cli php7.2-common php7.2-json php7.2-msgpack php7.2-opcache php7.2-phpdbg php7.2-readline php7.3-cli php7.3-common php7.3-json php7.3-msgpack php7.3-opcache php7.3-phpdbg php7.3-readline php7.4-msgpack php8.0-cli php8.0-common php8.0-msgpack php8.0-opcache php8.0-phpdbg
  php8.0-readline
0 upgraded, 46 newly installed, 0 to remove and 12 not upgraded.
Need to get 25.3 MB/25.5 MB of archives.
After this operation, 101 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Expected behavior**
This should only install the usual php 7.4 packages.

**Distribution (please complete the following information):**
 - OS: Ubuntu (multiple versions tested, from xenial to focal)
 - Architecture: amd64
 - Repository: Ubuntu PPA

**Package(s) (please complete the following information):**
```
apt-cache policy php-memcached
php-memcached:
  Installed: (none)
  Candidate: 3.1.4+2.2.0-1+ubuntu18.04.1+deb.sury.org+20191129
  Version table:
     3.1.4+2.2.0-1+ubuntu18.04.1+deb.sury.org+20191129 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
     3.0.1+2.2.0-1build2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Additional context**
This is happening since yesterday (10 October 2020). Previously we didnt see this behavior.

**Comment by oerdnj** [comment] 2020-10-11 10:04
Duplicate of #1465

**Closed by oerdnj** 2020-10-11 10:04 UTC
