### ISSUE TITLE
Xdebug config files are not written

### ISSUE THREAD

**Issue by vkosachev** [oerdnj/deb.sury.org#283] opened 2016-03-02 13:46 UTC
Seems that latest update brought following change:
On fresh install php7.0 + php-xdebug, the php-xdebug does not create the xdebug.ini file in
 `/etc/php/7.0/mods-available/`
This way it cannot be enabled via `phpenmod`.
Manually adding the `xdebug.ini` file solves the issue.

**Comment by oerdnj** [comment] 2016-03-02 15:16
Do you have anything in apt.log? Because I am quite positive that the package contains /etc/php/7.0/mods-available/xdebug.ini:

```
$ dpkg-deb -c php-xdebug_2.4.0~rc4-2+deb.sury.org~trusty+3_amd64.deb 
drwxr-xr-x root/root         0 2016-03-01 17:34 ./
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/php/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/php/7.0/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/php/7.0/mods-available/
-rw-r--r-- root/root        25 2016-03-01 17:34 ./etc/php/7.0/mods-available/xdebug.ini
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/php/5.6/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./etc/php/5.6/mods-available/
-rw-r--r-- root/root        25 2016-03-01 17:34 ./etc/php/5.6/mods-available/xdebug.ini
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/lib/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/lib/php/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/lib/php/20151012/
-rw-r--r-- root/root   1187908 2016-03-01 17:34 ./usr/lib/php/20151012/xdebug.so
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/lib/php/20131226/
-rw-r--r-- root/root   1153495 2016-03-01 17:34 ./usr/lib/php/20131226/xdebug.so
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/share/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/share/doc/
drwxr-xr-x root/root         0 2016-03-01 17:34 ./usr/share/doc/php-xdebug/
-rw-r--r-- root/root      7860 2016-02-29 22:35 ./usr/share/doc/php-xdebug/copyright
-rw-r--r-- root/root      1514 2016-03-01 17:12 ./usr/share/doc/php-xdebug/changelog.Debian.gz
```

**Comment by vkosachev** [comment] 2016-03-03 09:48
Yes, the log in the `/var/log/apt/term.log` showed following message
`'Setting up php-xdebug (2.4.0~rc4-2+deb.sury.org~trusty+3) ...
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available'`

This gave me a hint what can help solve the issue.

However, the `dpkg.log` and `history.log` contain no error messages:

**dpkg.log**
`2016-03-02 14:23:04 configure php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3 <none>
2016-03-02 14:23:04 status unpacked php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3
2016-03-02 14:23:04 status unpacked php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3
2016-03-02 14:23:04 status unpacked php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3
2016-03-02 14:23:04 status half-configured php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3
2016-03-02 14:23:04 status installed php-xdebug:amd64 2.4.0~rc4-2+deb.sury.org~trusty+3`

**history.log**
`Start-Date: 2016-03-02  14:22:33
Commandline: /usr/sbin/synaptic
Install: php7.0-json:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-pgsql:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-cli:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-common:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-sqlite3:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-odbc:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-mcrypt:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-intl:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-gd:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-mysql:amd64 (7.0.3-13+deb.sury.org~trusty+1), php-imagick:amd64 (3.4.0~rc6-2+deb.sury.org~trusty+3), php7.0-zip:amd64 (7.0.3-13+deb.sury.org~trusty+1), php-xdebug:amd64 (2.4.0~rc4-2+deb.sury.org~trusty+3), php7.0-soap:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-ldap:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-curl:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-fpm:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-opcache:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-mbstring:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0:amd64 (7.0.3-13+deb.sury.org~trusty+1), php7.0-readline:amd64 (7.0.3-13+deb.sury.org~trusty+1, automatic), php7.0-xml:amd64 (7.0.3-13+deb.sury.org~trusty+1), libapache2-mod-php7.0:amd64 (7.0.3-13+deb.sury.org~trusty+1)
End-Date: 2016-03-02  14:23:17`

**Comment by oerdnj** [comment] 2016-03-03 09:58
Anything earlier in the term.log?

I can't reproduce the bug, since it just works here:
```
Setting up php7.0-cli (7.0.4~rc1-2+deb.sury.org~trusty+3) ...
update-alternatives: using /usr/bin/php7.0 to provide /usr/bin/php (php) in auto mode
update-alternatives: using /usr/bin/phar7.0 to provide /usr/bin/phar (phar) in auto mode
update-alternatives: using /usr/bin/phar.phar7.0 to provide /usr/bin/phar.phar (phar.phar) in auto mode

Creating config file /etc/php/7.0/cli/php.ini with new version
Setting up php-cli (1:7.0+35+deb.sury.org~trusty+1) ...
Setting up php-xdebug (2.4.0~rc4-2+deb.sury.org~trusty+5) ...
root@lettie:~# ls -l /etc/php/7.0/mods-available/xdebug.ini 
-rw-r--r-- 1 root root 25 Mar  2 18:27 /etc/php/7.0/mods-available/xdebug.ini
```

**Comment by vkosachev** [comment] 2016-03-03 10:14
No, that is all

**Comment by oerdnj** [comment] 2016-03-03 10:19
And it happens to you on every clean install?

E.g.: `apt-get purge php-xdebug` && `apt-get install php-xdebug`?

**Comment by vkosachev** [comment] 2016-03-03 12:07
Today I noticed an update to the xdebug module. Now it seems to be creating the file. But I get warnings on `apt-get purge php-xdebug` : 


```
The following packages will be REMOVED:
  php-xdebug*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 2,420 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 549172 files and directories currently installed.)
Removing php-xdebug (2.4.0~rc4-2+deb.sury.org~trusty+4) ...
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
php_invoke prerm: Disabled module xdebug for PHP 7.0 apache2 SAPI
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
php_invoke prerm: Disabled module xdebug for PHP 7.0 fpm SAPI
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
php_invoke prerm: Disabled module xdebug for PHP 7.0 cli SAPI
Purging configuration files for php-xdebug (2.4.0~rc4-2+deb.sury.org~trusty+4) ...
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
WARNING: Module xdebug ini file doesn't exist under /etc/php/7.0/mods-available
Reading package lists... Done

**Comment by oerdnj** [comment] 2016-03-03 12:12
The warning should be fixed in the next update that has been already queued.

The fix landed in dh-php_0.10, but all external extensions needs to be rebuild to catch up.

**Comment by vkosachev** [comment] 2016-03-03 12:16
Great! Thanks for your awesome ppa :+1:

**Comment by oerdnj** [comment] 2016-03-03 12:20
So I guess since it looks like it's fixed for you, I could close this bug.

**Closed by oerdnj** 2016-03-03 12:20 UTC
Labels: moreinfo
