### ISSUE TITLE
Why is it practical to have update-alternatives for php / php-config / phpize seperated

### ISSUE THREAD

**Issue by EugenMayer** [oerdnj/deb.sury.org#404] opened 2016-07-02 09:00 UTC
Follow up to  #403 just to understand, why it makes sense to seperate those alternatives. Switching either of those without the other always leads to (non trivial, hard to guess) issues.

Is it seperated because phpX-dev can be installed, or not? (modular) so its just packaging thing?

kudos for the new layout with /etc/php/X.Y/ so much more convenient!

**Comment by oerdnj** [comment] 2016-07-02 09:16
Duplicate of #351 and also already explained there.

**Closed** 2016-07-02 09:16 UTC
