### ISSUE TITLE
PHP8.1 ZTS support for parallel extension

### ISSUE THREAD

**Issue by lolcatw** [oerdnj/deb.sury.org#1794] opened 2022-06-18 20:47 UTC
**Frequently asked questions**

- [x] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Is your feature request related to a problem? Please describe.**
 - Yes. I would like to use the "parallel" extension on my PHP8 install. [(this thing!)](https://www.php.net/manual/en/intro.parallel.php)
There are a few issues with using this though. First of all, ZTS needs to be enabled. As you may already know, to enable this, I need this post build, build argument (`--enable-zts`) to compile the PHP binary. The issue I'm facing is that I don't know what arguments I should use alongside that to get a build equivalent to the one found on sury.org. Answers on stackoverflow merely tell me to just throw that flag to the build script, but it's clear to me that this isn't the only extension you need to work with PHP. For example, socket support.

**Describe the solution you'd like**
 - An update of the PHP8.1 package with ZTS support.

**Describe alternatives you've considered**
 - Building it myself, but I think many people out there would benefit from a pre-built package for this use case. The only reason I'm upgrading to PHP8 is because this extension requires PHP8 to work, apparently. Despite the introduction page saying it is compatible for PHP 7.2+, I encountered errors regarding my PHP version while installing the extension.

**Additional context**
 - Please let me know if I've been unclear with something. Many thanks :b

**Comment by attisan** [comment] 2022-06-22 06:32
Would love this feature too as I would like to try using amphp parallel with - well, "parallel" instead of relying in shell.

**Comment by oerdnj** [comment] 2022-06-25 07:47
This is duplicate of #327

**Closed by oerdnj** 2022-06-25 07:47 UTC

**Comment by michael-rubel** [comment] 2023-10-21 14:38
If you need ZTS mode and a `parallel` extension, Remi has all the candies ready.
https://github.com/krakjoe/parallel/issues/18
