### ISSUE TITLE
[php-7.0] request for extension xhprof

### ISSUE THREAD

**Issue by basz** [oerdnj/deb.sury.org#175] opened 2015-12-14 14:37 UTC
https://github.com/phacility/xhprof

**Comment by oerdnj** [comment] 2015-12-17 11:37
I very much doubt there's a support for PHP 7.0:
> committed on Feb 26

**Comment by LAV45** [comment] 2015-12-19 19:08
:+1:

**Comment by oerdnj** [comment] 2015-12-20 07:18
Folks, please don't :+1: unless there's an upstream version of the extension that supports PHP7 so I could actually package anything. I will package it when there's something to package, so +1 here is just noise.

**Comment by robfrawley** [comment] 2016-02-05 16:28
This doesn't look particularly promising. For reference, see: https://github.com/phacility/xhprof/issues/73

**Comment by lornajane** [comment] 2016-02-07 14:59
A better alternative would be https://github.com/tideways/php-profiler-extension which does more or less the same thing as xhprof but is actively maintained - for example XHGui can use either of them as a backend (see https://github.com/perftools/xhgui).  Tideways is ready for PHP 7.

**Comment by oerdnj** [comment] 2016-02-18 11:07
@lornajane Could you please open a separate issue for packaging tideways php-profiler? I'll keep this open in case xhprof wil get the support in due time.

**Comment by lornajane** [comment] 2016-02-29 16:25
No problem!  The new issue is #278

**Comment by oerdnj** [comment] 2016-03-01 14:45
JFTR tideways has been packaged, so this will probably end us wontfix bug.

**Comment by mike503** [comment] 2016-05-13 04:35
Currently there isn't a proper "cross-version" xhprof that is in the repo.

"php5-xhprof" only puts the .ini files in php 5.5 (but pecl install xhprof works, so I believe it could also supply the 5.6 ini files in the package and "just work"), i.e. this worked, but is a little cludgy. I love having a repo to go against, and have donated towards the cause in the past too. :)

```
pecl install channel://pecl.php.net/xhprof-0.9.4
echo "extension=xhprof.so" > /etc/php/5.6/mods-available/xhprof.ini
```

when I tried "php-xhprof" it suggested the commercial tideways. I would rather it NOT install an extension that has requires paying attached to it to use. Just tell me "no match" - if people want tideways, that's great, but keep it separate. Or, if there is a way to have the apt command just *say* a suggestion, that'd be tolerable.

```
root@ip-10-0-3-13:~# apt-get install php-xhprof
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php-tideways' instead of 'php-xhprof'
```

**Comment by oerdnj** [comment] 2016-05-13 07:13
@mike503 My understanding was that tideways can be used without paying anything. But perhaps I am wrong.

I'll strip php-xhprof provides from `tideways` and I now might prepare xhprof for PHP 5.x, as it can be done with updated dh-php.

**Comment by mike503** [comment] 2016-05-13 07:27
It looks like they have a limited time trial only

**Comment by oerdnj** [comment] 2016-05-13 07:47
Ok, `php-xhprof` for PHP 5.x has been upload to the repository. I'll add PHP 7.0 support when there's working PHP 7.0 branch somewhere...

**Closed by oerdnj** 2016-05-13 07:47 UTC
Labels: upstream

**Comment by lornajane** [comment] 2016-05-13 08:57
I believe that the extension for tideways does not require payment.  If you want to use their web interface, then that does require a subscription, but the tideways PHP extension can be installed and used as a replacement for XHProf for any of the XHProf-compatible frontends.

**Comment by mike503** [comment] 2016-05-13 09:04
okay, so they're upselling their web interface hard, which is basically xhprof-as-a-service with a really nice UI; otherwise it will generate the same dumps as xhprof used to? in that case, maybe it is an okay option.

It took me clicking around quick to see if it talks about running it locally. It looks like they hint at not using their platform here. But they sure don't really talk about it much. :)
https://github.com/tideways/php-profiler-extension

**Comment by mike503** [comment] 2016-05-13 20:51
After reviewing and seeing this URL:
https://tideways.io/profiler/xhprof-for-php7-php5.6

Yes, I guess it is a modern fork of it. Although I think it is still not okay to force install a package that was not requested (and tideways is not directly compatible with xhprof... you have to use tideways_* functions to call the profiler) - so I was wrong in the sense it was purely a cloud service, but do maintain it shouldn't be force installed when requesting xhprof. Merely suggested. So removing the "provides" is good.
