### ISSUE TITLE
Problem when update environment with php 7.2 in Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by dundee-81** [oerdnj/deb.sury.org#1341] opened 2020-02-15 09:47 UTC
**Describe the bug**
Update of following packages gives an error message and leaves packages not configured.

List of affected packages:
 php7.2-cli
 libapache2-mod-php7.2
 php7.2-dev
 php7.2-fpm
 php7.2

Error message:
Package configuration php7.2-cli (7.2.27-6+ubuntu18.04.1+deb.sury.org+1) ...
ucfr: Attempt from package php7.2-cli  to take /etc/php/7.2/apache2/php.ini away from package libapache2-mod-php7.2
ucfr: Aborting

**To Reproduce**
1. apt update
2. apt upgrade

**Expected behavior**
Updating packages to the latest versions

**Distribution (please complete the following information):**
 - Ubuntu 18.04.4 LTS
 - x86_64
 - Repository: ondrej/php, ondrej/apache2

**Comment by oerdnj** [comment] 2020-02-15 12:18
That’s very weird. Can you paste the contents of `/var/lib/dpkg/info/php7.2-cli.postinst` from the affected system?

**Comment by oerdnj** [comment] 2020-02-15 12:25
I am pretty much sure this bug is caused by something you did to your system. Any symlinks in `/etc/php` that are not there?  Do `ls -lR /etc/php` and paste the output here.

The package maintainer scripts (postinst, postrm, prerm) are all correct, I have just checked, so I am closing this bug.

**Closed by oerdnj** 2020-02-15 12:25 UTC

**Comment by jpschewe** [comment] 2020-04-26 13:20
I have this same problem.

/var/lib/dpkg/info/php7.2-cli.postinst
```
#!/bin/sh                                              
      
set -e                     

if [ "$1" = "configure" ]; then                        
    for binary in php phar phar.phar; do     
        update-alternatives \
            --install /usr/bin/${binary} ${binary} /usr/bin/${binary}7.2 72 \
            --slave /usr/share/man/man1/${binary}.1.gz ${binary}.1.gz /usr/share/man/man1/${binary}7.2.1.gz
    done                                 
fi          
      
CONFDIR=/etc/php/7.2/cli/conf.d
                                                                      
if [ "$1" = "configure" ]; then                      
    phpini="/etc/php/7.2/cli/php.ini"
  
    if [ "cli" = "cli" ]; then
        ucf /usr/lib/php/7.2/php.ini-production.cli $phpini
    else
        ucf /usr/lib/php/7.2/php.ini-production $phpini
    fi
    ucfr php7.2-cli $phpini
                                        
    if [ -e /usr/lib/php/php-maintscript-helper ]; then
        . /usr/lib/php/php-maintscript-helper

        mods=$(phpquery -M -v 7.2)
        for mod in $mods; do
            php_invoke enmod 7.2 cli $mod
        done
    fi

    if [ -n "$2" ] && dpkg --compare-versions "$2" lt "7.0.3-2~"; then
        rm -f /etc/php/7.2/cli/conf.d/20-opcache.ini;
    fi
fi



exit 0
```

ls -lR /etc/php
```
/etc/php:
total 4
drwxr-xr-x 6 root root 4096 Jun 18  2019 7.2/

/etc/php/7.2:
total 16
drwxr-xr-x 3 root root 4096 Apr  4 20:02 apache2/
drwxr-xr-x 3 root root 4096 Oct 29 06:24 cli/
drwxr-xr-x 4 root root 4096 Apr 16 06:26 fpm/
drwxr-xr-x 2 root root 4096 Oct 22  2019 mods-available/

/etc/php/7.2/apache2:
total 76
drwxr-xr-x 2 root root  4096 Oct 22  2019 conf.d/
lrwxrwxrwx 1 root root    14 Apr  4 20:02 php.ini -> ../fpm/php.ini
-rw-r--r-- 1 root root 71817 Oct 28 08:07 php.ini.dist

/etc/php/7.2/apache2/conf.d:
total 0
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-mysqlnd.ini -> /etc/php/7.2/mods-available/mysqlnd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-opcache.ini -> /etc/php/7.2/mods-available/opcache.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 10-pdo.ini -> /etc/php/7.2/mods-available/pdo.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 15-xml.ini -> /etc/php/7.2/mods-available/xml.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-calendar.ini -> /etc/php/7.2/mods-available/calendar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-ctype.ini -> /etc/php/7.2/mods-available/ctype.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-curl.ini -> /etc/php/7.2/mods-available/curl.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-dom.ini -> /etc/php/7.2/mods-available/dom.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-exif.ini -> /etc/php/7.2/mods-available/exif.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-fileinfo.ini -> /etc/php/7.2/mods-available/fileinfo.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-ftp.ini -> /etc/php/7.2/mods-available/ftp.ini
lrwxrwxrwx 1 root root 34 Jun 18  2019 20-gd.ini -> /etc/php/7.2/mods-available/gd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-gettext.ini -> /etc/php/7.2/mods-available/gettext.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-iconv.ini -> /etc/php/7.2/mods-available/iconv.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-imagick.ini -> /etc/php/7.2/mods-available/imagick.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-intl.ini -> /etc/php/7.2/mods-available/intl.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-json.ini -> /etc/php/7.2/mods-available/json.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-mbstring.ini -> /etc/php/7.2/mods-available/mbstring.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-mysqli.ini -> /etc/php/7.2/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_mysql.ini -> /etc/php/7.2/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_pgsql.ini -> /etc/php/7.2/mods-available/pdo_pgsql.ini
lrwxrwxrwx 1 root root 42 Oct 22  2019 20-pdo_sqlite.ini -> /etc/php/7.2/mods-available/pdo_sqlite.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-pgsql.ini -> /etc/php/7.2/mods-available/pgsql.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-phar.ini -> /etc/php/7.2/mods-available/phar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-posix.ini -> /etc/php/7.2/mods-available/posix.ini
lrwxrwxrwx 1 root root 38 Oct 22  2019 20-pspell.ini -> /etc/php/7.2/mods-available/pspell.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-readline.ini -> /etc/php/7.2/mods-available/readline.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-shmop.ini -> /etc/php/7.2/mods-available/shmop.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-simplexml.ini -> /etc/php/7.2/mods-available/simplexml.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sockets.ini -> /etc/php/7.2/mods-available/sockets.ini
lrwxrwxrwx 1 root root 39 Oct 22  2019 20-sqlite3.ini -> /etc/php/7.2/mods-available/sqlite3.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvmsg.ini -> /etc/php/7.2/mods-available/sysvmsg.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvsem.ini -> /etc/php/7.2/mods-available/sysvsem.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvshm.ini -> /etc/php/7.2/mods-available/sysvshm.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-tokenizer.ini -> /etc/php/7.2/mods-available/tokenizer.ini
lrwxrwxrwx 1 root root 36 Jun 28  2019 20-wddx.ini -> /etc/php/7.2/mods-available/wddx.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-xdebug.ini -> /etc/php/7.2/mods-available/xdebug.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlreader.ini -> /etc/php/7.2/mods-available/xmlreader.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlwriter.ini -> /etc/php/7.2/mods-available/xmlwriter.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-xsl.ini -> /etc/php/7.2/mods-available/xsl.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-zip.ini -> /etc/php/7.2/mods-available/zip.ini

/etc/php/7.2/cli:
total 220
drwxr-xr-x 2 root root  4096 Oct 22  2019 conf.d/
-rw-r--r-- 1 root root 71519 Jun 18  2019 php.ini
-rw-r--r-- 1 root root 71429 Oct 28 08:07 php.ini.ucf-dist
-rw-r--r-- 1 root root 71520 Jun  4  2019 php.ini.~1~

/etc/php/7.2/cli/conf.d:
total 0
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-mysqlnd.ini -> /etc/php/7.2/mods-available/mysqlnd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-opcache.ini -> /etc/php/7.2/mods-available/opcache.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 10-pdo.ini -> /etc/php/7.2/mods-available/pdo.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 15-xml.ini -> /etc/php/7.2/mods-available/xml.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-calendar.ini -> /etc/php/7.2/mods-available/calendar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-ctype.ini -> /etc/php/7.2/mods-available/ctype.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-curl.ini -> /etc/php/7.2/mods-available/curl.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-dom.ini -> /etc/php/7.2/mods-available/dom.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-exif.ini -> /etc/php/7.2/mods-available/exif.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-fileinfo.ini -> /etc/php/7.2/mods-available/fileinfo.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-ftp.ini -> /etc/php/7.2/mods-available/ftp.ini
lrwxrwxrwx 1 root root 34 Jun 18  2019 20-gd.ini -> /etc/php/7.2/mods-available/gd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-gettext.ini -> /etc/php/7.2/mods-available/gettext.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-iconv.ini -> /etc/php/7.2/mods-available/iconv.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-imagick.ini -> /etc/php/7.2/mods-available/imagick.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-intl.ini -> /etc/php/7.2/mods-available/intl.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-json.ini -> /etc/php/7.2/mods-available/json.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-mbstring.ini -> /etc/php/7.2/mods-available/mbstring.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-mysqli.ini -> /etc/php/7.2/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_mysql.ini -> /etc/php/7.2/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_pgsql.ini -> /etc/php/7.2/mods-available/pdo_pgsql.ini
lrwxrwxrwx 1 root root 42 Oct 22  2019 20-pdo_sqlite.ini -> /etc/php/7.2/mods-available/pdo_sqlite.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-pgsql.ini -> /etc/php/7.2/mods-available/pgsql.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-phar.ini -> /etc/php/7.2/mods-available/phar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-posix.ini -> /etc/php/7.2/mods-available/posix.ini
lrwxrwxrwx 1 root root 38 Oct 22  2019 20-pspell.ini -> /etc/php/7.2/mods-available/pspell.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-readline.ini -> /etc/php/7.2/mods-available/readline.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-shmop.ini -> /etc/php/7.2/mods-available/shmop.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-simplexml.ini -> /etc/php/7.2/mods-available/simplexml.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sockets.ini -> /etc/php/7.2/mods-available/sockets.ini
lrwxrwxrwx 1 root root 39 Oct 22  2019 20-sqlite3.ini -> /etc/php/7.2/mods-available/sqlite3.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvmsg.ini -> /etc/php/7.2/mods-available/sysvmsg.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvsem.ini -> /etc/php/7.2/mods-available/sysvsem.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvshm.ini -> /etc/php/7.2/mods-available/sysvshm.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-tokenizer.ini -> /etc/php/7.2/mods-available/tokenizer.ini
lrwxrwxrwx 1 root root 36 Jun 28  2019 20-wddx.ini -> /etc/php/7.2/mods-available/wddx.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-xdebug.ini -> /etc/php/7.2/mods-available/xdebug.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlreader.ini -> /etc/php/7.2/mods-available/xmlreader.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlwriter.ini -> /etc/php/7.2/mods-available/xmlwriter.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-xsl.ini -> /etc/php/7.2/mods-available/xsl.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-zip.ini -> /etc/php/7.2/mods-available/zip.ini

/etc/php/7.2/fpm:
total 304
drwxr-xr-x 2 root root  4096 Oct 22  2019 conf.d/
-rw-r--r-- 1 root root  4424 Jun  4  2019 php-fpm.conf
-rw-r--r-- 1 root root 72146 Apr  4 20:02 php.ini
-rw-r--r-- 1 root root 71817 Oct 28 08:07 php.ini.ucf-dist
-rw-r--r-- 1 root root 71908 Jun  4  2019 php.ini.~1~
-rw-r--r-- 1 root root 72118 Oct 22  2019 php.ini.~4~
drwxr-xr-x 2 root root  4096 Apr 16 06:26 pool.d/

/etc/php/7.2/fpm/conf.d:
total 0
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-mysqlnd.ini -> /etc/php/7.2/mods-available/mysqlnd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 10-opcache.ini -> /etc/php/7.2/mods-available/opcache.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 10-pdo.ini -> /etc/php/7.2/mods-available/pdo.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 15-xml.ini -> /etc/php/7.2/mods-available/xml.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-calendar.ini -> /etc/php/7.2/mods-available/calendar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-ctype.ini -> /etc/php/7.2/mods-available/ctype.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-curl.ini -> /etc/php/7.2/mods-available/curl.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-dom.ini -> /etc/php/7.2/mods-available/dom.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-exif.ini -> /etc/php/7.2/mods-available/exif.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-fileinfo.ini -> /etc/php/7.2/mods-available/fileinfo.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-ftp.ini -> /etc/php/7.2/mods-available/ftp.ini
lrwxrwxrwx 1 root root 34 Jun 18  2019 20-gd.ini -> /etc/php/7.2/mods-available/gd.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-gettext.ini -> /etc/php/7.2/mods-available/gettext.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-iconv.ini -> /etc/php/7.2/mods-available/iconv.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-imagick.ini -> /etc/php/7.2/mods-available/imagick.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-intl.ini -> /etc/php/7.2/mods-available/intl.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-json.ini -> /etc/php/7.2/mods-available/json.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-mbstring.ini -> /etc/php/7.2/mods-available/mbstring.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-mysqli.ini -> /etc/php/7.2/mods-available/mysqli.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_mysql.ini -> /etc/php/7.2/mods-available/pdo_mysql.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-pdo_pgsql.ini -> /etc/php/7.2/mods-available/pdo_pgsql.ini
lrwxrwxrwx 1 root root 42 Oct 22  2019 20-pdo_sqlite.ini -> /etc/php/7.2/mods-available/pdo_sqlite.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-pgsql.ini -> /etc/php/7.2/mods-available/pgsql.ini
lrwxrwxrwx 1 root root 36 Jun 18  2019 20-phar.ini -> /etc/php/7.2/mods-available/phar.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-posix.ini -> /etc/php/7.2/mods-available/posix.ini
lrwxrwxrwx 1 root root 38 Oct 22  2019 20-pspell.ini -> /etc/php/7.2/mods-available/pspell.ini
lrwxrwxrwx 1 root root 40 Jun 18  2019 20-readline.ini -> /etc/php/7.2/mods-available/readline.ini
lrwxrwxrwx 1 root root 37 Jun 18  2019 20-shmop.ini -> /etc/php/7.2/mods-available/shmop.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-simplexml.ini -> /etc/php/7.2/mods-available/simplexml.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sockets.ini -> /etc/php/7.2/mods-available/sockets.ini
lrwxrwxrwx 1 root root 39 Oct 22  2019 20-sqlite3.ini -> /etc/php/7.2/mods-available/sqlite3.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvmsg.ini -> /etc/php/7.2/mods-available/sysvmsg.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvsem.ini -> /etc/php/7.2/mods-available/sysvsem.ini
lrwxrwxrwx 1 root root 39 Jun 18  2019 20-sysvshm.ini -> /etc/php/7.2/mods-available/sysvshm.ini
lrwxrwxrwx 1 root root 41 Jun 18  2019 20-tokenizer.ini -> /etc/php/7.2/mods-available/tokenizer.ini
lrwxrwxrwx 1 root root 36 Jun 28  2019 20-wddx.ini -> /etc/php/7.2/mods-available/wddx.ini
lrwxrwxrwx 1 root root 38 Jun 18  2019 20-xdebug.ini -> /etc/php/7.2/mods-available/xdebug.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlreader.ini -> /etc/php/7.2/mods-available/xmlreader.ini
lrwxrwxrwx 1 root root 41 Jun 28  2019 20-xmlwriter.ini -> /etc/php/7.2/mods-available/xmlwriter.ini
lrwxrwxrwx 1 root root 35 Jun 28  2019 20-xsl.ini -> /etc/php/7.2/mods-available/xsl.ini
lrwxrwxrwx 1 root root 35 Jun 18  2019 20-zip.ini -> /etc/php/7.2/mods-available/zip.ini

/etc/php/7.2/fpm/pool.d:
total 20
-rw-r--r-- 1 root root 18860 Apr  4 13:54 www.conf

/etc/php/7.2/mods-available:
total 164
-rw-r--r-- 1 root root 74 Jun  4  2019 calendar.ini
-rw-r--r-- 1 root root 71 Jun  4  2019 ctype.ini
-rw-r--r-- 1 root root 68 Jun  4  2019 curl.ini
-rw-r--r-- 1 root root 66 Jun  4  2019 dom.ini
-rw-r--r-- 1 root root 70 Jun  4  2019 exif.ini
-rw-r--r-- 1 root root 74 Jun  4  2019 fileinfo.ini
-rw-r--r-- 1 root root 69 Jun  4  2019 ftp.ini
-rw-r--r-- 1 root root 64 Jun  4  2019 gd.ini
-rw-r--r-- 1 root root 73 Jun  4  2019 gettext.ini
-rw-r--r-- 1 root root 71 Jun  4  2019 iconv.ini
-rw-r--r-- 1 root root 60 Feb  2  2018 imagick.ini
-rw-r--r-- 1 root root 68 Jun  4  2019 intl.ini
-rw-r--r-- 1 root root 68 Jun  4  2019 json.ini
-rw-r--r-- 1 root root 76 Jun  4  2019 mbstring.ini
-rw-r--r-- 1 root root 71 Jun  4  2019 mysqli.ini
-rw-r--r-- 1 root root 72 Jun  4  2019 mysqlnd.ini
-rw-r--r-- 1 root root 79 Jun  4  2019 opcache.ini
-rw-r--r-- 1 root root 69 Jun  4  2019 pdo.ini
-rw-r--r-- 1 root root 74 Jun  4  2019 pdo_mysql.ini
-rw-r--r-- 1 root root 74 Jun  4  2019 pdo_pgsql.ini
-rw-r--r-- 1 root root 77 Aug 12  2019 pdo_sqlite.ini
-rw-r--r-- 1 root root 70 Jun  4  2019 pgsql.ini
-rw-r--r-- 1 root root 70 Jun  4  2019 phar.ini
-rw-r--r-- 1 root root 71 Jun  4  2019 posix.ini
-rw-r--r-- 1 root root 72 Aug 12  2019 pspell.ini
-rw-r--r-- 1 root root 76 Jun  4  2019 readline.ini
-rw-r--r-- 1 root root 71 Jun  4  2019 shmop.ini
-rw-r--r-- 1 root root 72 Jun  4  2019 simplexml.ini
-rw-r--r-- 1 root root 73 Jun  4  2019 sockets.ini
-rw-r--r-- 1 root root 74 Aug 12  2019 sqlite3.ini
-rw-r--r-- 1 root root 73 Jun  4  2019 sysvmsg.ini
-rw-r--r-- 1 root root 73 Jun  4  2019 sysvsem.ini
-rw-r--r-- 1 root root 73 Jun  4  2019 sysvshm.ini
-rw-r--r-- 1 root root 75 Jun  4  2019 tokenizer.ini
-rw-r--r-- 1 root root 67 Jun  4  2019 wddx.ini
-rw-r--r-- 1 root root 25 Feb  1  2018 xdebug.ini
-rw-r--r-- 1 root root 66 Jun  4  2019 xml.ini
-rw-r--r-- 1 root root 72 Jun  4  2019 xmlreader.ini
-rw-r--r-- 1 root root 72 Jun  4  2019 xmlwriter.ini
-rw-r--r-- 1 root root 66 Jun  4  2019 xsl.ini
-rw-r--r-- 1 root root 66 Jun  4  2019 zip.ini
```

apt list --installed '*php*'
```
Listing...
libapache2-mod-php/bionic,now 1:7.2+60ubuntu1 all [installed]
libapache2-mod-php7.2/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php/bionic,now 1:7.2+60ubuntu1 all [installed]
php-auth-sasl/bionic,now 1.0.6-3 all [installed,automatic]
php-common/bionic,now 1:60ubuntu1 all [installed,automatic]
php-curl/bionic,now 1:7.2+60ubuntu1 all [installed]
php-fpm/bionic,now 1:7.2+60ubuntu1 all [installed]
php-gd/bionic,now 1:7.2+60ubuntu1 all [installed]
php-imagick/bionic,now 3.4.3~rc2-2ubuntu4 amd64 [installed]
php-intl/bionic,now 1:7.2+60ubuntu1 all [installed]
php-json/bionic,now 1:7.2+60ubuntu1 all [installed]
php-mail-mime/bionic,now 1.10.2-0.1 all [installed,automatic]
php-mbstring/bionic,now 1:7.2+60ubuntu1 all [installed]
php-mysql/bionic,now 1:7.2+60ubuntu1 all [installed]
php-net-sieve/bionic,now 1.4.1-1 all [installed,automatic]
php-net-smtp/bionic,now 1.8.0-1 all [installed,automatic]
php-net-socket/bionic,now 1.0.14-2 all [installed,automatic]
php-pear/bionic-updates,bionic-security,now 1:1.10.5+submodules+notgz-1ubuntu1.18.04.1 all [installed,automatic]
php-pgsql/bionic,now 1:7.2+60ubuntu1 all [installed]
php-pspell/bionic,now 1:7.2+60ubuntu1 all [installed,automatic]
php-sqlite3/bionic,now 1:7.2+60ubuntu1 all [installed,automatic]
php-xdebug/bionic,now 2.6.0-0ubuntu1 amd64 [installed]
php-xml/bionic,now 1:7.2+60ubuntu1 all [installed]
php-zip/bionic,now 1:7.2+60ubuntu1 all [installed]
php7.2/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 all [installed,automatic]
php7.2-cli/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-common/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-curl/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-fpm/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-gd/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-intl/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-json/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-mbstring/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-mysql/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-opcache/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed]
php7.2-pgsql/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-pspell/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-readline/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-sqlite3/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-xml/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
php7.2-zip/bionic-updates,bionic-security,now 7.2.24-0ubuntu0.18.04.4 amd64 [installed,automatic]
```

On an upgrade I get
```
Setting up libapache2-mod-php7.2 (7.2.24-0ubuntu0.18.04.4) ...
ucfr: Attempt from package libapache2-mod-php7.2  to take /etc/php/7.2/fpm/php.ini away from package php7.2
-fpm                                                  
ucfr: Aborting.       
```

**Comment by jpschewe** [comment] 2020-04-26 13:22
Although I'm seeing this with the official Ubuntu repository.

**Comment by jpschewe** [comment] 2020-04-26 13:24
I found it, I had a symlink from `/etc/php/7.2/apache2/php.ini` to `/etc/php/7.2/fpm/php.ini`. That's the problem. If someone else comes across this problem and lands on this bug report. That's what they should look for.

**Comment by oerdnj** [comment] 2020-04-26 13:44
> I found it, I had a symlink from /etc/php/7.2/apache2/php.ini to /etc/php/7.2/fpm/php.ini. That's the problem.

@jpschewe, you are welcome, your rubber duck :).

Actually, I am glad that you went and:
1. provided useful information that could be used to find the problem
2. you didn't stop with pasting the information, but you looked at the problem once more and you found the problem

This is very much appreciated.

**Comment by jab4** [comment] 2021-05-02 20:28
Please apologize for warming this up.

We are facing a similar scenario, although our symlinks in /etc/php/n.n/php.ini are _on purpose_ to ease administration. Well, that is initial and sporadic administration on several virtual machines—as soon as there are incoming `apt update`s of PHP, we get the same problem as initially described by @dundee-81 and @jpschewe, whom I'm thankful for giving the right pointers.

The **quick and dirty fix** now is to always have a `rsync -a` of the original `/etc/php/` at hand, i. e. at `/etc/00-php-dist`; same for our customized version like `/etc/00-php-companyname` containing the symlinks which break the PHP dpkg scripts.

So, _before_ `apt upgrade` on PHP, we would move  /etc/00-php-dist back to /etc/php. 
_After_ `apt` and `dpkg` would have done their jobs—rightfully now without complaining and leaving behind a broken apt state—, we would move back our custom conf dir. Glad these updates don't happen too often.

@oerdnj: I was hoping to find the culprit under the likes of https://github.com/oerdnj/pkg-php/blob/master-5.6/debian/php5-fpm.preinst; but all I could find was this ancient version. Where could I look? Anyways, a better fix would be for the upstream → Ubuntu → Debian → @oerdnj  😬 package script to either one of:

1. determine file type of php.ini it's looking at: file or symlink? If symlink, offer to replace it with a "real" file or to keep it as is, skipping the script parts that cause the initial issue here.
2. determine whether there is an empty file named `php.ini_dpkg_ignore` inside the path of the ini file it is about to handle.  If yes, skip the script parts that cause the initial issue here. This also gives the benefit to silence the GUI question on changed local config files.
3. check if `apt upgrade` is running with `--yes`. If true, don't look at/mess with package configuration at all. 

Any thoughts?

**Comment by oerdnj** [comment] 2021-05-02 20:33
Don't symlink the main php.ini, just leave it in, but add any overrides as 99-local in the include directory.

You can also make php.I I empty (not delete it) and just include the central file from it.
