### ISSUE TITLE
Unversioned PECL (apcu, msgpack, memcached, ...) extension packages install all PHP versions

### ISSUE THREAD

**Issue by realizelol** [oerdnj/deb.sury.org#1465] opened 2020-10-11 08:30 UTC
**Frequently asked questions**

- [X] I have read [Frequenty Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Describe the bug**
Update _php-msgpack_ will install all dependencies for **all php versions**.

**To Reproduce**
just "apt full-upgrade -y #byebye"
`apt-cache depends php-msgpack`
php-msgpack
  PreDepends: php-common
  Depends: php8.0-msgpack
  Depends: php7.4-msgpack
  Depends: php7.3-msgpack
  Depends: php7.2-msgpack
  Depends: php7.1-msgpack
  Depends: php7.0-msgpack
  Depends: php5.6-msgpack

Original Focal package is:
`apt-cache depends php-msgpack`
php-msgpack
  PreDepends: php-common
 |Depends: <phpapi-20190902>
    libapache2-mod-php7.4
    libphp7.4-embed
    php7.4-cgi
    php7.4-cli
    php7.4-fpm
    php7.4-phpdbg
 |Depends: <phpapi-20180731>
 |Depends: <phpapi-20170718>
 |Depends: <phpapi-20160303>
 |Depends: <phpapi-20151012>
  Depends: <phpapi-20131226>
  Depends: libc6

**Expected behavior**
Remove dependencies so that not all versions of `phpX.X-msgpack` will be installed.
Maybe a notification that also php7.4-msgpack needs to be installed.

But it also seems to redirect to php-msgpack:
`apt-get install php7.4-msgpack`
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting **'php-msgpack'** instead of **'php7.4-msgpack'**
php-msgpack is already the newest version (2.1.0+0.5.7-1+ubuntu20.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Distribution (please complete the following information):**
 - OS: Ubuntu - 20.04 - focal
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
php-msgpack:
  Installed: 2.1.0+0.5.7-1+ubuntu20.04.1+deb.sury.org+1
  Candidate: 2.1.1+0.5.7-1+ubuntu20.04.1+deb.sury.org+1
  Version table:
     2.1.1+0.5.7-1+ubuntu20.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu focal/main amd64 Packages
 *** 2.1.0+0.5.7-1+ubuntu20.04.1+deb.sury.org+1 100
        100 /var/lib/dpkg/status
     2.1.0beta1-0ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://mirror.hetzner.de/ubuntu/packages focal/universe amd64 Packages

**Additional context**
I've done this to actually avoid this behaviour:
```
echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CN} main" > /etc/apt/sources.list.d/ondrej-php.list
echo "deb-src http://ppa.launchpad.net/ondrej/php/ubuntu ${UBUNTU_CN} main" >> /etc/apt/sources.list.d/ondrej-php.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &>/dev/null
apt-get -qq update
apt-get autoremove --purge -y ^php8.0* ^php7.3* ^php7.2* ^php7.1* ^php7.0* ^php5.6* \
  php-common libapache2-mod-php7.4 apache2-bin imagemagick-6-common libaspell15 libc-client2007e libjansson4 liblcms2-2 liblqr-1-0 \
  libmagickcore-6.q16-6 libmagickwand-6.q16-6 libonig5 libxmlrpc-epi0 mlock
mv /etc/php /etc/php.bk_$(date +"%Y%m%d_%H%M%S")
apt-get install -y php-apcu php-common php-igbinary php-imagick php-mailparse \
  php7.4-bcmath php7.4-bz2 php7.4-cli php7.4-common php7.4-curl php7.4-fpm php7.4-gd php7.4-gmp php7.4-imap php7.4-intl php7.4-json \
  php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-pspell php7.4-readline php7.4-soap php7.4-xml php7.4-xmlrpc php7.4-zip php7.4
rm /tmp/php-msgpack.deb
wget "http://ppa.launchpad.net/ondrej/php/ubuntu/pool/main/p/php-msgpack/php-msgpack_2.1.0+0.5.7-1+ubuntu20.04.1+deb.sury.org+1_amd64.deb" \
  -O /tmp/php-msgpack.deb && dpkg -i /tmp/php-msgpack.deb
apt install -y php-memcached
```
Therefore there is this version installed: `2.1.0+0.5.7-1+ubuntu20.04.1+deb.sury.org+1`

best regards
realizelol

**Comment by oerdnj** [comment] 2020-10-11 08:40
Originally, the php-msgpack contained the extensions for all PHP versions. The dependencies are there to mimick the previous behavior.

It requires manual intervention, but not having the dependency would be worse, it would actually remove the binary extensions that’s already in use without any warning.

**Comment by swiffer** [comment] 2020-10-11 10:12
i noticed that it's the same for php-apcu (will install all php versions).

i then tried to remove php-apcu and installed php8.0-apcu instead but it's still trying to install ll php versions.

however doing the same with php(8.0)-igbinary works just fine (php8.0-igbinary installs without requiring additional php versions to be installed).

**Comment by AleksCee** [comment] 2020-10-11 10:58
Same for php-igbinary php-imagick

**Comment by oerdnj** [comment] 2020-10-11 11:14
Those are genuine bugs and I'll look into that.

**Comment by logan2211** [comment] 2020-10-11 16:58
Looks like php-pecl-http is affected as well.

**Comment by mxdpeep** [comment] 2020-10-11 19:07
imagick and redis do the same

**Comment by oerdnj** [comment] 2020-10-11 19:19
So, let me specify what's a bug and what's a feature:

1. `apt install php-imagick` will pull all supported PHP releases - FEATURE
2. `apt install php8.0-imagick` will pull all supported PHP releases - BUG

e.g. `php-apcu`, `php-igbinary`, `php-msgpack`, `php-redis`, `php-imagick`, not a bug, feature, but `php-pecl-http` is a bug and it needs `php-propro` to be built first and the `php-pecl-http` can be updated and thus fixed.

**Comment by oerdnj** [comment] 2020-10-11 19:22
Here's more thorough explanation: https://www.patreon.com/posts/october-update-42636315

**Comment by stathis** [comment] 2020-10-11 19:22
I attempted to upgrade and got this.
Note that on the machine I only have 5.6 and 7.4 and it's trying to install all the other versions too.
I already ran it blind on a dev machine of mine and had to apt remove --purge them.

```
The following NEW packages will be installed:
  libargon2-1 php5.6-apcu php5.6-igbinary php7.0-apcu php7.0-cli php7.0-common php7.0-igbinary php7.0-json php7.0-opcache php7.0-phpdbg php7.0-readline php7.1-apcu php7.1-cli php7.1-common php7.1-igbinary php7.1-json
  php7.1-opcache php7.1-phpdbg php7.1-readline php7.2-apcu php7.2-cli php7.2-common php7.2-igbinary php7.2-json php7.2-opcache php7.2-phpdbg php7.2-readline php7.3-apcu php7.3-cli php7.3-common php7.3-igbinary php7.3-json
  php7.3-opcache php7.3-phpdbg php7.3-readline php7.4-apcu php7.4-igbinary php8.0-apcu php8.0-cli php8.0-common php8.0-igbinary php8.0-opcache php8.0-phpdbg php8.0-readline
The following packages will be upgraded:
  libargon2-0 libpcre16-3 libpcre2-16-0 libpcre2-32-0 libpcre2-8-0 libpcre2-dev libpcre2-posix2 libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libzip4 php-apcu php-common php-igbinary php-imagick php-pear php5.6-bcmath
  php5.6-bz2 php5.6-cli php5.6-common php5.6-curl php5.6-dev php5.6-enchant php5.6-fpm php5.6-gd php5.6-imap php5.6-intl php5.6-json php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-opcache php5.6-pspell php5.6-readline
  php5.6-tidy php5.6-xml php5.6-xmlrpc php5.6-xsl php5.6-zip php7.4-bz2 php7.4-cli php7.4-common php7.4-curl php7.4-dev php7.4-fpm php7.4-gd php7.4-imap php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php7.4-opcache
  php7.4-pspell php7.4-readline php7.4-soap php7.4-xml php7.4-xmlrpc php7.4-xsl php7.4-zip`
```

**Comment by stathis** [comment] 2020-10-11 19:23
It should only be upgrading, not deciding to install new packages for versions that I have not asked by itself.

**Comment by apiraino** [comment] 2020-10-11 19:53
For NextCloud users passing by, this issue breaks the NextCloud installation because PHP 8.0.0RC1 is pulled and not yet supported by NextCloud.

**Comment by AleksCee** [comment] 2020-10-11 20:42
Ok, after the notice from @oerdnj and 
pkguninstall php-igbinary php-imagick php-redis
pkginstall php7.4-igbinary php7.4-imagick php7.4-redis

All is fine for me.

BTW pkg... are aliases on my system because I‘m lazy
alias pkginstall='apt-get install'
alias pkguninstall='apt-get remove --purge'

**Comment by QROkes** [comment] 2020-10-11 21:06
@oerdnj updating an existing server and then getting all the PHP versions installed, **that's not a feature!**
I understand the explanation you posted, but now after `apt update && upgrade` I'm getting 8.0 RC displayed with `php -v`.

That will be happening to a lot of people and breaking a lot of things because **not all people will read your post before updating their servers.**

**Comment by stathis** [comment] 2020-10-11 21:08
Agree with @QROkes . While it is a very nice idea to split those packages, this change will break things.
It is best to keep it as is for 5.6-7.4 and start this new clean tactic for 8.0 imo.

**Comment by ProteusCortex** [comment] 2020-10-11 21:25
I agree @QROkes and @stathis. This is a serious issue in container images that I'm trying to keep lean. Having all PHP versions installed instead of just the one required by the application adds bloat, and the fact that the default PHP version changes to the latest RC is not helping in keeping the build scripts clean.

**Comment by predakanga** [comment] 2020-10-11 21:50
> @oerdnj updating an existing server and then getting all the PHP versions installed, **that's not a feature!**
> I understand the explanation you posted, but now after `apt update && upgrade` I'm getting 8.0 RC displayed with `php -v`.
> 
> That will be happening to a lot of people and breaking a lot of things because **not all people will read your post before updating their servers.** _(Especially when your PPA is maybe installed in millions of servers)_

The change in CLI version can also break other things - in my case, it broke PEAR.

**Comment by matt-stuart** [comment] 2020-10-11 22:32
@oerdnj sorry I’m trying to confirm there is a bug? I’m also seeing lots of behaviors that I’m documenting to try and get a complete picture. I’m seeing potential problems with purging php versions and cascading through removal of extension metas that are causing my explicitly installed versions of those extensions. 

Note: personally I believe the behavior should be when choosing the meta install the versions matching php*-common installed. None install then install the meta common and cascade from there. 

Also why is an RC part of this channel? That should be an explicit choice NOT auto!

**Comment by realizelol** [comment] 2020-10-11 22:33
So if I understand you correctly:

All php-* packages will grep all versions and if I wan't to install it for the correct version then I have to specify the version?
For example if I need apcu, igbinary, memcached, msgpack then I previously installed it like this:
`apt install php-acpu php-igbinary php-memcached php-msgpack`
Now we need to specify the version like this:
`apt install php7.4-acpu php7.4-igbinary php7.4-memcached php7.4-msgpack` ?

EDIT: Seems to be legit. But you previously have to do a `apt update` and you have to remove the PECL packages e.g.
`apt remove --purge php-acpu php-igbinary`

**"POSSIBLE ONE LINER":** _hasn't been tested cuz I use my own PHP-Script with conf modifications_
```
cp -r /etc/php /etc/php.bk_$(date +"%Y%m%d_%H%M%S")
apt update
PHP_PACKAGES=$(dpkg -l | grep -oP "^i.*\K(php-[a-z0-9]*)")
for PHPP in ${PHP_PACKAGES}; do
  apt remove --purge -y ${PHPP}
  PHPP_INST=$(echo ${PHP_INST} | sed "s/php-/php7.4-/g")
  apt install -y ${PHP_INST}
done
```

best regards
realizelol

**Comment by swiffer** [comment] 2020-10-12 03:37
> I agree @QROkes and @stathis. This is a serious issue in container images that I'm trying to keep lean. Having all PHP versions installed instead of just the one required by the application adds bloat, and the fact that the default PHP version changes to the latest RC is not helping in keeping the build scripts clean.

This can be avoided by specifying the matching extension version (e.g. php7.4-apcu)

**Comment by matt-stuart** [comment] 2020-10-12 03:53
@swiffer for me and it appears others the issue became the meta packages. At SOME point in the past we had used meta packages to install an extension even though sometime in the last 2 years we've switched to using explicit php7.2* packages. We didn't purge the meta packages first instead just stuck with installing php7.2* from that point forward. The PPA effectively took over. Without warning it decided to not only install every version of PHP because we had a meta in the past and the above mentioned "feature" but it ALSO took over set the alternative to whatever it felt like. In this case it set the alternative to PHP8.0 RC1. A RELEASE CANDIDATE. It decided that the DEFAULT should be a release candidate. I didn't ask for that. I asked for PHP7.2.

*Note: the "why" I ran into this problem is currently theory. I've tested new systems with ONLY ever using php7.x packages and haven't been able to recreate. Currently restoring some old images and "moving through time" to try and simulate the switch from meta to non-meta packages.

**Comment by swiffer** [comment] 2020-10-12 04:06
I see, I've had the same locally but in my case had to do a apt-get dist-upgrade to get the newer versions of the meta packages, then wondered why all PHP versions would get installed and found this issue, removed them and installed the specific versions instead.

For PHP8.0; happy to have it available for testing but as you mentioned it should not be set to the default cli version.

There is a risk of causing serious issues for orgs running this PPA in production and updating without seeing the post / issue and simply agree on what get's installed.

Maybe it's better to deprecate the meta packages instead?

**Comment by matt-stuart** [comment] 2020-10-12 04:27
So in general I feel:

Meta should always alias to the most recent stable line. Installing from meta should mean you roll without the edge but never cutting (Ie no beta / RC, most recent stable release). 

Setting the used version or alternatives is more complex. In part I don’t know what’s possible from a PPAs perspective. 

When installing meta it should only add to the alternatives list and not be opinionated. If left in auto select mode it’ll use the newest version otherwise if specified in some way the meta will not affect that choice. 

Installing a package from the phpX.X set should set this version as preferred. I mean by this is if, “a user” has set the alternative manually be through IaC or by typing the command then it should not mess with it. Otherwise it sets the used version to what’s being installed. That includes if it is already installed but being installed again (perhaps this needs a flag) but basically I want last across the line behavior. 

What happened today should never happen. In no way should an upgrade on a meta package for an extension cause new major versions to be installed AND take over the “active” system version when explicit versions had been installed.

**Comment by mig5** [comment] 2020-10-12 04:52
Yes, this is especially a problem for existing installations. Even if I was to try and 'get onto' the version-specific releases on a PHP 7.2 system with FPM and a couple of things like 'php-redis', I can't seem to find a way to apt-get remove the 'non-version-specific' packages without weird things happening like wiping out FPM and installing Apache.

And indeed, dragging in the other PHP versions as part of build scripts such as Dockerfiles, means that the CLI PHP version ends up wrong, which cascades into further problems (e.g where using `pear`), unless one mitigates with `update-alternatives --set php /usr/bin/php7.2`

**Comment by matt-stuart** [comment] 2020-10-12 04:57
Wanted to add we’re currently using this to help mitigate. 

```
    /etc/apt/preferences.d/php.pref
    Package: php8.0*
    Pin: release *
    Pin-Priority: -1
    
    Package: php5.6*
    Pin: release *
    Pin-Priority: -1
    
    Package: php7.3*
    Pin: release *
    Pin-Priority: 100
    
    Package: php7.*
    Pin: release *
    Pin-Priority: -1
```

**Comment by timglabisch** [comment] 2020-10-12 06:03
i guess this will break half the internet that uses php. But nice to see, that a lot of people will start upgrading to php 8 ;)

**Comment by oerdnj** [comment] 2020-10-12 06:10
I think I found a way how to circumvent the problem other way. The individual packages don't depend on matching `phpapi-<ver>` now, so they don't pull any of the SAPIs. That way when you do `apt install php7.4-apcu` it won't pull `php7.4-cli` which leaves your system just with the binary extension and nothing to use it with, but that way installing `php-apcu` will just install the PHP extensions and not all the PHP releases available.

**Comment by oerdnj** [comment] 2020-10-12 06:14
The `deb.sury.org+4` version should contain the fix.

**Comment by oerdnj** [comment] 2020-10-12 06:17
```
# apt install php-apcu
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  php-common php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php7.4-apcu php8.0-apcu psmisc
Suggested packages:
  php-gd
Recommended packages:
  php-apcu-bc
The following NEW packages will be installed:
  php-apcu php-common php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php7.4-apcu php8.0-apcu psmisc
0 upgraded, 10 newly installed, 0 to remove and 3 not upgraded.
Need to get 383 kB of archives.
After this operation, 1585 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

**Comment by Basster** [comment] 2020-10-12 06:57
xdebug is affected, as well. At least it is not enabled by default:

On a fresh install

```bash
sudo apt install php7.4-cli php-xdebug                                                                 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  libzip4 ttf-dejavu-core
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
Die folgenden zusätzlichen Pakete werden installiert:
  php-common php5.6-xdebug php7.0-xdebug php7.1-xdebug php7.2-xdebug php7.3-xdebug php7.4-common php7.4-json php7.4-opcache php7.4-readline
Vorgeschlagene Pakete:
  php-pear
Die folgenden NEUEN Pakete werden installiert:
  php-common php-xdebug php5.6-xdebug php7.0-xdebug php7.1-xdebug php7.2-xdebug php7.3-xdebug php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-readline
0 aktualisiert, 12 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
Es müssen noch 0 B von 4.936 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 23,2 MB Plattenplatz zusätzlich benutzt.

```
then
```bash
ls -la /etc/php/7.4/mods-available                                                                       
insgesamt 88
drwxr-xr-x 2 root root 4096 Okt 12 08:49 .
drwxr-xr-x 4 root root 4096 Okt 12 08:49 ..
-rw-r--r-- 1 root root   74 Okt 10 21:45 calendar.ini
-rw-r--r-- 1 root root   71 Okt 10 21:45 ctype.ini
-rw-r--r-- 1 root root   70 Okt 10 21:45 exif.ini
-rw-r--r-- 1 root root   69 Okt 10 21:45 ffi.ini
-rw-r--r-- 1 root root   74 Okt 10 21:45 fileinfo.ini
-rw-r--r-- 1 root root   69 Okt 10 21:45 ftp.ini
-rw-r--r-- 1 root root   73 Okt 10 21:45 gettext.ini
-rw-r--r-- 1 root root   71 Okt 10 21:45 iconv.ini
-rw-r--r-- 1 root root   68 Okt 10 21:45 json.ini
-rw-r--r-- 1 root root   79 Okt 10 21:45 opcache.ini
-rw-r--r-- 1 root root   69 Okt 10 21:45 pdo.ini
-rw-r--r-- 1 root root   70 Okt 10 21:45 phar.ini
-rw-r--r-- 1 root root   71 Okt 10 21:45 posix.ini
-rw-r--r-- 1 root root   76 Okt 10 21:45 readline.ini
-rw-r--r-- 1 root root   71 Okt 10 21:45 shmop.ini
-rw-r--r-- 1 root root   73 Okt 10 21:45 sockets.ini
-rw-r--r-- 1 root root   73 Okt 10 21:45 sysvmsg.ini
-rw-r--r-- 1 root root   73 Okt 10 21:45 sysvsem.ini
-rw-r--r-- 1 root root   73 Okt 10 21:45 sysvshm.ini
-rw-r--r-- 1 root root   75 Okt 10 21:45 tokenizer.ini

```
and
```bash
php --version                                                                               
PHP 7.4.11 (cli) (built: Oct 10 2020 19:45:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

```

**Comment by swiffer** [comment] 2020-10-12 07:04
Xdebug seems to be missing for 7.4 and 8.0

Specific packages (e.g. 5.1.19+4.0.11-2+ubuntu20.10.1+deb.sury.org-3) are still showing multiple versions of the extension. Is this intended ?

**Comment by oerdnj** [comment] 2020-10-12 07:19
> Xdebug seems to be missing for 7.4 and 8.0 in specific packages.

There's no xdebug for PHP 8.0 yet, the 7.4 should be fixed in next upload. There's a difference on how upstream developers mark compatibility with PHP versions, and xdebug use one that the script pass in a wrong way.

> Specific packages (e.g. 5.1.19+4.0.11-2+ubuntu20.10.1+deb.sury.org-3) are still showing multiple versions of the extension. Is this intended ?

I don't understand what do you mean by this.

**Comment by Basster** [comment] 2020-10-12 09:07
> the 7.4 [xdebug] should be fixed in next upload

Thank you, @oerdnj. Works like a charm. https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/20140163 also fixed the issue, of the missing `mods-available/xdebug.ini`. :+1:

**Comment by stathis** [comment] 2020-10-12 09:13
Thanks @oerdnj .
Do you propose some specific actions to clean up a system after the latest updates?
E.g. purge the php-* and all uneeded phpX.Y-* ?

**Comment by oerdnj** [comment] 2020-10-12 09:51
Well, thanks for pushing me to find a better solution that would work achieve the goal of splitting the binary package while not breaking anything.

I would suggest to do it in two steps:

1. Purge the main PHP X.Y package, e.g.: `apt purge phpX.Y-common```
2. Purge the extra modules, e.g.: `apt purge phpX.Y-*`

That way it would be more clear what is happening in each step.

**Comment by stathis** [comment] 2020-10-12 10:59
@oerdnj , what about the old, `php-common`, should that be removed too?

**Comment by oerdnj** [comment] 2020-10-12 11:15
Removing `php-common` would uninstall everything related to PHP - that’s the ultimate “base” package.

**Comment by stathis** [comment] 2020-10-12 11:20
What about `php-apcu php-igbinary php-imagick php-pear php-redis` -- If i'm running let's say only 7.4, do I keep these now?
Sorry for asking so many things that you might have answered already, it's just not so clear to me at this time! :)

**Comment by oerdnj** [comment] 2020-10-12 11:34
That’s up to you. Keeping them is harmless, you don’t end up with more files than before. You can remove them if nothing else depend on them to keep the system in clean state.

**Comment by logan2211** [comment] 2020-10-12 15:43
Thanks @oerdnj. Still seeing some issues with the http module.

1. The `php<version>-http` packages do not depend on `php<version>-raphf` and `php<version>-propro`, so the raphf and propro dependencies must be explicitly installed or the module cannot be used.

2. Installing `php<version>-http` does not enable the module. It must be enabled separately using phpenmod. Not sure if this is intentional but it is definitely a notable change since modules were enabled upon installation previously.

**Comment by KorvinSzanto** [comment] 2020-10-12 15:50
I'm not sure if this is related but we saw some really strange behavior from the memcached extension with this mornings update. For some reason the new version of memcached has a construct with three parameters vs just the 2 that it has had in the past. Is this related or different?

Specific error we're seeing is:
```Illuminate\Contracts\Container\BindingResolutionException: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #2 [ <optional> $connection_str ]] in class Memcached'```

because of that 3rd parameter. If I use reflection to check it indeed has 3 parameters while locally I only see 2.

**Comment by oerdnj** [comment] 2020-10-12 17:07
Do you have the latest version locally?

**Comment by oerdnj** [comment] 2020-10-12 17:09
I’ll look into the pecl_http, there pkg-pecl.mk should pull the dependencies from package.xml and export them into a proper field, but it looks like there’s something wrong.

**Comment by KorvinSzanto** [comment] 2020-10-12 20:32
> Do you have the latest version locally?

The versions as reported by phpinfo are the same in both places but yeah clearly there's a different set of code on the production server for this extension since reflection is seeing a different constructor

**Comment by GaalexxC** [comment] 2020-10-13 06:52
> It should only be upgrading, not deciding to install new packages for versions that I have not asked by itself.

Same issue have PHP7.4 and no other versions, no problems updating until a couple days ago, apt update/upgrade wants to install every PHP version and package available. Had to remove the PPA for now to update normally other packages.

**Comment by GrahamCampbell** [comment] 2020-10-13 12:37
I can confirm this issue, even after specifying the PHP version. Ubuntu 20.04. A months ago, I ran:

```
add-apt-repository ppa:ondrej/php
apt clean && apt update
apt dist-upgrade
apt install php7.4 php7.4-apcu php7.4-apcu-bc php7.4-bcmath php7.4-curl php7.4-ds php7.4-gd php7.4-gmp php7.4-json php7.4-mbstring php7.4-pgsql php7.4-readline php7.4-redis php-sqlite3 php7.4-xml php7.4-zip --no-install-recommends
```

And now, when I run `apt clean && apt update && apt dist-upgrade`, the following happens:

```
The following NEW packages will be installed:
  php5.6-apcu php5.6-igbinary php5.6-redis php7.0-apcu php7.0-igbinary php7.0-redis php7.1-apcu php7.1-igbinary
  php7.1-redis php7.2-apcu php7.2-igbinary php7.2-redis php7.3-apcu php7.3-igbinary php7.3-redis php7.4-apcu
  php7.4-igbinary php7.4-redis php8.0-apcu php8.0-igbinary php8.0-redis
The following packages will be upgraded:
  libapache2-mod-php7.4 libargon2-1 libpcre2-8-0 libpcre3 libzip4 php-apcu php-common php-igbinary php-redis
  php-sqlite3 php7.4 php7.4-bcmath php7.4-cli php7.4-common php7.4-curl php7.4-gd php7.4-gmp php7.4-json
  php7.4-mbstring php7.4-opcache php7.4-pgsql php7.4-readline php7.4-sqlite3 php7.4-xml php7.4-zip sosreport
26 upgraded, 21 newly installed, 0 to remove and 0 not upgraded.
```

I suppose it is `php-sqlite3` which is causing the issues, however, at the time (and possibly still the case), `php7.4-sqlite3` did not exist.

**Comment by GrahamCampbell** [comment] 2020-10-13 12:41
Even after removing `php-sqlite3` and `php7.4-sqlite3`, the issue remains.

**Comment by GrahamCampbell** [comment] 2020-10-13 12:42
Also:

```
$ apt install php7.4-apcu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  php-apcu php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php8.0-apcu
The following NEW packages will be installed:
  php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php7.4-apcu php8.0-apcu
The following packages will be upgraded:
  php-apcu
1 upgraded, 7 newly installed, 0 to remove and 23 not upgraded.
Need to get 326 kB of archives.
After this operation, 374 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by adriankirchner** [comment] 2020-10-13 12:48
> Also:
> 
> ```
> $ apt install php7.4-apcu
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following additional packages will be installed:
>   php-apcu php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php8.0-apcu
> The following NEW packages will be installed:
>   php5.6-apcu php7.0-apcu php7.1-apcu php7.2-apcu php7.3-apcu php7.4-apcu php8.0-apcu
> The following packages will be upgraded:
>   php-apcu
> 1 upgraded, 7 newly installed, 0 to remove and 23 not upgraded.
> Need to get 326 kB of archives.
> After this operation, 374 kB of additional disk space will be used.
> Do you want to continue? [Y/n] n
> Abort.
> ```

@GrahamCampbell In this case `php-apcu` would be upgraded, therefore installing the new dependencies for each php version. Remove if beforehand and your  `apt install php7.4-apcu` will be clean.
I used this list, which covers all previously installed metapackages on my machines:
```bash
sudo apt-get -y remove php-imagick php-redis php-memcached php-apcu php-igbinary php-msgpack 
```
And then:
```bash
sudo apt-get install php7.4-imagick php7.4-redis php7.4-memcached php7.4-apcu php7.4-igbinary php7.4-msgpack 
```

**Comment by mpesari** [comment] 2020-10-13 12:55
Sorry if this is noise, but `php-ds` does not include 8.0 files (nor do `phpX.Y-ds` packages exist), and `php-ssh2` pulls other versions except `php8.0-ssh2`, which does not exist. Thanks!

**Comment by GrahamCampbell** [comment] 2020-10-13 12:59
@mpesari Yep, those two extensions have not been upgraded yet. You can send PRs to upgrade them if you like. The source code is https://github.com/php-ds/ext-ds and https://github.com/php/pecl-networking-ssh2.

**Comment by GrahamCampbell** [comment] 2020-10-13 13:03
@adriankirchner Ah, right. Thank you!

**Comment by OndroNR** [comment] 2020-10-18 19:56
I am running PHP 7.2, but those packages `php-igbinary php-imagick php-memcache php-memcached php-msgpack php-redis` did not have `php7.2-*` variant at time of server setup (now they do).

I ran following commands to resolve my situation:
```
apt-mark auto php-common php-igbinary php-imagick php-memcache php-memcached php-msgpack php-redis
apt install php7.2-common php7.2-igbinary php7.2-imagick php7.2-memcache php7.2-memcached php7.2-msgpack php7.2-redis
```

Useful commands for checking which php packages were installed manually or automatically as dependency of another package.
```
apt-mark showmanual | grep php
apt-mark showauto | grep php
```

**Comment by GrahamCampbell** [comment] 2020-10-18 22:51
Yep, this is exactly what I experienced, and this isn't really a bug. It's just what can be expected.

**Comment by dannyb80** [comment] 2020-10-21 17:57
I think `php-sass` still needs to be fixed...

**Comment by GaalexxC** [comment] 2020-10-26 04:24
> Yep, this is exactly what I experienced, and this isn't really a bug. It's just what can be expected.

If this is not a bug then bugs don't exist. 

First off all of a sudden common packages have changed, when did this occur and why when the conmon packages are functioning properly? IE
php-apcu php-apcu-bc php-igbinary php-imagick php-redis
php7.4-apcu php7.4-apcu-bc php7.4-igbinary php7.4-imagick php7.4-redis

Do I need to remove the common packages and install the version specific packages now? Does anyone have an idea of wtf is happening with this repo?

Apt update / apt upgrade cannot be preformed with this repo anymore as it wants to install everything no matter what you have installed. I would classify that as a BUG.

apt list --upgradable shows proper upgrade packages
![upgradable](https://user-images.githubusercontent.com/28851458/97133480-97511d80-1720-11eb-8b5a-fafb2c3c243b.PNG)

Apt upgrade blows open the doors

![upgrade](https://user-images.githubusercontent.com/28851458/97133514-b64faf80-1720-11eb-92c6-5d8018129b70.PNG)

Are we going to see a fix or should I mark this repo as dead? Don't want to have to uninstall PHP and reinstall using Ubuntu native support although it would be best seeing that nothing is happening with this issue.

**Comment by oerdnj** [comment] 2020-10-26 05:14
> Are we going to see a fix or should I mark this repo as dead?

With this entitled attitude, please mark this repo as dead.

**Comment by oerdnj** [comment] 2020-10-26 05:15
> I think php-sass still needs to be fixed...

The phpsass package hasn’t been built in a while. I’ll take a look.

**Closed by oerdnj** 2020-10-26 05:14 UTC

**Comment by GrahamCampbell** [comment] 2020-10-26 10:25
@GaalexxC Please actually read the whole thread... the solution is right here...

**Comment by themew** [comment] 2022-01-20 00:33
This issue has returned with Debian 10.11 -- trying to figure out how to fix this...

**Comment by sleemanj** [comment] 2022-01-20 01:09
Read the FAQ, described in thereMessage ID: ***@***.***>
https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions
