### ISSUE TITLE
Cannot update "graphicsmagick" 1.3.25 on Trusty

### ISSUE THREAD

**Issue by mbrodala** [oerdnj/deb.sury.org#812] opened 2018-02-09 15:14 UTC
It seems like the dependencies of the `graphicsmagick` package cannot be satisfied on Ubuntu Trusty:

```
$ sudo apt install graphicsmagick
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 graphicsmagick : Depends: libgraphicsmagick-q16-3 (>= 1.3.5) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The current package state:

```
$ apt-cache policy graphicsmagick
graphicsmagick:
  Installed: 1.3.18-1ubuntu3
  Candidate: 1.3.25-8~ubuntu14.04.1+deb.sury.org+2
  Version table:
     1.3.25-8~ubuntu14.04.1+deb.sury.org+2 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
 *** 1.3.18-1ubuntu3 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Any idea besides staying on 1.3.18?

**Comment by oerdnj** [comment] 2018-02-12 10:06
What's the output of `apt-cache policy libgraphicsmagick-q16-3` and what happens if you try to do: `apt-get install libgraphicsmagick-q16-3`?

**Comment by mbrodala** [comment] 2018-02-12 14:20
Here we go:

```
$ apt-cache policy libgraphicsmagick-q16-3
libgraphicsmagick-q16-3:
  Installed: (none)
  Candidate: 1.3.25-8~ubuntu14.04.1+deb.sury.org+2
  Version table:
     1.3.25-8~ubuntu14.04.1+deb.sury.org+2 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
```

And:

```
$ sudo apt install libgraphicsmagick-q16-3
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgraphicsmagick-q16-3 : Depends: libwebp5 (>= 0.4.3) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Following on that:

```
$ apt-cache policy libwebp5
libwebp5:
  Installed: (none)
  Candidate: 0.4.0-4
  Version table:
     0.4.0-4 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
```

**Comment by oerdnj** [comment] 2018-02-21 12:06
Aha, graphicsmagic needs to be recompiled against newest libwebp.

**Comment by gschoenberger** [comment] 2018-03-13 10:28
We are hitting the same issue on Ubuntu 14.04, the problem is the dependency on libwebp5 (>= 0.4.3), I think it muss be libwebp6 now!

**Comment by oerdnj** [comment] 2018-03-13 19:35
This should be fixed in graphicsmagick 1.3.28 that I uploaded today. If not, please provide diagnostic info, I don't have time to try it right now.

**Closed by oerdnj** 2018-03-13 19:35 UTC
Labels: moreinfo

**Comment by mbrodala** [comment] 2018-03-14 08:27
I can confirm that version 1.3.28 installs just fine. @oerdnj thanks for fixing!

**Comment by gschoenberger** [comment] 2018-03-14 08:28
Yes, THX a lot. Tested it on another two hosts.
