### ISSUE TITLE
Php5-fpm starts and then fails after a few seconds

### ISSUE THREAD

**Issue by golevel** [oerdnj/deb.sury.org#144] opened 2015-11-30 17:15 UTC
After an upgrade from ubuntu 14 to ubuntu 15, if I run sudo php5-fpm start, it hangs in ssh but the webserver is online and I can access the website. After a few seconds (maybe 30) the ssh command finally finishes with this error message:

`Job for php5-fpm.service failed because a timeout was exceeded. See "systemctl status php5-fpm.service" and "journalctl -xe" for details.`

systemctl status php5-fpm.service yields:

`php5-fpm.service - The PHP FastCGI Process Manager Loaded: loaded (/lib/systemd/system/php5-fpm.service; disabled; vendor preset: enabled) Active: failed (Result: timeout) since Mon 2015-11-30 11:36:59 EST; 1min 47s ago Process: 1508 ExecStart=/usr/sbin/php5-fpm --nodaemonize --fpm-config /etc/php5/fpm/php-fpm.conf (code=exited, status=0/SUCCESS) Process: 1504 ExecStartPre=/usr/lib/php5/php5-fpm-checkconf (code=exited, status=0/SUCCESS) Main PID: 1508 (code=exited, status=0/SUCCESS)`

journalctl -xe yields:

`No journal files were found. -- No entries --`

I did my best to google for a solution and found this:

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1451346

From which I tried this:

/usr/sbin/php5-fpm --nodaemonize --fpm-config /etc/php5/fpm/php-fpm.conf

Which works. It just hangs in ssh but at least my webserver is running. However, I can no longer use sudo service php5-fpm start, stop, or restart. Is there a permanent solution to this?

**Comment by oerdnj** [comment] 2015-11-30 17:36
Duplicate of #65

**Closed** 2015-12-08 15:35 UTC
