### ISSUE TITLE
packages.sury.org SSL certificate problem

### ISSUE THREAD

**Issue by MacTrophy** [oerdnj/deb.sury.org#1106] opened 2019-02-25 15:42 UTC
**Describe the bug**
I called `apt-get update` on my servers and got errors about SSL certificate, this seems linked with the recent change to using KeyCDN I think

```
Err:6 https://cdn.sury.org/php stretch Release
  SSL: certificate subject name (*.kxcdn.com) does not match target host name 'cdn.sury.org'
Reading package lists... Done
E: The repository 'https://packages.sury.org/php stretch Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

I don't know if it has an impact but I am also using a apt-cacher-ng server on our local network

I tried re-running `wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg` on both my server and the cache server with no success.

I also tried using plain HTTP with no success.

**Distribution (please complete the following information):**
 - OS: Debian 9
 - Architecture: amd64
 - Repository: packages.sury.org

**Comment by tanertas** [comment] 2019-02-26 14:30
I have same issue as well. I purged, reinstalled ca-certificates... manually imported certificates of packages.sury.org (which said they're already installed) but didn't help.

```
# apt-get update
Ign:1 http://ftp.tr.debian.org/debian stretch InRelease
Get:3 http://ftp.tr.debian.org/debian stretch-updates InRelease [91,0 kB]
Get:4 http://ftp.tr.debian.org/debian stretch-backports InRelease [91,8 kB]
Ign:5 https://packages.sury.org/php stretch InRelease                    
Get:6 http://ftp.tr.debian.org/debian stretch Release [118 kB]           
Ign:7 https://packages.sury.org/php stretch Release    
Get:2 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94,3 kB]
Ign:9 https://packages.sury.org/php stretch/main amd64 Packages
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Ign:9 https://packages.sury.org/php stretch/main amd64 Packages
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Ign:9 https://packages.sury.org/php stretch/main amd64 Packages
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Ign:9 https://packages.sury.org/php stretch/main amd64 Packages
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Ign:9 https://packages.sury.org/php stretch/main amd64 Packages
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Err:9 https://packages.sury.org/php stretch/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign:10 https://packages.sury.org/php stretch/main all Packages
Ign:11 https://packages.sury.org/php stretch/main Translation-en_US
Ign:12 https://packages.sury.org/php stretch/main Translation-en
Fetched 395 kB in 4s (81,2 kB/s)
Reading package lists... Done
W: The repository 'https://packages.sury.org/php stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.sury.org/php/dists/stretch/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead
```

```
# echo "" | gnutls-cli packages.sury.org -p 443
Processed 153 CA certificate(s).
Resolving 'packages.sury.org:443'...
Connecting to '178.18.201.202:443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=packages.sury.org', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x037ec55cdcdf21c494909e613f0368a97ee8, RSA key 2048 bits, signed using RSA-SHA256, activated `2019-02-07 17:48:27 UTC', expires `2019-05-08 17:48:27 UTC', key-ID `sha256:68212ddf60c3eaac1cdd07cab3f113907f84bc3af38e382b54546e8cd6dbe474'
	Public Key ID:
		sha1:282798be55c80198b74121f979aafd358bfd00d0
		sha256:68212ddf60c3eaac1cdd07cab3f113907f84bc3af38e382b54546e8cd6dbe474
	Public key's random art:
		+--[ RSA 2048]----+
		|.=+.             |
		|+.oo             |
		| o.+E            |
		|  +=.o .         |
		|  oo* + S        |
		| ..  *           |
		| o. . +          |
		|. .o + +         |
		|  ..o o..        |
		+-----------------+

- Certificate[1] info:
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', key-ID `sha256:60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18'
- Status: The certificate is trusted. 
- Description: (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-128-GCM)
- Session ID: 29:BE:EC:8A:90:4F:51:C5:ED:95:AE:67:A1:28:23:19:23:91:93:E0:B7:7E:42:96:1B:E0:1F:BC:F0:7C:BD:65
- Ephemeral EC Diffie-Hellman parameters
 - Using curve: SECP256R1
 - Curve size: 256 bits
- Version: TLS1.2
- Key Exchange: ECDHE-RSA
- Server Signature: RSA-SHA256
- Cipher: AES-128-GCM
- MAC: AEAD
- Compression: NULL
- Options: extended master secret, safe renegotiation,
- Handshake was completed

- Simple Client Mode:
```

**Comment by oerdnj** [comment] 2019-02-26 14:40
These are two different errors, the first one is caused by stale information in the DNS. Did you perhaps put an entry to `/etc/hosts`?

The second issue is different, could you try doing `printf "HEAD https://packages.sury.org/ HTTP/1.0\n\n" | gnutls-cli packages.sury.org -p 443`, the headers should look like this:

```
HTTP/1.1 200 OK
Server: keycdn-engine
Date: Tue, 26 Feb 2019 14:38:52 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: max-age=86400
Expires: Wed, 27 Feb 2019 14:38:52 GMT
X-Edge-Location: atvi
Access-Control-Allow-Origin: *
```

I am interested in what `X-Edge-Location` is the CDN reports.

**Comment by MacTrophy** [comment] 2019-02-26 14:44
On my configuration I added nothing in the host file and here is the output of the command
```
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=packages.sury.org', issuer `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', serial 0x037ec55cdcdf21c494909e613f0368a97ee8, RSA key 2048 bits, signed using RSA-SHA256, activated `2019-02-07 17:48:27 UTC', expires `2019-05-08 17:48:27 UTC', key-ID `sha256:68212ddf60c3eaac1cdd07cab3f113907f84bc3af38e382b54546e8cd6dbe474'
	Public Key ID:
		sha1:282798be55c80198b74121f979aafd358bfd00d0
		sha256:68212ddf60c3eaac1cdd07cab3f113907f84bc3af38e382b54546e8cd6dbe474
	Public key's random art:
		+--[ RSA 2048]----+
		|.=+.             |
		|+.oo             |
		| o.+E            |
		|  +=.o .         |
		|  oo* + S        |
		| ..  *           |
		| o. . +          |
		|. .o + +         |
		|  ..o o..        |
		+-----------------+

- Certificate[1] info:
 - subject `CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US', issuer `CN=DST Root CA X3,O=Digital Signature Trust Co.', serial 0x0a0141420000015385736a0b85eca708, RSA key 2048 bits, signed using RSA-SHA256, activated `2016-03-17 16:40:46 UTC', expires `2021-03-17 16:40:46 UTC', key-ID `sha256:60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18'
- Status: The certificate is trusted.
- Description: (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-128-GCM)
- Session ID: 3A:1D:A6:54:45:7F:E1:F0:CF:98:20:4A:CF:9E:66:37:61:6D:41:B3:6C:FA:7C:73:E7:34:EC:1B:21:FA:52:55
- Ephemeral EC Diffie-Hellman parameters
 - Using curve: SECP256R1
 - Curve size: 256 bits
- Version: TLS1.2
- Key Exchange: ECDHE-RSA
- Server Signature: RSA-SHA256
- Cipher: AES-128-GCM
- MAC: AEAD
- Compression: NULL
- Options: extended master secret, safe renegotiation, OCSP status request,
- Handshake was completed

- Simple Client Mode:

HTTP/1.1 200 OK
Server: keycdn-engine
Date: Tue, 26 Feb 2019 14:43:02 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: max-age=86400
Expires: Wed, 27 Feb 2019 14:43:02 GMT
X-Edge-Location: camo
Access-Control-Allow-Origin: *
```

**Comment by tanertas** [comment] 2019-02-26 14:51
```
# printf "HEAD https://packages.sury.org/ HTTP/1.0\n\n" | gnutls-cli packages.sury.org -p 443

HTTP/1.1 200 OK
Server: keycdn-engine
Date: Tue, 26 Feb 2019 14:48:35 GMT
Content-Type: text/html; charset=utf-8
Connection: close
Vary: Accept-Encoding
Cache-Control: max-age=86400
Expires: Wed, 27 Feb 2019 14:48:35 GMT
X-Edge-Location: tris
Access-Control-Allow-Origin: *
```

**Comment by oerdnj** [comment] 2019-02-26 14:54
@MacTrophy cdn.sury.org was an interim configuration and it should not be used anywhere.  So, how does your apt sources.lists for packages.sury.org looks like?

**Comment by MacTrophy** [comment] 2019-02-26 14:56
Simple file `/etc/apt/sources.list.d/php.list` containing `deb https://packages.sury.org/php/ stretch main`

**Comment by oerdnj** [comment] 2019-02-26 14:56
@tanertas Are you sure it's not your government tampering with the connection?  The gnutls-cli TLS connection setup looks fine to me, so it should work.

**Comment by oerdnj** [comment] 2019-02-26 14:57
@MacTrophy So, if you do: `dig IN A packages.sury.org` what is the output?

**Comment by oerdnj** [comment] 2019-02-26 14:57
And `ping packages.sury.org`?

**Comment by tanertas** [comment] 2019-02-26 14:58
```
ping packages.sury.org
PING p-tris00.kxcdn.com (178.18.201.202) 56(84) bytes of data.
64 bytes from 201-202.vargonen.net (178.18.201.202): icmp_seq=1 ttl=54 time=12.4 ms
```

**Comment by MacTrophy** [comment] 2019-02-26 14:59
```
# dig IN A packages.sury.org

; <<>> DiG 9.10.3-P4-Debian <<>> IN A packages.sury.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2261
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;packages.sury.org.		IN	A

;; ANSWER SECTION:
packages.sury.org.	60	IN	CNAME	deb-f3a0.kxcdn.com.
deb-f3a0.kxcdn.com.	3600	IN	CNAME	c-ca00.kvcdn.com.
c-ca00.kvcdn.com.	407	IN	CNAME	p-camo00.kxcdn.com.
p-camo00.kxcdn.com.	37	IN	A	192.99.233.195

;; AUTHORITY SECTION:
kxcdn.com.		61540	IN	NS	ns-1318.awsdns-36.org.
kxcdn.com.		61540	IN	NS	ns-1756.awsdns-27.co.uk.
kxcdn.com.		61540	IN	NS	ns-437.awsdns-54.com.
kxcdn.com.		61540	IN	NS	ns-572.awsdns-07.net.

;; Query time: 390 msec
;; SERVER: 192.168.128.1#53(192.168.128.1)
;; WHEN: Tue Feb 26 09:58:31 EST 2019
;; MSG SIZE  rcvd: 278
```

```
# ping packages.sury.org
PING p-camo00.kxcdn.com (192.99.233.195) 56(84) bytes of data.
64 bytes from camo01.proinity.net (192.99.233.195): icmp_seq=1 ttl=53 time=9.03 ms
```

**Comment by MacTrophy** [comment] 2019-02-26 14:59
Oh, seems the answer comes from my internal DNS! damn I'll try to flush that

**Comment by oerdnj** [comment] 2019-02-26 15:05
I believe we have proven that the server has a correct certificate if the DNS is correct, so I am closing the issue.

And for @tanertas, I am sorry, but I can't do an individual debugging of the servers beyond basic tips.  I simply don't have time for that.

**Closed by oerdnj** 2019-02-26 15:05 UTC

**Comment by MacTrophy** [comment] 2019-02-26 15:09
Can you provide me an example of correct results from the dig command so I can troubleshoot my DNS problem? So far even with my local dns server offline it's not working with answers from 4.2.2.1

**Comment by tanertas** [comment] 2019-02-26 15:12
@oerdnj closing the issue is not the solution. Maybe some other people come with a solution.

**Comment by oerdnj** [comment] 2019-02-26 15:14
@MacTrophy This:
```
;; ANSWER SECTION:
packages.sury.org.	60	IN	CNAME	deb-f3a0.kxcdn.com.
deb-f3a0.kxcdn.com.	3600	IN	CNAME	c-ca00.kvcdn.com.
c-ca00.kvcdn.com.	407	IN	CNAME	p-camo00.kxcdn.com.
p-camo00.kxcdn.com.	37	IN	A	192.99.233.195
```

looks like a correct answer, but something is caching the cdn.sury.org redirection somewhere.  Do you perhaps have a web proxy between you and the network?

**Comment by oerdnj** [comment] 2019-02-26 15:16
@MacTrophy I change the redirection URL on the old site to: `deb-f3a0.kxcdn.com.`, so the `cdn.sury.org` URL should not be present anywhere.

**Comment by oerdnj** [comment] 2019-02-26 15:16
@tanertas This is an issue tracker for the problems with the packages, not for your connectivity problems.  As I said, I can't help you with that beyond the basic debugging.

**Comment by MacTrophy** [comment] 2019-02-26 15:20
Ok it works now, I restarted my apt-cacher-ng on our local server, it was probably where something was cached

Thank you @oerdnj, your help is appreciated, I learned something here!
