### ISSUE TITLE
ppa:ondrej/php is unstable for a moment due 8GB limit (in progress)

### ISSUE THREAD

**Issue by alcaeus** [oerdnj/deb.sury.org#663] opened 2017-08-04 12:34 UTC
Currently, the `php-mongodb` package is not installable:
```
root@box:/home/ubuntu# aptitude install php7.1-mongodb
Note: selecting "php-mongodb" instead of the
      virtual package "php7.1-mongodb"
The following NEW packages will be installed:
  php-mongodb{b} 
0 packages upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/407 kB of archives. After unpacking 2,518 kB will be used.
The following packages have unmet dependencies:
 php-mongodb : Depends: libssl1.0.2 (>= 1.0.2d) but it is not installable.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     php-mongodb [Not Installed]                        
```

libssl1.0.2 is also not installable:
```
root@box:/home/ubuntu# aptitude install libssl1.0.2
No candidate version found for libssl1.0.2
No candidate version found for libssl1.0.2
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by oerdnj** [comment] 2017-08-04 13:01
Unfortunately, the repository grew-up over 8GB, and I am unable to do anything with it until:
a) https://answers.launchpad.net/launchpad/+question/655287 is solved
b) the repository size is recalculated again, because I have deleted some packages to free up more space, but obviously it didn't trigger the space recalculation

**Comment by alcaeus** [comment] 2017-08-04 13:02
Thanks for the quick feedback. That is indeed unfortunate. Is there any way we can install libssl1.0.2 in the meantime?

**Comment by oerdnj** [comment] 2017-08-04 13:11
Just a sec, I might have find a bug in launchpad :). Copying package from different repository doesn't enforce the size limit, so I might be able to fix the repository state in couple of minutes.

**Comment by navarr** [comment] 2017-08-04 13:18
Imagine my surprise when php7.0-common couldn't be found.

Thanks for your hard work!

**Comment by oerdnj** [comment] 2017-08-04 13:22
Oh, if you are by any chance on yakkety, it has reached it's end-of-life on July 20, so I have removed all the packages for yakkety to save a space.

**Comment by alcaeus** [comment] 2017-08-04 13:31
@oerdnj thank you for your work resolving this. In the meantime, I got it to work using `ppa:blubolt/openssl1.0`. Not optimal, but it installs.

**Comment by navarr** [comment] 2017-08-04 13:46
@oerdnj I'm running on trusty

**Comment by flaviomoringa** [comment] 2017-08-04 14:50
This is critical for people using php7.0 or 7.1 on trusty... I'm using it in production, and new servers aren't able to install the php7.0 stack.

Could you remove php7.2 and do a new update so that at least 7.0 and 7.1 works... and then add 7.2 when you get the size increase?

**Comment by oerdnj** [comment] 2017-08-04 14:52
@flaviomoringa That doesn't help. The problem is that the repository size calculation isn't instant after you delete the packages, but it takes some time to recalculate, and that's why it's over limit now.

You'll just have to be patient a little bit, it should settle down in a couple more minutes.

**Comment by flaviomoringa** [comment] 2017-08-04 14:53
Sorry if I seem anxious, but it's affecting our production servers autoscalling.. on a friday :-(
I really hope  it's fixed soon....

**Comment by oerdnj** [comment] 2017-08-04 14:56
The launchpad amd64 builders seems to be overloaded, but many of the packages have already been rebuilt.

**Comment by oerdnj** [comment] 2017-08-04 15:16
Also please understand that it always was and it always will be a "best effort" service, so you should be running something like local apt mirror or some other measures, if your business direly depends on the PPA. (Some applies to launchpad, I don't think Canonical guarantee any SLA on the service.)

**Comment by flaviomoringa** [comment] 2017-08-04 15:20
You are right of course, but because we never had any issues it didn't came up... We will change it asap... but for now it would be really important to at least work as it was...

**Comment by oerdnj** [comment] 2017-08-04 15:28
If you absolutely need php7.0 amd64 packages for trusty, they can be downloaded here: https://launchpad.net/~ondrej/+archive/ubuntu/php/+build/13198163

Or just wait, and they will land in the repository in couple minutes (depends on launchpad, usually 10-20 minutes).

**Comment by flaviomoringa** [comment] 2017-08-04 15:30
We've made a hot fix that will hold for now some services... so we'll wait for launchpad... let's just hope it's 10-20 min :-)

**Comment by oerdnj** [comment] 2017-08-04 15:36
```
php7.0-common:
  Installed: (none)
  Candidate: 7.0.22-2+ubuntu14.04.1+deb.sury.org+4
  Version table:
     7.0.22-2+ubuntu14.04.1+deb.sury.org+4 0
        500 http://ppa.launchpad.net/ondrej/php/ubuntu/ trusty/main amd64 Packages
```

**Comment by flaviomoringa** [comment] 2017-08-04 15:56
Working... thanks

**Comment by oerdnj** [comment] 2017-08-04 16:00
Also the mongodb packages has been rebuilt now (and will take couple minutes to install into the archive), so I am closing the issue now. Please open individual issues if there's error with other packages.

**Closed by oerdnj** 2017-08-04 16:00 UTC

**Comment by alcaeus** [comment] 2017-08-04 16:09
@oerdnj thank you very much for your help and work you put in to provide these packages. ❤️

**Comment by dominikzogg** [comment] 2017-08-04 20:49
@oerdnj thank you for getting the ppa up and running again!
