### ISSUE TITLE
Some php7.0-fpm installation problems

### ISSUE THREAD

**Issue by markc** [oerdnj/deb.sury.org#94] opened 2015-08-03 03:50 UTC
Either the exec reference in the systemd startup file or the name of the installed fpm binary is wrong. I'd say the binary should be called /usr/sbin/php7.0-fpm.
```
Aug 03 03:13:18 gc5 systemd[3166]: php7.0-fpm.service:
Failed at step EXEC spawning /usr/sbin/php7.0-fpm: No such file or directory
~ ll /usr/sbin/*fpm*
-rwxr-xr-x 1 root root 4237712 Aug  2 09:51 /usr/sbin/php-fpm7.0*
```
Also the last line of /etc/php/7.0/fpm/php-fpm.conf is wrong, it should be...
```
;include=/etc/pool.d/*.conf
include=/etc/php/7.0/fpm/pool.d/*.conf
```
and this default pool conf file is missing altogether but might be related to the above incorrect pool path (I co-installed php5-fpm and copied the one from it)...
```
/etc/php/7.0/fpm/pool.d/www.conf
```
And finally, when installing php5-fpm it brought in these extra dependencies which php7.0-fpm did not so I suspect libxml2 should also be a dependency of php7.0 (maybe).
```
~ apt-get install php5-fpm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libicu52 libxml2 lsof php5-cli php5-common php5-json php5-readline sgml-base xml-core
```

**Comment by markc** [comment] 2015-08-03 04:23
I forgot to mention this but the current /etc/php/7.0 config dir is rather awkward. It would be neater and make sense if php5 was also installed to /etc/php/5 but it isn't and I can't imagine the current php5 packages ever being modified from /etc/php5 to /etc/php/5 (a pity as a single /etc/php would be nice) so it's probably easier to go with /etc/php7.0 rather than the current /etc/php/7.0. FWIW IMHO.

Of course if the intention is to eventually unify all versions of php to a single /etc/php config dir then that's great (assuming pid and log settings all match too).

**Comment by oerdnj** [comment] 2015-08-03 06:41
> the binary should be called /usr/sbin/php7.0-fpm

The name of the binary is decided by upstream build system, it's just slightly inconsistent sometimes with packaging.

> and this default pool conf file is missing altogether but might be related to the above incorrect pool path (I co-installed php5-fpm and copied the one from it)...

The cause was different, but it should be fixed now.

> And finally, when installing php5-fpm it brought in these extra dependencies which php7.0-fpm did not so I suspect libxml2 should also be a dependency of php7.0 (maybe).

That's ok, I moved most of the modules out of the SAPIs, so it will get pulled from something else. Also PEAR that required libxml is not longer built from src:phpX.Y.

>  I can't imagine the current php5 packages ever being modified from /etc/php5 to /etc/php/5.5 and /etc/php/5.6

You should dream a bit more :). That's exactly the plan. I don't have a transition plan for configuration files, but I will come up with something. (The last resort would be to not have a automatic conversion in place, since the default PHP in stretch will be PHP 7.0.)

**Comment by markc** [comment] 2015-08-03 10:37
One runtime issue with /usr/bin/php7.0. I straced this but nothing obvious and no sign of any "phar" related package to install...
```
~ curl -s -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
~ chmod +x wp-cli.phar &&  mv wp-cli.phar /usr/local/bin/wp
~ wp --help
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/local/bin/wp:3
Stack trace:
#0 {main}
  thrown in /usr/local/bin/wp on line 3
```
At least WordPress 4.2.3 seems to run and first impression is that it does indeed seem snappier. For the record (so I can google it in the future) these are the exact set of packages I installed for WP...
```
php5-common
php7.0-cli
php7.0-common
php7.0-fpm
php7.0-phpdbg
php-common
php-curl
php-gd
php-imap
php-intl
php-json
php-mcrypt
php-mysql
php-readline
php-xmlrpc
php-zip
```

**Comment by markc** [comment] 2015-08-03 10:54
FWIW. Looks like a fresh update of the core php7.0 packages. I got this error previously and again just now...
```
Get:1 http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/ wily/main php7.0-phpdbg amd64 7.0.0~beta2-7+deb.sury.org~wily+1 [1,394 kB]
Get:2 http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/ wily/main php7.0-fpm amd64 7.0.0~beta2-7+deb.sury.org~wily+1 [1,370 kB]                                
Get:3 http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/ wily/main php7.0-cli amd64 7.0.0~beta2-7+deb.sury.org~wily+1 [1,342 kB]                                
Get:4 http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/ wily/main php7.0-common all 7.0.0~beta2-7+deb.sury.org~wily+1 [67.5 kB]                                
Fetched 4,174 kB in 18s (230 kB/s)                                                                                                                           
(Reading database ... 17736 files and directories currently installed.)
Preparing to unpack .../php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb ...
Unpacking php7.0-phpdbg (7.0.0~beta2-7+deb.sury.org~wily+1) over (7.0.0~beta2-3+deb.sury.org~wily+1) ...
dpkg: warning: subprocess old post-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
dpkg: error processing archive /var/cache/apt/archives/php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb (--unpack):
 subprocess new post-removal script returned error exit status 1
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
Preparing to unpack .../php7.0-fpm_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb ...
Unpacking php7.0-fpm (7.0.0~beta2-7+deb.sury.org~wily+1) over (7.0.0~beta2-3+deb.sury.org~wily+1) ...
Preparing to unpack .../php7.0-cli_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb ...
Unpacking php7.0-cli (7.0.0~beta2-7+deb.sury.org~wily+1) over (7.0.0~beta2-3+deb.sury.org~wily+1) ...
Preparing to unpack .../php7.0-common_7.0.0~beta2-7+deb.sury.org~wily+1_all.deb ...
Unpacking php7.0-common (7.0.0~beta2-7+deb.sury.org~wily+1) over (7.0.0~beta2-3+deb.sury.org~wily+1) ...
Processing triggers for systemd (223-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 /var/cache/apt/archives/php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
And of course trying to remove it to attempt a reinstall gets the usual catch22...
```
[...]
dpkg: error processing package php7.0-phpdbg (--purge):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting a removal
Errors were encountered while processing:
 php7.0-phpdbg
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by markc** [comment] 2015-08-03 11:14
I edited the postinst, postrm and prerm scripts to add set -x but I still couldn't pick up what the above error is. Maybe this is useful for you (from inside a wily lxd container).
```
~ cp /var/cache/apt/archives/php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb .
~ dpkg-deb --extract php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb php7.0-phpdbg
~ dpkg-deb --control php7.0-phpdbg_7.0.0~beta2-7+deb.sury.org~wily+1_amd64.deb php7.0-phpdbg/DEBIAN

# add set -x to each of these below
~ e php7.0-phpdbg/DEBIAN/postinst 
~ e php7.0-phpdbg/DEBIAN/postrm
~ e php7.0-phpdbg/DEBIAN/prerm

~ dpkg-deb --build php7.0-phpdbg
dpkg-deb: building package 'php7.0-phpdbg' in 'php7.0-phpdbg.deb'.
~ dpkg -i php7.0-phpdbg.deb
Selecting previously unselected package php7.0-phpdbg.
(Reading database ... 17736 files and directories currently installed.)
Preparing to unpack php7.0-phpdbg.deb ...
Unpacking php7.0-phpdbg (7.0.0~beta2-7+deb.sury.org~wily+1) over (7.0.0~beta2-3+deb.sury.org~wily+1) ...
dpkg: warning: subprocess old post-removal script returned error exit status 1
dpkg: trying script from the new package instead ...
+ set -e
+ '[' failed-upgrade = purge ']'
+ '[' -e /usr/lib/php/php-maintscript-helper ']'
+ . /usr/lib/php/php-maintscript-helper
++ '[' -n '' ']'
++ EXPORT_PHP_MAINTSCRIPT_HELPER=1
++ '[' -n '' ']'
++ '[' -z failed-upgrade ']'
++ PHP_MAINTSCRIPT_NAME=postrm
++ '[' postrm ']'
++ case "$PHP_MAINTSCRIPT_NAME" in
++ PHP_MAINTSCRIPT_PACKAGE=php7.0-phpdbg
++ '[' -z php7.0-phpdbg ']'
++ '[' -z '' ']'
++ PHP_MAINTSCRIPT_METHOD=failed-upgrade
++ case "$PHP_MAINTSCRIPT_METHOD" in
++ '[' -z '' ']'
++ PHP_MAINTSCRIPT_ARGUMENT=7.0.0~beta2-3+deb.sury.org~wily+1
++ phpquery -M -v 7.0
+ mods='readline
mysqli
pdo_mysql
json
curl
gd
imap
intl
mcrypt
xmlrpc
zip
opcache'
+ for mod in '$mods'
+ php_invoke dismod 7.0 phpdbg readline
+ local CMD=dismod
+ local VERSION=7.0
+ local SAPI=phpdbg
+ local MOD=readline
+ local check_switch=
+ local invoke_string=
+ local rcd_action=
+ local rcd_scripts=
+ local sapi_list=
+ '[' -x /usr/sbin/phpdismod ']'
+ '[' -x /usr/sbin/phpquery ']'
+ version_list=7.0
+ case "$VERSION" in
+ for VERSION in '$version_list'
+ sapi_list=phpdbg
+ case "$SAPI" in
+ return 1
dpkg: error processing archive php7.0-phpdbg.deb (--install):
 subprocess new post-removal script returned error exit status 1
+ set -e
+ '[' abort-upgrade = purge ']'
+ '[' -e /usr/lib/php/php-maintscript-helper ']'
+ . /usr/lib/php/php-maintscript-helper
++ '[' -n '' ']'
++ EXPORT_PHP_MAINTSCRIPT_HELPER=1
++ '[' -n '' ']'
++ '[' -z abort-upgrade ']'
++ PHP_MAINTSCRIPT_NAME=postrm
++ '[' postrm ']'
++ case "$PHP_MAINTSCRIPT_NAME" in
++ PHP_MAINTSCRIPT_PACKAGE=php7.0-phpdbg
++ '[' -z php7.0-phpdbg ']'
++ '[' -z '' ']'
++ PHP_MAINTSCRIPT_METHOD=abort-upgrade
++ case "$PHP_MAINTSCRIPT_METHOD" in
++ '[' -z '' ']'
++ PHP_MAINTSCRIPT_ARGUMENT=7.0.0~beta2-3+deb.sury.org~wily+1
++ phpquery -M -v 7.0
+ mods='readline
mysqli
pdo_mysql
json
curl
gd
imap
intl
mcrypt
xmlrpc
zip
opcache'
+ for mod in '$mods'
+ php_invoke dismod 7.0 phpdbg readline
+ local CMD=dismod
+ local VERSION=7.0
+ local SAPI=phpdbg
+ local MOD=readline
+ local check_switch=
+ local invoke_string=
+ local rcd_action=
+ local rcd_scripts=
+ local sapi_list=
+ '[' -x /usr/sbin/phpdismod ']'
+ '[' -x /usr/sbin/phpquery ']'
+ version_list=7.0
+ case "$VERSION" in
+ for VERSION in '$version_list'
+ sapi_list=phpdbg
+ case "$SAPI" in
+ return 1
dpkg: error while cleaning up:
 subprocess new post-removal script returned error exit status 1
Errors were encountered while processing:
 php7.0-phpdbg.deb
```

**Comment by oerdnj** [comment] 2015-08-03 11:29
Found it: php-maintscript-helper was missing phpdbg switch. Upgrade to php-common_8 before trying again.

**Comment by markc** [comment] 2015-08-03 11:43
No _8 at http://ppa.launchpad.net/ondrej/php-7.0/ubuntu/pool/main/p/php7.0/ yet and it's nearly 10pm here so I'll continue and confirm in the morning. Thank you for all you effort on this and the courier packages.

**Comment by oerdnj** [comment] 2015-08-03 12:30
It was built 49 minutes ago: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0/+builds?build_text=&build_state=built

**Comment by oerdnj** [comment] 2015-08-03 13:04
The situation with php-pear (+phar) has to be yet resolved - we have a meeting at DebConf15 with more people, so we'll probably fix it there; together with preparing at least one of php-5.x (I think we will start with php-5.6) to the new format.

**Comment by oerdnj** [comment] 2015-08-10 14:01
I believe this has been resolved.

**Closed by oerdnj** 2015-08-10 14:01 UTC
