### ISSUE TITLE
CLI Error  Unable to load dynamic library '/usr/lib/php/20151012/zlib.so'

### ISSUE THREAD

**Issue by Shaeldon** [oerdnj/deb.sury.org#293] opened 2016-03-08 09:35 UTC
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/zlib.so' - /usr/lib/php/20151012/zlib.so: cannot open shared object file: No such file or directory in Unknown on line 0

updated an hour ago~

**Comment by oerdnj** [comment] 2016-03-08 10:17
@Shaeldon Could you run: `sh -x /var/lib/dpkg/info/php7.0-common.preinst upgrade` and paste output here? The dynamically loaded extension should have been disabled by preinst script and I am interested why this isn't the case.

**Comment by Shaeldon** [comment] 2016-03-08 10:26
@oerdnj I'll assume you ment me to run that as root? Then see this link: http://pastebin.com/3P5fUJt8
otherwise it would be this: http://pastebin.com/qsRDnk63
Thanks for your help

**Comment by oerdnj** [comment] 2016-03-08 11:04
@Shaeldon Yeah, as a root.

Could you also do: `grep -r zlib.so /etc/php`?

**Comment by Shaeldon** [comment] 2016-03-09 08:39
@oerdnj uh well that returns nothing

**Comment by cerlestes** [comment] 2016-03-09 08:40
The problem is that upgrading from 7.0.3 to 7.0.4 (or anywhere in between) doesn't remove the previously created /etc/php/mods-available/zlib.ini - you'll have to remove that manually. After that no more startup error occurs.

**Comment by oerdnj** [comment] 2016-03-09 08:52
@cerlestes I think I know, it would work for incremental updates, but not if you skipped some steps. Let me prepare a test release to php-qa and it would be tremendous if you could test it on your third server. Thank you that you thought about that.

**Comment by cerlestes** [comment] 2016-03-09 09:06
@oerdnj Sure, let me know when I should try. Interestingly on our dev machines running `7.0.3-11+deb.sury.org~trusty+1`, zlib.so is located in the correct directory: `/etc/php/7.0/mods-available/`

**Comment by cerlestes** [comment] 2016-03-09 09:11
@Shaeldon Did deleting those files work for you?

**Comment by oerdnj** [comment] 2016-03-09 09:38
@cerlestes that depends whether you have updated from (ver << 7.0.3-11) or (7.0.3-11 <= ver << 7.0.4-3). If former the break will occur, if later the your config files have already been updated.

In 7.0.4-3 the zlib has been removed from the list of extensions to be upgraded from `/etc/php/mods-available` to `/etc/php/X.Y/mods-available`, but the preinst script has just cleaned `/etc/php/X.Y/mods-available/zlib.ini`.

This should be fixed in `7.0.4-4+deb.sury.org~*+1`. After builds in php-qa PPA: https://launchpad.net/~ondrej/+archive/ubuntu/php-qa/+packages?batch=200 are finished, you can try upgrading the last server.

**Comment by oerdnj** [comment] 2016-03-09 09:39
@Shaeldon if you are still getting the error, but the grep is showing nothing, than you must have a custom configuration that loads the zlib extension in some other place.

**Comment by cerlestes** [comment] 2016-03-09 10:06
@oerdnj Working fine for us now! Thanks again for your service.

```
xxx@xxx:/etc/php# ll mods-available
ls: cannot access /etc/php/mods-available: No such file or directory
xxx@xxx:/etc/php# service php7.0-fpm restart
 * Restarting PHP 7.0 FastCGI Process Manager php-fpm7.0   [ OK ]
```

**Comment by oerdnj** [comment] 2016-03-09 10:09
Ok, re-uploading to the main repository.

**Closed by oerdnj** 2016-03-09 10:09 UTC

**Comment by oerdnj** [comment] 2016-03-09 10:10
@cerlestes Don't forget to remove `ppa:ondrej/php-qa` afterwards, so you don't get the random testing stuff I might upload there in the future.

**Comment by cerlestes** [comment] 2016-03-09 10:10
Sure :)

**Comment by Shaeldon** [comment] 2016-03-09 14:54
@oerdnj and @cerlestes Thjanks for your help everything is running again!
